Pocket/pocket-ios

Pocket.xcodeproj/project.pbxproj
- Add cert/provisioning identifiers for debug and release builds
=> project: set up signing/provisioning

Pocket.xcodeproj/project.pbxproj, Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Pocket.xcodeproj/xcshareddata/xcschemes/Pocket (iOS).xcscheme, PocketTests/AccessTokenStoreTests.swift, PocketTests/Support/Calls.swift, PocketTests/Support/MockKeychain.swift, Shared/Authorization/AccessTokenStore.swift, Shared/Authorization/AuthorizationClient.swift, Shared/Environment.swift, Shared/Keychain.swift, Shared/LoggedInView.swift, Shared/PocketApp.swift, Shared/SignInView.swift, Tests iOS/Tests_iOS.swift, iOS/Info.plist
Co-authored-by: David Skuza <dskuza@getpocket.com>
=> feat(auth): persist access token

Pocket.xcodeproj/project.pbxproj, Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Pocket.xcodeproj/xcshareddata/xcschemes/Pocket (iOS).xcscheme, Pocket.xcodeproj/xcshareddata/xcschemes/Pocket (macOS).xcscheme, Pocket.xcodeproj/xcshareddata/xcschemes/Sync.xcscheme
Had to rejigger the Apollo framework for some reason?
=> Open the project in Xcode Beta

Shared/Item/ItemDestinationView.swift, Shared/Item/ItemListView.swift, Sync/API.swift, Sync/Item+Extensions.swift, Sync/PocketModel.xcdatamodeld/PocketModel.xcdatamodel/contents, Sync/list.graphql, Sync/schema.json, SyncTests/Fixtures/duplicate-list.json, SyncTests/Fixtures/list.json, SyncTests/Fixtures/updated-item.json, SyncTests/SourceTests.swift, Tests iOS/Fixtures/initial-list.json, Tests iOS/Fixtures/particle-sample.json, Tests iOS/Fixtures/updated-list.json, Tests iOS/Support/Fixture.swift, Tests iOS/Tests_iOS.swift, download-schema
- Update graphic schema and query to fetch particleJson
- Extract the JSON from the response and store it in core data
- Use the stored JSON when rendering an article view
=> Particle from server

Pocket.xcodeproj/project.pbxproj, Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, PocketTests/AuthorizationClientTests.swift, Shared/Authorization/AuthorizationClient.swift, Shared/Authorization/AuthorizeResponse.swift, Shared/Keys.swift, Shared/PocketApp.swift, Shared/SignInView.swift, Tests iOS/Fixtures/successful-auth.json, iOS/Info.plist
- Initialize sentry in PocketApp.init
- Attach user id after user signs in
=> Setup sentry

PocketKit/Sources/PocketKit/SignInView.swift, PocketKit/Sources/Textile/Style/Style+SwiftUI.swift, PocketKit/Sources/Textile/Style/Style.swift, Tests iOS/Support/Elements/SignInScreen.swift
This pull request introduces a minor redesign of the sign-in view in preparation for more testing.
=> feat: redesign sign-in view

PocketKit/Sources/Sync/API.swift, PocketKit/Sources/Sync/Item+Extensions.swift, PocketKit/Sources/Sync/PocketModel.xcdatamodeld/PocketModel.xcdatamodel/contents, PocketKit/Sources/Sync/Requests.swift, PocketKit/Sources/Sync/Source.swift, PocketKit/Sources/Sync/list.graphql, PocketKit/Sources/Sync/schema.json, PocketKit/Tests/SyncTests/Fixtures/duplicate-list.json, PocketKit/Tests/SyncTests/Fixtures/large-list-1.json, PocketKit/Tests/SyncTests/Fixtures/large-list-2.json, PocketKit/Tests/SyncTests/Fixtures/large-list-3.json, PocketKit/Tests/SyncTests/Fixtures/list.json, PocketKit/Tests/SyncTests/Fixtures/paginated-list-1.json, PocketKit/Tests/SyncTests/Fixtures/paginated-list-2.json, PocketKit/Tests/SyncTests/Fixtures/updated-item.json, PocketKit/Tests/SyncTests/SourceTests.swift, Tests iOS/Fixtures/initial-list.json, Tests iOS/Fixtures/list-with-archived-item.json, Tests iOS/Fixtures/updated-list.json, Tests iOS/Tests_iOS.swift
- Update graphql schema
- Query for `isArchived` property of SavedItem
- Include `isArchived: false` filter when fetching data from API
- Persist `isArchived` property in core data
- Add `isArchived = false` predicate to Item fetch request
=> feat: exclude archived items from list

PocketKit/Sources/PocketKit/Authorization/AccessTokenStore.swift, PocketKit/Sources/PocketKit/Authorization/SignOutOnFirstLaunch.swift, PocketKit/Sources/PocketKit/PocketApp.swift, PocketKit/Sources/PocketKit/Services.swift, PocketKit/Tests/PocketKitTests/AccessTokenStoreTests.swift, PocketKit/Tests/PocketKitTests/SignOutOnFirstLaunchTests.swift
https://getpocket.atlassian.net/browse/IN-165
=> Clear keychain when launching app after fresh install

PocketKit/Sources/PocketKit/PocketSceneCoordinator.swift
- Update button style to avoid deprecation warning
- Fix presentation of reader settings on iPad (it was presenting as modal instead of popover)
- Listen for item selection on main thread
=> Small bug fixes

PocketKit/Sources/PocketKit/Article/ActivityItemSource.swift, PocketKit/Sources/PocketKit/Article/ArticleViewController.swift, PocketKit/Sources/PocketKit/Article/TextContentCell.swift
https://getpocket.atlassian.net/browse/IN-93
=> Include item URL and title when sharing selected text

PocketKit/Sources/PocketKit/Item/ItemListView.swift, PocketKit/Sources/PocketKit/Item/ItemPresenter.swift, PocketKit/Sources/PocketKit/PocketSceneCoordinator.swift, PocketKit/Sources/Textile/Views/ItemRow.swift, Tests iOS/ArchiveAnItemTests.swift, Tests iOS/DeleteAnItemTests.swift, Tests iOS/Support/Elements/ItemElement.swift, Tests iOS/Support/Elements/PocketApp.swift, Tests iOS/Tests_iOS.swift
https://getpocket.atlassian.net/browse/IN-238
=> Use a menu for item actions instead of swipe actions

Pocket.xcodeproj/project.pbxproj, Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, PocketKit/Sources/PocketKit/Item/ItemPresenter.swift, PocketKit/Sources/Textile/Views/ActivitySheet.swift, PocketKit/Sources/Textile/Views/ItemRow.swift, Tests iOS/ShareAnItemTests.swift, Tests iOS/Support/Elements/PocketApp.swift
https://getpocket.atlassian.net/browse/IN-175
=> Supporting sharing an item from list (via share sheet)

PocketKit/Sources/Analytics/UIContext.swift, PocketKit/Sources/PocketKit/Item/ItemListView.swift, PocketKit/Sources/PocketKit/Item/ItemPresenter.swift, PocketKit/Sources/PocketKit/Item/ItemViewController.swift, PocketKit/Sources/Textile/Views/ItemRow.swift
This builds on #49 and #50 so let's get those reviewed and merged before diving to deep into discussing this one
https://getpocket.atlassian.net/browse/IN-149
https://getpocket.atlassian.net/browse/IN-150
=> Track analytics events for item actions

PocketKit/Sources/PocketKit/PocketSceneCoordinator.swift
https://getpocket.atlassian.net/browse/IN-208
=> Clear selection when popping back to list

Pocket.xcodeproj/project.pbxproj, PocketKit/Sources/PocketKit/Authorization/AccessTokenStore.swift, PocketKit/Sources/PocketKit/Item/ItemListView.swift, PocketKit/Sources/PocketKit/PocketSceneCoordinator.swift, PocketKit/Sources/PocketKit/Services.swift, PocketKit/Sources/Sync/LastRefresh.swift, PocketKit/Sources/Sync/Operations/FetchList.swift, PocketKit/Sources/Sync/Operations/SyncOperationFactory.swift, PocketKit/Sources/Sync/Source+async.swift, PocketKit/Sources/Sync/Source.swift, PocketKit/Tests/PocketKitTests/AccessTokenStoreTests.swift, PocketKit/Tests/SyncTests/Fixtures/empty-list.json, PocketKit/Tests/SyncTests/Operations/FetchListTests.swift, PocketKit/Tests/SyncTests/SourceTests.swift, PocketKit/Tests/SyncTests/Support/MockAccessTokenProvider.swift, PocketKit/Tests/SyncTests/Support/MockLastRefresh.swift, PocketKit/Tests/SyncTests/Support/MockOperationFactory.swift, Tests iOS/PullToRefreshTests.swift, Tests iOS/Support/Elements/UserListScreen.swift
https://getpocket.atlassian.net/browse/IN-207
=> Add pull to refresh to "My List"

PocketKit/Sources/Sync/ApolloClientProtocol+Extensions.swift, PocketKit/Sources/Sync/Operations/FetchList.swift, PocketKit/Tests/SyncTests/Operations/FetchListTests.swift
https://getpocket.atlassian.net/browse/IN-267
=> Only fetch unread items on initial list download

Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, PocketKit/Package.resolved, PocketKit/Package.swift, PocketKit/Sources/Sync/API.swift, PocketKit/Sources/Sync/Item+Extensions.swift, PocketKit/Sources/Sync/list.graphql, PocketKit/Sources/Sync/schema.json, PocketKit/Tests/SyncTests/Fixtures/duplicate-list.json, PocketKit/Tests/SyncTests/Fixtures/large-list-1.json, PocketKit/Tests/SyncTests/Fixtures/large-list-2.json, PocketKit/Tests/SyncTests/Fixtures/large-list-3.json, PocketKit/Tests/SyncTests/Fixtures/list.json, PocketKit/Tests/SyncTests/Fixtures/paginated-list-1.json, PocketKit/Tests/SyncTests/Fixtures/paginated-list-2.json, PocketKit/Tests/SyncTests/Fixtures/updated-item.json, Tests iOS/Fixtures/initial-list.json, Tests iOS/Fixtures/list-with-archived-item.json, Tests iOS/Fixtures/updated-list.json
API now returns ItemResult (which is either an Item or a PendingItem).
So we use fragements to determine which fields we would like to select.
https://getpocket.atlassian.net/browse/IN-301
=> Handle updated API schema

PocketKit/Sources/Sync/API.swift, PocketKit/Sources/Sync/Slates/Slate+remoteMapping.swift, PocketKit/Sources/Sync/Slates/SlateService.swift, PocketKit/Sources/Sync/Source.swift, PocketKit/Sources/Sync/list.graphql, PocketKit/Tests/SyncTests/APISlateServiceTests.swift, PocketKit/Tests/SyncTests/Fixtures/slate-detail.json, PocketKit/Tests/SyncTests/SourceTests.swift, PocketKit/Tests/SyncTests/Support/MockSlateService.swift
https://getpocket.atlassian.net/browse/IN-190
=> Add `fetchSlate(_:)` to SlateService

Pocket.xcodeproj/project.pbxproj, PocketKit/Sources/PocketKit/Home/HomeViewController.swift, PocketKit/Sources/PocketKit/Home/RecommendationPresenter.swift, PocketKit/Sources/PocketKit/Home/SlateDetailViewController.swift, PocketKit/Sources/Sync/Slates/Slate.swift, Tests iOS/HomeTests.swift, Tests iOS/Support/Elements/PocketAppElement.swift, Tests iOS/Support/Elements/SlateDetailElement.swift
https://getpocket.atlassian.net/browse/IN-190
=> Add slate detail view on tap

PocketKit/Sources/PocketKit/Activity/PocketItemActivity.swift, PocketKit/Sources/PocketKit/Article/ArticleViewController.swift, PocketKit/Sources/PocketKit/Article/Item+Readable.swift, PocketKit/Sources/PocketKit/Article/Recommendation+Readable.swift, PocketKit/Sources/PocketKit/Home/HomeViewController.swift, PocketKit/Sources/PocketKit/Home/SlateDetailViewController.swift, PocketKit/Sources/PocketKit/Item/Item+Extensions.swift, PocketKit/Sources/PocketKit/Item/ItemViewController.swift, PocketKit/Sources/PocketKit/Main/CompactMainCoordinator.swift, PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift, PocketKit/Sources/Textile/Style/Paragraph/TextAlignment.swift, Tests iOS/ArchiveAnItemTests.swift, Tests iOS/DeleteAnItemTests.swift, Tests iOS/FavoriteAnItemTests.swift, Tests iOS/Fixtures/slate-detail.json, Tests iOS/Fixtures/slates.json, Tests iOS/HomeTests.swift, Tests iOS/PullToRefreshTests.swift, Tests iOS/ShareAnItemTests.swift, Tests iOS/Tests_iOS.swift
https://getpocket.atlassian.net/browse/IN-196
=> Show recommendations in reader on selection

PocketKit/Sources/PocketKit/Article/ArticleMetadataPresenter.swift, PocketKit/Sources/PocketKit/Article/ArticleViewController.swift, PocketKit/Sources/PocketKit/Article/Cells/ArticleMetadataCell.swift, PocketKit/Sources/Textile/Style/Paragraph/ParagraphStyle.swift, PocketKit/Sources/Textile/Style/Style+Definitions.swift, PocketKit/Sources/Textile/Style/Style+UIKit.swift, PocketKit/Sources/Textile/Textiles.swift
This is the first change in a larger set of changes to design & styling of the native reader view. I'll be creating all PRs against the `marticle-updates` branch and using separate PRs for each component. Once each component PR is merged, we can review all the changes together before merging into `develop`
=> Update Article title & metadata cell in reader

PocketKit/Sources/PocketKit/Article/ArticleMetadataPresenter.swift, PocketKit/Sources/PocketKit/Article/ArticleViewController.swift, PocketKit/Sources/PocketKit/Article/Cells/ArticleMetadataCell.swift, PocketKit/Sources/PocketKit/Article/Cells/BlockquoteComponentCell.swift, PocketKit/Sources/PocketKit/Article/Cells/CodeBlockComponentCell.swift, PocketKit/Sources/PocketKit/Article/Cells/DIviderComponentCell.swift, PocketKit/Sources/PocketKit/Article/Cells/ImageComponentCell.swift, PocketKit/Sources/PocketKit/Article/Cells/MarkdownComponentCell.swift, PocketKit/Sources/PocketKit/Article/Presenters/BlockquoteComponentPresenter.swift, PocketKit/Sources/PocketKit/Article/Presenters/CodeBlockPresenter.swift, PocketKit/Sources/PocketKit/Article/Presenters/DividerComponentPresenter.swift, PocketKit/Sources/PocketKit/Article/Presenters/ImageComponentPresenter.swift, PocketKit/Sources/PocketKit/Article/Presenters/ListComponentPresenter.swift, PocketKit/Sources/PocketKit/Article/Presenters/MarkdownComponentPresenter.swift, PocketKit/Sources/Textile/NSAttributedString+Extensions.swift, PocketKit/Sources/Textile/Style/Style+Definitions.swift
Take a look at #104 before this one!
The only new commit is the last one: 5deff4d3d9ac38205695b16e09ababc1909760bc
=> Marticle everything else

PocketKit/Sources/PocketKit/Article/ArticleMetadataPresenter.swift, PocketKit/Sources/PocketKit/Article/ArticleViewController.swift, PocketKit/Sources/PocketKit/Article/Cells/ArticleMetadataCell.swift, PocketKit/Sources/PocketKit/Article/Cells/BlockquoteComponentCell.swift, PocketKit/Sources/PocketKit/Article/Cells/CodeBlockComponentCell.swift, PocketKit/Sources/PocketKit/Article/Cells/DIviderComponentCell.swift, PocketKit/Sources/PocketKit/Article/Cells/ImageComponentCell.swift, PocketKit/Sources/PocketKit/Article/Cells/MarkdownComponentCell.swift, PocketKit/Sources/PocketKit/Article/Presenters/BlockquoteComponentPresenter.swift, PocketKit/Sources/PocketKit/Article/Presenters/CodeBlockPresenter.swift, PocketKit/Sources/PocketKit/Article/Presenters/DividerComponentPresenter.swift, PocketKit/Sources/PocketKit/Article/Presenters/ImageComponentPresenter.swift, PocketKit/Sources/PocketKit/Article/Presenters/ListComponentPresenter.swift, PocketKit/Sources/PocketKit/Article/Presenters/MarkdownComponentPresenter.swift, PocketKit/Sources/Textile/NSAttributedString+Extensions.swift, PocketKit/Sources/Textile/Style/Paragraph/ParagraphStyle.swift, PocketKit/Sources/Textile/Style/Style+Definitions.swift, PocketKit/Sources/Textile/Style/Style+UIKit.swift, PocketKit/Sources/Textile/Style/Typography/FontDescriptor.swift, PocketKit/Sources/Textile/Textiles.swift, Tests iOS/HomeTests.swift, Tests iOS/Tests_iOS.swift
Cumulative changes from these PRs:
https://github.com/Pocket/pocket-ios/pull/102
https://github.com/Pocket/pocket-ios/pull/103
https://github.com/Pocket/pocket-ios/pull/104
https://github.com/Pocket/pocket-ios/pull/105
=> Marticle updates

PocketKit/Package.swift, PocketKit/Sources/PocketKit/Article/ArticleViewController.swift, PocketKit/Sources/PocketKit/Article/Cells/VimeoComponentCell.swift, PocketKit/Sources/PocketKit/Article/Presenters/ArticleComponentPresenter.swift, PocketKit/Sources/PocketKit/Article/Presenters/UnsupportedComponentPresenter.swift, PocketKit/Sources/PocketKit/Article/Presenters/VimeoComponentPresenter.swift, PocketKit/Sources/PocketKit/Article/Presenters/YouTubeVideoComponentPresenter.swift, PocketKit/Sources/PocketKit/OEmbedService.swift, PocketKit/Tests/PocketKitTests/Fixtures/oembed.json, PocketKit/Tests/PocketKitTests/OEmbedServiceTests.swift, PocketKit/Tests/PocketKitTests/Support/Fixture.swift
~I'm still waiting on some info from backend team to make sure that we can count on `vid` being consistently populated.~
95% of Vimeo videos have a `vid`. I talked with Laurie and she is fine with that margin
=> Support Vimeo components in MArticle reader

Pocket.xcodeproj/project.pbxproj, PocketKit/Sources/PocketKit/Home/HomeCollectionViewSectionProvider.swift, PocketKit/Sources/PocketKit/Home/HomeViewController.swift, PocketKit/Sources/PocketKit/Home/TopicChipCell.swift, PocketKit/Sources/PocketKit/Home/TopicChipPresenter.swift, PocketKit/Sources/PocketKit/MyList/MyListItemCell.swift, PocketKit/Sources/PocketKit/MyList/MyListViewController.swift, PocketKit/Sources/PocketKit/MyList/MyListViewModel.swift, PocketKit/Sources/Sync/Requests.swift, PocketKit/Sources/Sync/Source.swift, PocketKit/Sources/Sync/Space.swift, Tests iOS/MyList/MyListFiltersTests.swift, Tests iOS/MyList/MyListTests.swift, Tests iOS/Support/Elements/UserListElement.swift
https://getpocket.atlassian.net/browse/IN-455
=> Support filtering My List by favorited items

PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift, PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListItemPresenter.swift, PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewController.swift, PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewModel.swift, PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift, PocketKit/Sources/PocketKit/NetworkPathMonitor.swift, PocketKit/Sources/Sync/Archive/ArchiveService.swift, PocketKit/Sources/Sync/ArchivedItem.swift, PocketKit/Sources/Sync/PocketSource.swift, PocketKit/Sources/Sync/Source.swift, PocketKit/Tests/PocketKitTests/ArchivedItemsViewModelTests.swift, PocketKit/Tests/PocketKitTests/Support/ArchivedItem+factories.swift, PocketKit/Tests/PocketKitTests/Support/MockNetworkPathMonitor.swift, PocketKit/Tests/PocketKitTests/Support/MockSource.swift, PocketKit/Tests/PocketKitTests/Support/UIAlertAction+invoke.swift, PocketKit/Tests/SyncTests/PocketArchiveServiceTests.swift, PocketKit/Tests/SyncTests/PocketSourceTests.swift, PocketKit/Tests/SyncTests/Support/MockArchiveService.swift, Tests iOS/DeleteAnItemTests.swift, Tests iOS/FavoriteAnItemTests.swift
https://getpocket.atlassian.net/browse/IN-460
=> Add support for deleting, favoriting, and unfavoriting archived items

PocketKit/Sources/Sync/Operations/FetchArchivePageOperation.swift, PocketKit/Sources/Sync/Operations/FetchList.swift, PocketKit/Sources/Sync/Operations/SaveItemOperation.swift, PocketKit/Sources/Sync/PocketSource.swift, PocketKit/Sources/Sync/SavedRecommendationsService.swift, PocketKit/Tests/SyncTests/PocketSourceTests.swift, PocketKit/Tests/SyncTests/SavedRecommendationsServiceTests.swift, PocketKit/Tests/SyncTests/Support/Space+factories.swift
Just a few fixup items that I noticed needed done while adding queue persistence. Separated here into their own PR to reduce noise
=> Sync fixups

PocketKit/Sources/PocketKit/Authorization/AuthorizationClient.swift, PocketKit/Sources/PocketKit/LoggedOut/LoggedOutViewController.swift, PocketKit/Sources/PocketKit/LoggedOut/PocketLoggedOutViewModel.swift, PocketKit/Tests/PocketKitTests/AuthorizationClientTests.swift, PocketKit/Tests/PocketKitTests/PocketLoggedOutViewModelTests.swift
Discussing this pull request live.
=> Add support for signing up via FxA

PocketKit/Sources/Sync/Operations/FetchArchivePageOperation.swift, PocketKit/Sources/Sync/Operations/FetchList.swift, PocketKit/Sources/Sync/Operations/RetriableOperation.swift, PocketKit/Sources/Sync/Operations/SaveItemOperation.swift, PocketKit/Sources/Sync/Operations/SavedItemMutationOperation.swift, PocketKit/Sources/Sync/Operations/SyncOperationFactory.swift, PocketKit/Sources/Sync/PocketSource.swift, PocketKit/Tests/SyncTests/Operations/FetchArchivePageOperationTests.swift, PocketKit/Tests/SyncTests/Operations/FetchListTests.swift, PocketKit/Tests/SyncTests/Operations/ItemMutationOperationTests.swift, PocketKit/Tests/SyncTests/Operations/RetriableOperationTests.swift, PocketKit/Tests/SyncTests/Operations/SaveItemOperationTests.swift, PocketKit/Tests/SyncTests/PocketSourceTests+networkMonitoring.swift, PocketKit/Tests/SyncTests/PocketSourceTests+restoringOperations.swift, PocketKit/Tests/SyncTests/PocketSourceTests.swift, PocketKit/Tests/SyncTests/Support/MockApolloClient+stubs.swift, PocketKit/Tests/SyncTests/Support/MockOperationFactory.swift, PocketKit/Tests/SyncTests/Support/ResponseCodeError+factories.swift, PocketKit/Tests/SyncTests/Support/Space+factories.swift, PocketKit/Tests/SyncTests/Support/TestSyncOperation.swift
https://getpocket.atlassian.net/browse/IN-392
=> Retry user actions on network failure

PocketKit/Sources/PocketKit/imageCacheURL.swift
According to @JohnOberhauser, these are the filters that the android app is currently using.
https://getpocket.atlassian.net/browse/IN-564
=> IN-564 Include thumbor filters in image cache requests

PocketKit/Sources/PocketKit/Home/HomeCollectionViewSectionProvider.swift, PocketKit/Sources/PocketKit/Home/HomeViewController.swift, PocketKit/Sources/PocketKit/Home/RecommendationPresenter.swift, PocketKit/Sources/PocketKit/Home/SlateHeaderPresenter.swift, PocketKit/Sources/PocketKit/Home/TopicChipCell.swift, PocketKit/Sources/PocketKit/Home/TopicChipPresenter.swift, PocketKit/Sources/PocketKit/LoggedOut/LoggedOutViewController.swift, PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift, PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListItemPresenter.swift, PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewController.swift, PocketKit/Sources/PocketKit/MyList/MyListTitleView.swift, PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift, PocketKit/Sources/PocketKit/Navigation/NavigationSidebarViewController.swift, PocketKit/Sources/SaveToPocketKit/Style+Extensions.swift, PocketKit/Sources/Textile/Style/Style+Definitions.swift, PocketKit/Tests/PocketKitTests/ItemsListItemPresenterTests.swift
- My/List Archive switcher styling
- Filter button styling
=> Fix switcher and filter button styling issues in MyList page

bitrise.yml
* Move bitrise.yml file to github so iterations are reviewable and shareable.
* Moved `APP_ID` to an environment variable. The rest all look safe.
=> build(bitrise): adding in ci file

.github/CODEOWNERS
* Establishing iOS as codeowners. This will let the team auto-assign themselves to code review, and establish branch protections when others are in the codebase.
* No functionality changes, no code changes.
=> chore(codeowners): establishing ios as codeowners

bitrise.yml
* It was brought up that the team wanted to get QA Builds in slack for each pr. This accomplishes this https://pocket.slack.com/archives/C041UJ8UZFC/p1662766286264229
=> feat(qa): slacking qa builds

Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, PocketKit/Package.swift, PocketKit/Sources/PocketKit/Home/EndOfFeedAnimationView.swift, PocketKit/Sources/PocketKit/Main/MainCoordinator.swift
* Update apollo ios to 0.53.0
* Update Kingfisher from a custom branch to 7.3.2
* Update Sentry to 7.25.0
* Update lottie to 3.4.3  
* I also enabled CoreAnimation rendering which is in the latest release
* Update Snowplow to 3.2.0
* Note: I could not update us to 4.0.0 due to an exception crash on launch. Instead of debugging going with 3.2.0 
* General regression test
=> chore(dependencies): updating dependenices to some of the latest versions

PocketKit/Sources/Analytics/Tracker/PocketSnowplowTracker.swift
* Enable application & platform contexts in snowplow to get device-type information
* https://pocket.slack.com/archives/C0GCG2VNZ/p1663789281310259
* Analytics events still firing
=> feat(snowplow): adding in snowplow data

bitrise.yml
Per request from @irios and @nzeltzer
=> Use standard machines on bitrise

PocketKit/Sources/Sync/Operations/ArchiveService.swift, Tests iOS/MyList/ArchiveFiltersTests.swift
* Added `_untagged_` to filter no tags in archive
* [IN-874](https://getpocket.atlassian.net/jira/software/projects/IN/boards/80?selectedIssue=IN-874)
* handle untagged from graphql
* go to archives
* sort by tag
* select untagged
=> IN 874 - updating untagged filter

Tests iOS/BannerViewTests.swift
* fixed a test to hard-code swipe gesture
* [IN-906](https://getpocket.atlassian.net/browse/IN-906)
* removed `.swipeDown()` and implemented a manual `swipe`
* run `test_dismissingBanner_withClipboardURL_doesNotShowBanner` on all phone sizes
=> refactor(failing test): fixing test not working on some device screen [IN-906]

bitrise.yml
* XCode 14.1.x is now RC and releases 10/24 time to bump our version
* https://getpocket.atlassian.net/browse/IN-909
=> build(xcode): bumping to xcode 14.1.x [IN-909]

AllTests.xctestplan, Pocket.xcodeproj/project.pbxproj, Pocket.xcodeproj/xcshareddata/xcschemes/Pocket (iOS).xcscheme, PocketKit/Sources/Sync/PocketSaveService.swift, PocketKit/Tests/SyncTests/PocketSaveServiceTests.swift, Tests iOS/ArchiveAnItemTests.swift, Tests iOS/BannerViewTests.swift, Tests iOS/EditTagsTests.swift, Tests iOS/FavoriteAnItemTests.swift, Tests iOS/HomeTests.swift, Tests iOS/MyList/MyListTests.swift, Tests iOS/ReportARecommendationTests.swift, Tests iOS/Support/Elements/MyListElement.swift, Tests iOS/Support/Elements/PocketUIElement.swift, Tests iOS/Support/Elements/XCUIElement+wait.swift, Tests iOS/Support/XCTestCase+extensions.swift
This will be the default test plan for use locally. CI runs individual test plans.
=> Add "AllTests" test plan and make it the default

PocketKit/Sources/Analytics/Context/UIContext.swift, PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift, PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift, PocketKit/Sources/PocketKit/Tags/TagsFilterView.swift, PocketKit/Sources/PocketKit/Tags/TagsFilterViewModel.swift, PocketKit/Tests/PocketKitTests/TagsFilterViewModelTests.swift
* Added Analytics for Tag filtering
* [IN-907](https://getpocket.atlassian.net/jira/software/projects/IN/boards/80?selectedIssue=IN-907)
* added analytics for filter tags
=> feat(tags): Analytics for Tags [IN-907]

PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift, PocketKit/Sources/PocketKit/MyList/EmptyStates/EmptyStateView.swift, PocketKit/Sources/PocketKit/MyList/EmptyStates/TagsEmptyStateViewModel.swift, PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift, PocketKit/Tests/PocketKitTests/ArchivedItemsListViewModelTests.swift, PocketKit/Tests/PocketKitTests/SavedItemsListViewModelTests.swift, Tests iOS/MyList/EmptyStateTests.swift, Tests iOS/Support/Elements/SavesElement.swift
* Added empty state for tag
* [IN-597](https://getpocket.atlassian.net/jira/software/projects/IN/boards/80?selectedIssue=IN-597)
* added empty state for tag
* create a tag with no saved articles
* click filter on the tag
<details>
<summary>empty state</summary>
</details>
=> feat(tags): added tags empty view [IN-597]

PocketKit/Package.swift
=> Revert "chore(deps): update dependency apollographql/apollo-ios to from: "1.0.3""

Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, PocketKit/Package.resolved, PocketKit/Package.swift, PocketKit/Sources/PocketGraph/Schema/InputObjects/PaginationInput.graphql.swift, PocketKit/Sources/PocketGraph/Schema/InputObjects/SavedItemTagsInput.graphql.swift, PocketKit/Sources/PocketGraph/Schema/InputObjects/SavedItemUpsertInput.graphql.swift, PocketKit/Sources/PocketGraph/Schema/InputObjects/SavedItemsFilter.graphql.swift, PocketKit/Sources/PocketGraph/Schema/InputObjects/SavedItemsSort.graphql.swift, PocketKit/Sources/PocketGraph/Schema/InputObjects/TagUpdateInput.graphql.swift
=> chore(deps): Apollo Upgrade

PocketKit/Sources/PocketKit/AppBadgeTracker.swift, PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift, PocketKit/Sources/PocketKit/NotificationCenter+EventNames.swift, PocketKit/Sources/PocketKit/PocketSceneDelegate.swift, PocketKit/Sources/PocketKit/Services.swift, PocketKit/Sources/PocketKit/Settings/AccountViewController.swift, PocketKit/Sources/PocketKit/Settings/AccountViewModel.swift, PocketKit/Sources/PocketKit/Settings/Components/SettingsRowToggle.swift, PocketKit/Sources/PocketKit/Settings/SettingsView.swift, PocketKit/Tests/PocketKitTests/AppBadgeTrackerTests.swift, PocketKit/Tests/PocketKitTests/Notifications/PushNotificationServiceTests.swift, PocketKit/Tests/PocketKitTests/SavedItemsListViewModelTests.swift
* Add app badge for number of saved articles
* [IN-981](https://getpocket.atlassian.net/jira/software/projects/IN/boards/80?selectedIssue=IN-981)
* Added app badges
* Go to settings
* turn on app badge
* go to home of iphone and check to see if app badges are showing
* turn off app badges in settings
=> feat(appbadge): App Badge

PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift, PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift
Fix Analytics for Tag Badge
IN-1082
Move the tag badge call into `UIAction` handler
1. Navigate to Saves 
2. Click on Item and Favorite it and Share it 
3. Make sure tag badge call is not triggered
=> fix(analytics): tag badge

PocketKit/apollo-ios-cli, bitrise.yml
Flaky tests are getting worse. Until we have a solve, lets retry on failure the default amount of times bitrise is setup to (3).
=> fix(tests): retrying tests on failures

.gitignore, Package.resolved, Pocket.xcodeproj/project.pbxproj, Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, PocketKit/Package.resolved, PocketKit/Package.swift, PocketKit/Sources/PocketGraph/Operations/Mutations/ArchiveItemMutation.graphql.swift, PocketKit/Sources/PocketGraph/Operations/Mutations/DeleteItemMutation.graphql.swift, PocketKit/Sources/PocketGraph/Operations/Mutations/DeleteTagMutation.graphql.swift, PocketKit/Sources/PocketGraph/Operations/Mutations/FavoriteItemMutation.graphql.swift, PocketKit/Sources/PocketGraph/Operations/Mutations/ReplaceSavedItemTagsMutation.graphql.swift, PocketKit/Sources/PocketGraph/Operations/Mutations/SaveItemMutation.graphql.swift, PocketKit/Sources/PocketGraph/Operations/Mutations/TagUpdateMutation.graphql.swift, PocketKit/Sources/PocketGraph/Operations/Mutations/UnfavoriteItemMutation.graphql.swift, PocketKit/Sources/PocketGraph/Operations/Mutations/UpdateSavedItemRemoveTagsMutation.graphql.swift, PocketKit/Sources/PocketGraph/Operations/Queries/FetchSavesQuery.graphql.swift, PocketKit/Sources/PocketGraph/Operations/Queries/GetSlateLineupQuery.graphql.swift, PocketKit/Sources/PocketGraph/Operations/Queries/GetSlateQuery.graphql.swift, PocketKit/Sources/PocketGraph/Operations/Queries/ItemByIDQuery.graphql.swift, PocketKit/Sources/PocketGraph/Operations/Queries/SavedItemByIDQuery.graphql.swift, PocketKit/Sources/PocketGraph/Operations/Queries/SavedItemSummariesQuery.graphql.swift, PocketKit/Sources/PocketGraph/Operations/Queries/TagsQuery.graphql.swift, README.md, bitrise.yml
Updates:
* Apollo 1.0.3 -> 1.0.5
* Kingfisher 7.3.2 -> 7.4.1
* Sentry 7.25.0 -> 7.31.2
* Snowplow 3.2.0 -> 4.0.1
* Lottie 3.4.3 -> 3.5.0
* Braze 5.6.2 -> 5.6.3
=> chore(updates): updating all packages to latest

Tests iOS/MyList/SavesTests.swift
Fix attempts for flakey UI tests
https://getpocket.atlassian.net/browse/IN-950
Skeleton view test failure is the first attempt
If Bitrise stops failing the tests, we will know the fixes are working :)
=> ci(tests): flakey test fixes

Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift, PocketKit/Sources/PocketKit/Navigation/NavigationSidebarViewController.swift, PocketKit/Sources/Sync/PocketSource.swift, PocketKit/Sources/Sync/Requests.swift, PocketKit/Sources/Sync/Source.swift, PocketKit/Sources/Sync/Space.swift, PocketKit/Tests/PocketKitTests/SearchViewModelTests.swift, PocketKit/Tests/PocketKitTests/Support/MockSource.swift, PocketKit/Tests/SyncTests/PocketSourceTests.swift
* Added search from core data
* [IN-963](https://getpocket.atlassian.net/jira/software/projects/IN/boards/80?selectedIssue=IN-963)
* [IN-889](https://getpocket.atlassian.net/jira/software/projects/IN/boards/80?selectedIssue=IN-889)
* added two calls for core data search
* Go to search. run a search and check to see if the number of elements show as expected
=> feat(search): Local search [IN-963][IN-889]

PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift
* changed return key type
* [IN-969](https://getpocket.atlassian.net/browse/IN-969)
* changed return type
* Go to search
* if nothing is entered, search should be not allowed
* if text is entered, search should be allowed
=> feat(search): search return type

PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift, PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift, PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift, Tests iOS/MyList/SearchTests.swift
* search with recent search
* [IN-960](https://getpocket.atlassian.net/browse/IN-960)
* modified keyboard and navigation
* search for two different items
* click the either one again
* search should update, keyboard should hide, and the list should update with most recent search order
N/A
=> feat(search): search with recent search

Package.resolved, Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, PocketKit/Package.resolved
Update Package.resolved files to match the exact versions
IN-1126
Removed the Package.resolved files and run the command line to resolve packages `swift package resolve`
Ref: https://blog.eidinger.info/swift-package-manager-understand-resolve-reset-and-update
=> project(spm): update resolved files

Pocket.xcodeproj/project.pbxproj, Tests iOS/AddTagsItemTests.swift, Tests iOS/ReaderTests.swift, Tests iOS/Support/Elements/ReaderElement.swift, UITests-2.xctestplan, UITests.xctestplan
Creates a new set of Reader tests, fixes a small tags test.
Merging:
https://github.com/Pocket/pocket-ios/pull/334
https://github.com/Pocket/pocket-ios/pull/355
Implementation Details
See PR's above.
=> ci(tests): combining 2 PRs new reader tests

PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift, PocketKit/Tests/PocketKitTests/Search/SearchViewModelTests.swift
Resubmit search when device comes online
IN-980
Observe network changes in `SearchViewModel` and then retrigger the search call only if the last network status was offline, search term is not empty and the current network status is online.
AND the selected scope is “Archive” 
AND the device is offline
THEN the device gains an internet connect
SUBMIT the search query
Note: This should also apply to All items but was not specified in the ticket. Will confirm on slack.
=> feat(search): resubmit search when device comes online

PocketKit/Sources/PocketKit/Resources/de-DE.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/it-IT.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ja-JP.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ko-KR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/nl-NL.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pl-PL.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-BR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-PT.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ru-RU.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-CN.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-TW.lproj/Localizable.strings
=> chore(smartling): translations for commit 8a15e07df1049d90bd909aa5aed0da4c8f10e933 from develop

PocketKit/Sources/PocketKit/Report/ReportRecommendationView.swift
Adding in missed localization for report.
=> fix(localization): report localization

PocketKit/Sources/Sync/ApolloClientProtocol+Extensions.swift, PocketKit/Sources/Sync/Log.swift, PocketKit/Sources/Sync/PocketSource.swift
I got bit recently by a silently failing network call that took me a while to figure out. 
This explicitly logs all network calls and graphql possible errors.
=> fix(log): adding in network logging

PocketKit/Sources/PocketKit/Resources/en.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Settings/SettingsView.swift, PocketKit/Sources/PocketKit/Strings.swift
* Added build and app versions
* grabbed bundle version and short version to get app and build numbers
* go to settings
* app and build numbers should be present
* end credit should be present
=> feat(settings): version and credit

Tests iOS/HomeTests.swift, Tests iOS/ReportARecommendationTests.swift
PR to fix consistent UI Tests Suite 2 tests
N / A
Modify the tests due to changes in the mock data
Run the tests for this suite and check that it passes
=> ci(tests): fix UI Tests Suite 2 tests

PocketKit/Sources/PocketKit/Resources/en.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Settings/AccountViewModel.swift, PocketKit/Sources/PocketKit/Settings/SettingsView.swift, PocketKit/Sources/PocketKit/Strings.swift
*  Adding a link to our open source notices
* IN-863
=> feat(openSource): adding open source notice page

PocketKit/Sources/Analytics/Entities/RecommendationEntity.swift, PocketKit/Sources/Analytics/Events/ContentOpen.swift, PocketKit/Sources/Analytics/Events/Impression.swift, PocketKit/Sources/Analytics/Tracker/PocketTracker.swift
Working on integrating Snowplow Micro, and I found some errors in the new analytics. This corrects those.
Commented out persistent contexts until @cyndichin 's pr which will fix them
=> fix(analytics): few analytics tests that snowplow micro caught

PocketKit/Sources/Sync/PersistentContainer.swift
Forgot to reset the last refresh date in https://github.com/Pocket/pocket-ios/pull/414
=> fix(reset): reseting refresh date

PocketKit/Sources/PocketKit/Resources/de-DE.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/it-IT.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ja-JP.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ko-KR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/nl-NL.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pl-PL.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-BR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-PT.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ru-RU.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-CN.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-TW.lproj/Localizable.strings
=> chore(smartling): translations are completed for commit 43874fe630416f41c83bd15ca1444c4cbb50818c from develop

PocketKit/Sources/PocketKit/Resources/en.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Settings/SettingsView.swift, PocketKit/Sources/PocketKit/Strings.swift, Tests iOS/SignOutTests.swift, Tests iOS/Support/Elements/AccountViewElement.swift
Updating copy to match https://getpocket.atlassian.net/browse/IN-1165 and https://getpocket.atlassian.net/browse/IN-1172
The actual popup and reset coredata work was already done.
* IN-1165
* IN-1172
=> fix(logout): updating log out copy

PocketKit/Sources/Analytics/Tracker/PocketSnowplowTracker.swift, Tests iOS/Support/LaunchEnvironment.swift
Bringing us inline with the Web and Android team snowplow collector paths that use a custom path on our main domain.
=> fix(snowplow): updating to the getpocket.com endpoint

PocketKit/Sources/PocketKit/Resources/de-DE.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/it-IT.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ja-JP.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ko-KR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/nl-NL.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pl-PL.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-BR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-PT.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ru-RU.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-CN.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-TW.lproj/Localizable.strings
=> chore:(smartling) translations are completed for commit e0be9b2a24786768e7b717c83f6e503341c2f8bd from develop

PocketKit/Sources/PocketKit/Article/ArticleMetadataPresenter.swift, PocketKit/Sources/PocketKit/Article/Presenters/CodeBlockPresenter.swift, PocketKit/Sources/PocketKit/Article/Presenters/ImageComponentPresenter.swift, PocketKit/Sources/PocketKit/Article/Presenters/ListComponentPresenter.swift, PocketKit/Sources/PocketKit/Style+ReaderSettings.swift, PocketKit/Sources/Textile/TextileStyler.swift, Tests iOS/ReaderTests.swift, Tests iOS/Support/Elements/ReaderElement.swift
Update reader mode to follow the display settings the user selected.
Given I am a user in reader mode, when i increase or decrease the font size all text in the article view should increase or decrease.
* IN-939
=> fix(reader): ensuring reader view follows modifiers

PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListItemPresenter.swift, PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift, PocketKit/Sources/PocketKit/Resources/en.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Strings.swift, PocketKit/Sources/PocketKit/Tags/TagsFilterView.swift
I noticed a few strings were missing from localization. So adding them in.
=> fix(localization): adding in some missed strings

PocketKit/Sources/PocketKit/Resources/en.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Settings/SettingsView.swift, PocketKit/Sources/PocketKit/Strings.swift, README.md
Update text for Settings screen and help docs.
* IN-1164
Mainly updated localization text and readme.
=> fix(text): updating help text to match designs

PocketKit/Sources/PocketKit/Resources/de-DE.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/it-IT.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ja-JP.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ko-KR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/nl-NL.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pl-PL.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-BR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-PT.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ru-RU.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-CN.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-TW.lproj/Localizable.strings
=> chore(smartling): translations are completed for commit b486452c59832e5bb30bf3b42ef9a71d30172e46 from develop

PocketKit/Sources/PocketKit/Premium/View/PremiumUpgradeView.swift
=> fix(premium): disable premium purchases for beta testers

PocketKit/Sources/PocketKit/Premium/ViewModel/PremiumUpgradeViewModel.swift, PocketKit/Tests/PocketKitTests/Search/SearchViewModelTests.swift
=> Reinstate @Mainactor for PRemiumUpgradeViewModel

PocketKit/Sources/PocketKit/Resources/de-DE.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ko-KR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-BR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-PT.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-CN.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-TW.lproj/Localizable.strings
=> chore(smartling): translations are completed for commit 224a5e40a33d62f2cceb190d79ea3195009b8462 from develop

PocketKit/Sources/Sync/PersistentContainer.swift, Tests iOS/Support/LaunchArguments.swift
Removes the temporary core data deletion code when we made pieces in core data not null.
* IN-1173
=> fix(coredata): removing temporary core data code

PocketKit/Sources/PocketKit/Resources/de-DE.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/it-IT.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ja-JP.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ko-KR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/nl-NL.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pl-PL.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-BR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-PT.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ru-RU.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-CN.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-TW.lproj/Localizable.strings
=> Smartling translations are completed for commit 3f5c00d151088cdfae058628f921e30e31a86969 from develop

PocketKit/Sources/PocketKit/Resources/de-DE.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/it-IT.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ja-JP.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ko-KR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/nl-NL.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pl-PL.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-BR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-PT.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ru-RU.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-CN.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-TW.lproj/Localizable.strings
=> Smartling translations are completed for commit 4ad5c0dafb99c4d6fd51c2e96d9b16423e6b3587 from develop

UITests-2.xctestplan, UITests-3.xctestplan, UITests.xctestplan
=> Rebalance UI test suites duration

PocketKit/Sources/PocketKit/Premium/View/PremiumUpgradeView.swift
=> Prevent UI tests from failing when Premium Upgrades are disabled

PocketKit/Sources/PocketKit/Resources/de-DE.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/it-IT.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ja-JP.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/nl-NL.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pl-PL.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-BR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-PT.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-CN.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-TW.lproj/Localizable.strings
=> Smartling translations are completed for commit df8936ce92f6dfb6c377162cf881a8a407e8188b from develop

bitrise.yml
=> fix(build): lower machine size

PocketKit/Sources/PocketKit/Home/HomeViewModel.swift, PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItemsListViewModel.swift, PocketKit/Sources/PocketKit/Services.swift
Switch home and saves models to recieve events on a thread and only use the main thread when they have what they need.
=> fix(threads): updating how our main model recieve events

Pocket.xcodeproj/project.pbxproj, Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, PocketKit/Package.resolved, PocketKit/Package.swift, PocketKit/Sources/PocketGraph/Operations/Mutations/ReplaceSavedItemTagsMutation.graphql.swift, PocketKit/Sources/PocketGraph/Operations/Mutations/UpdateSavedItemRemoveTagsMutation.graphql.swift, PocketKit/Sources/PocketGraph/Schema/Objects/User.graphql.swift
Updated:
* Braze 5.11.0 -> 5.11.2
* YouTubePlayerKit 1.3.1 -> 1.4.0
* Sentry 8.2.0 -> 8.3.1
* Fetched and generated latest schema
=> chore(deps): general dependency upgrade

Pocket.xcodeproj/xcshareddata/xcschemes/Pocket (iOS) Alpha Neue.xcscheme, Pocket.xcodeproj/xcshareddata/xcschemes/Pocket (iOS).xcscheme
Fix XCode test schemes for local development
=> chore(tests): updating xcode test scheme

PocketKit/Sources/Sync/Log.swift
Sentry made its way into develop commented out. Re-enabling it.
=> fix(sentry): install sentry on non-debug builds

Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> Update Swift-nio dependency version

PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift, PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift, PocketKit/Sources/PocketKit/Resources/en.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Strings.swift
* Adding swipe functionality to searched items
* [IN-898](https://getpocket.atlassian.net/browse/IN-898)
* added swipe functionality to searched items
* search for item in Saves
* swiping should show action to Archive
* clicking it will archive
* leave search
* check archive
* search for item in Archives
* swiping should show action to Move to Saves
* clicking it will move item to saves
* leave search
* check saves
[IN-898]: https://getpocket.atlassian.net/browse/IN-898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(search-swipe): Adding Search Swipe

PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
* update header for saves
* [IN-1209](https://getpocket.atlassian.net/browse/IN-1209)
* update header for saves in home
* go to saves
* check saves header
[IN-1209]: https://getpocket.atlassian.net/browse/IN-1209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(name): update header name

PocketKit/Sources/PocketKit/Settings/PremiumStatus/ViewModel/PremiumStatusViewModel.swift
=> Premium - Add iTunes identifier to subscription providers

Config/secrets.xcconfig.example
Includes necessary secret example to run the app.
App should build and run successfully with GROUP_ID added
=> Add groupid example to secrets file

README.md, bitrise.yml
* Write up how to release to Testflight.
* Ensure Bitrise timesout if it gets stuck (it did)
=> docs(releasing): how to release

PocketKit/Sources/PocketKit/Resources/de-DE.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/it-IT.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ja-JP.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ko-KR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/nl-NL.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pl-PL.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-BR.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/pt-PT.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/ru-RU.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-CN.lproj/Localizable.strings, PocketKit/Sources/PocketKit/Resources/zh-TW.lproj/Localizable.strings
=> Smartling translations are completed for commit 14a74786bd0ee758f252ab1e35848d37f90f99e3 from develop

PocketKit/Sources/PocketKit/Article/ReadableViewModel/ReadableViewModel.swift, PocketKit/Sources/PocketKit/Article/ReadableViewModel/RecommendationViewModel.swift, PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift, PocketKit/Sources/PocketKit/Home/HomeViewController.swift, PocketKit/Sources/PocketKit/Home/HomeViewModel.swift, PocketKit/Sources/PocketKit/Home/SlateDetailViewModel.swift, PocketKit/Sources/PocketKit/Main/MainViewModel.swift, PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItemsListViewModel.swift, PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift, PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift, PocketKit/Sources/PocketKit/PocketPremiumURL.swift, PocketKit/Tests/PocketKitTests/HomeViewModelTests.swift, PocketKit/Tests/PocketKitTests/RecommendationViewModelTests.swift, PocketKit/Tests/PocketKitTests/SavedItemViewModelTests.swift, PocketKit/Tests/PocketKitTests/SavedItemsListViewModelTests.swift, PocketKit/Tests/PocketKitTests/SlateDetailViewModelTests.swift
Loads premium getpocket.com pages by adding a query parameter to the recommendation / item's url. As of this pull request. the query parameter supports syndicated articles, but not collections (out of our code's control).
IN-574
- Introduced a pocketPremiumURL` helper function that will generate the premium URL for any URL whose host is `getpocket.com`, using the appropriate implementation functions for iOS 15 vs 16, to add the correct query parameter to the URL (in this case, `premium_user`.
=> feat(premium): load premium getpocket.com pages for premium users

PocketKit/Sources/PocketKit/LinkedExternalURLs.swift
Setup license url for iOS next
* Requires https://github.com/mozilla/bedrock/issues/12910 to be merged
* Requires https://github.com/Pocket/dotcom-gateway/pull/105 dotcom gateway pr to be merged
=> fix(url): update license url

PocketKit/Sources/Sync/Space/Space.swift
Fixes a bug in Space where we where not using the passed in context
=> fix(coredata): fixing a bug in coredata

PocketKit/Package.resolved
=> chore(deps): update resolved

PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItemsListViewModel.swift
Don't show placeholders if we have data!
* Background and re-open the app while its loading data, you should always see your items after they first come in.
=> fix(loading): ensure that a user sees items and not blank cells when they exist

PocketKit/Sources/Localization/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/it-IT.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pl-PL.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pt-PT.lproj/Localizable.strings
=> Smartling translations are completed for commit 1cd5a10bc33588b90ff81d3d956e63bb8ba2655d from develop

PocketKit/Sources/Sync/User/UserService.swift
Users can not have names or usernames, so lets not log errors in that scenario
=> fix(user): stop logging username error

bitrise.yml
Shutdown the iOS 15 testing pipeline for now.
=> chore(builds): removing legacy pipeline

Pocket.xcodeproj/project.pbxproj, PocketKit/Package.swift, PocketKit/Sources/PocketKit/MyList/ItemsList/SwiftUI/ListItem.swift, PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift, PocketKit/Sources/PocketKit/PocketURLs.swift, PocketKit/Sources/PocketKit/Settings/AccountManagementView.swift, PocketKit/Sources/PocketKit/Settings/SettingsView.swift, PocketKit/Sources/Textile/Views/Banner/PasteBoardView.swift, Tests iOS/Support/Elements/AddTagsViewElement.swift, Tests iOS/Support/Elements/PocketAppElement.swift, Tests iOS/Support/Elements/SearchViewElement.swift
* This PR sets the minimum deployment target to iOS 16
* Update project and remove all `if #available(iOS 16.0, *)` conditions
* make sure this branch builds on iOS 16/iPadOS 16 devices
=> Update minimum deployment target to iOS 16

Tests iOS/Fixtures/save-item-2.json
Saw a small bug from the tags work in https://github.com/Pocket/pocket-ios/pull/603
=> chore(tests): small fix for bad data in upsertSavedItem

Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> chore(version): swift nio update

PocketKit/Sources/PocketKit/Tags/SelectedTagChipCell.swift, PocketKit/Sources/Textile/Style/Images/UIImagePadding.swift
* added spacing to close tag filter
* [IN-1255](https://getpocket.atlassian.net/browse/IN-1255)
* added method to allow UIImage to have padding (total width and total height) padding
[IN-1255]: https://getpocket.atlassian.net/browse/IN-1255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(filters): tag filter 'x' spacing

Pocket.xcodeproj/project.pbxproj, Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, PocketKit/Package.resolved, PocketKit/Package.swift
* Update apollo to 1.1.2
* Update braze to 5.14.0
* Move sails to a Pocket owned fork
* Update sentry to 8.5.0
=> deps(updates): latest package versions

PocketKit/Sources/Localization/Resources/de-DE.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/it-IT.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ja-JP.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ko-KR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/nl-NL.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pl-PL.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pt-BR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pt-PT.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ru-RU.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/zh-CN.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/zh-TW.lproj/Localizable.strings
=> Smartling translations are completed for commit d22a6df3c60703ba22c998521d0faa84d1546260 from develop

bitrise.yml
* Eventually we will want prs to have a status check on the built product (release build & alpha neue build). This adds a step that should add that callback back to Github.
=> chore(bitrise): updating bitrise to deploy a build so we can get a github status result

Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, PocketKit/Sources/Analytics/AppEvents/Premium.swift, PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift, PocketKit/Sources/PocketKit/PremiumUpgrade/View/PremiumUpgradeView.swift, PocketKit/Sources/Sync/PocketSaveService.swift
* Remove some `print`s here and there
* Also update a package, since we're here
=> Remove unnecessary `print()` statements in the code

Info.plist, PocketKit/Sources/Localization/Resources/en.lproj/Localizable.strings, PocketKit/Sources/Localization/Strings.swift, PocketKit/Sources/PocketKit/Settings/SettingsView.swift, bitrise.yml
To help with builds/debugging adding in a short version of the git sha to the settings page. 
=> chore(settings): adding short gitsha to settings

Info.plist, PocketKit/Sources/Localization/Resources/en.lproj/Localizable.strings, PocketKit/Sources/Localization/Strings.swift, PocketKit/Sources/PocketKit/Settings/SettingsView.swift, bitrise.yml
Reverts Pocket/pocket-ios#654
Isn't pulling in the gitsha, no time to debug right now.
=> Revert "chore(settings): adding short gitsha to settings"

Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> chore(package): swift nio

PocketKit/Sources/PocketKit/Home/HomeCarouselItemCell.swift, PocketKit/Sources/PocketKit/Home/HomeRecommendationCellHeroWideViewModel.swift, PocketKit/Sources/PocketKit/Home/HomeRecommendationCellViewModel.swift, PocketKit/Sources/PocketKit/Home/RecentSavesItemCell.swift, PocketKit/Sources/PocketKit/Home/RecommendationButton.swift, PocketKit/Sources/PocketKit/Home/RecommendationCarouselCell.swift, PocketKit/Sources/PocketKit/Home/RecommendationCell.swift, PocketKit/Sources/PocketKit/Home/RecommendationCellHeroWide.swift, PocketKit/Sources/PocketKit/Home/RecommendationSaveButton.swift, PocketKit/Sources/PocketKit/Home/SectionHeaderView.swift, PocketKit/Sources/PocketKit/Home/TopicChipCell.swift, PocketKit/Sources/PocketKit/Home/TopicChipPresenter.swift, PocketKit/Sources/PocketKit/ItemAction.swift, PocketKit/Sources/PocketKit/Main/RootView.swift, PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListItemCell.swift, PocketKit/Sources/PocketKit/MyList/SavesTitleView.swift, PocketKit/Sources/PocketKit/Tags/SelectedTagChipCell.swift, PocketKit/Sources/Textile/Style/Colors/Colors.xcassets/UI/grey8.colorset/Contents.json, PocketKit/Sources/Textile/Style/Colors/Colors.xcassets/UI/homeCellBackground.colorset/Contents.json, PocketKit/Sources/Textile/Style/Colors/Colors.xcassets/UI/saveButtonText.colorset/Contents.json, PocketKit/Sources/Textile/Style/Colors/Colors.xcassets/UI/teal2.colorset/Contents.json, PocketKit/Sources/Textile/Style/Colors/Colors.xcassets/UI/teal5.colorset/Contents.json, PocketKit/Sources/Textile/Style/Colors/Palettes.swift, PocketKit/Sources/Textile/Style/SavesSelectorButtonStyle.swift
Worked with Tais to adjust all our styles.
https://user-images.githubusercontent.com/1010384/234406867-0babf436-d879-475b-9930-4287e3d0826f.mp4
=> fix(ui): updating ui colors

PocketKit/Sources/Localization/Resources/de-DE.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/it-IT.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ja-JP.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ko-KR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/nl-NL.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pl-PL.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pt-BR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pt-PT.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ru-RU.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/zh-CN.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/zh-TW.lproj/Localizable.strings
Please review updates and merge this pull request
=> Smartling translations are updated for commit 0aba91c2e60eea512dbbc0888573fe15065b206d from develop

PocketKit/Sources/PocketGraphTestMocks/SavedItem+Mock.graphql.swift, Tests iOS/Fixtures/recommendation-detail-4.json, Tests iOS/Fixtures/slates.json, Tests iOS/Fixtures/updated-slates.json, Tests iOS/HomeTests.swift, Tests iOS/MyList/ArchiveTests.swift, Tests iOS/MyList/SearchTests.swift, Tests iOS/PremiumTests.swift, Tests iOS/ReaderTests.swift, Tests iOS/ReportARecommendationTests.swift, Tests iOS/Support/Response+factories.swift, bitrise.yml
PR to address tests that are failing in Suite 1 + 2
N/A
* Update `slates.json` url to be unique
* Utilize `upsertSavedItem` for tests that previously utilized `unarchive.json` and `save-item.json`
Run the two test suites and verify that all tests are passing.
=> chore(fix): fix tests in suite 1 + 2

PocketKit/Sources/PocketKit/PremiumUpgrade/Model/ReceiptService.swift
* This PR adds a layer of safety to the receipt request continuation
* This PR also avoid sending the receipt from a simulator
* Update `ReceiptService`:
- use an array of continuation instead of a single property to prevent overwriting
- prevent sending the receipt from simulator
=> App Store Receipt - prevent continuations to be overwritten so they can safely be resumed and deleted

PocketKit/Sources/SharedPocketKit/Log.swift
=> When capturing an error, log the error instead of the localized description

bitrise.yml
Uncomment code after fixing UI tests
N/A
N/A
N/A
N/A
=> chore(bitrise): remove comment after fixing ui tests

Tests iOS/Fixtures/save-recommendation-1.json, Tests iOS/Fixtures/save-recommendation-2.json, Tests iOS/Fixtures/slates.json, Tests iOS/HomeTests.swift
=> chore(tests): update home test fixtures

PocketKit/Sources/Localization/Resources/de-DE.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/it-IT.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ja-JP.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ko-KR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/nl-NL.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pl-PL.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pt-BR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pt-PT.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ru-RU.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/zh-CN.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/zh-TW.lproj/Localizable.strings
=> chore(smartling): translations are completed for commit 5c70ad977ac7e6c2464c7eddc72c576b788c6188 from develop

PocketKit/Sources/Analytics/AppEvents/Search.swift, PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
* While digging through some search code noticed a duplicate event being fired in legacy version of analytics.
=> fix(analytics): updating search open analytics to have destination

PocketKit/Sources/PocketKit/PremiumUpgrade/Model/PocketSubscriptionStore.swift, PocketKit/Sources/PocketKit/PremiumUpgrade/Model/ReceiptService.swift, PocketKit/Sources/PocketKit/Settings/AccountViewModel.swift
=> Premium purchases: add some logging

PocketKit/Sources/PocketKit/PremiumUpgrade/Model/PocketSubscriptionStore.swift, PocketKit/Sources/PocketKit/PremiumUpgrade/Model/ReceiptService.swift
=> Storekit logs fix

Info.plist
Adds in the processing background mode for IN-1398
=> fix(background): adding in the processing background mode

Package.swift, Pocket.xcodeproj/project.pbxproj, Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, PocketKit/Package.resolved, PocketKit/Package.swift
* Lets update our dependencies before we lock in our RC!
Apollo had some issues, will tackle that in a separate pr
=> chore(deps): upgrading dependencies

PocketKit/Sources/Localization/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ja-JP.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pl-PL.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pt-PT.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/zh-CN.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/zh-TW.lproj/Localizable.strings
=> Smartling translations are completed for commit eff432813518fea78985fa1214d44d476eb1ed37 from develop

PocketKit/Sources/Analytics/AppEvents/ExpandedSlate.swift, PocketKit/Sources/PocketKit/Home/HomeViewModel.swift, PocketKit/Sources/PocketKit/Home/SlateDetailViewController.swift, PocketKit/Sources/PocketKit/Home/SlateDetailViewModel.swift, Tests iOS/HomeTests.swift, Tests iOS/Support/SnowplowMicro.swift
* Demo converting old analytics to new style
* Add in slate analytics for detail views
* Copied with @JohnOberhauser started on Android and then expanded, realistically this one is a copy paste, while changing the identifier
=> feat(analytics): adding in explicit analytics to slate detail

PocketKit/Sources/Localization/Resources/de-DE.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/it-IT.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ja-JP.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ko-KR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/nl-NL.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pl-PL.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pt-BR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pt-PT.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ru-RU.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/zh-CN.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/zh-TW.lproj/Localizable.strings
=> Smartling translations are completed for commit 70b227ab8a956e1eccc992496cb13322daa8370a from develop

PocketKit/Sources/Localization/Resources/de-DE.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/it-IT.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ja-JP.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ko-KR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/nl-NL.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pl-PL.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pt-BR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pt-PT.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ru-RU.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/zh-CN.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/zh-TW.lproj/Localizable.strings
=> Smartling translations are completed for commit 4fa7f4e9778fb2894f2c602d80220b096f7a66bb from develop

Pocket.xcodeproj/project.pbxproj
We lock our point release today! So time to version bump!
=> fix(version): bumping to 8.0.1

PocketKit/Sources/Localization/Resources/de-DE.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/it-IT.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ja-JP.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ko-KR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/nl-NL.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pl-PL.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pt-BR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pt-PT.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ru-RU.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/zh-CN.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/zh-TW.lproj/Localizable.strings
=> Smartling translations are completed for commit 8dc3176ad58de593b8a6e495b1e27d2ed8d987c3 from develop

PocketKit/Sources/PocketKit/Article/Cells/BlockquoteComponentCell.swift, PocketKit/Sources/PocketKit/Article/Cells/CodeBlockComponentCell.swift, PocketKit/Sources/PocketKit/Home/HomeCollectionViewSectionProvider.swift, PocketKit/Sources/PocketKit/Report/ReportRecommendationView.swift, PocketKit/Sources/Textile/Style/PocketButtonStyle.swift, PocketKit/Sources/Textile/Style/SavesSelectorButtonStyle.swift
Update Constants to use `enum` instead of `struct` as they can't be initialized accidentally
N/A
Discussion here: https://pocket.slack.com/archives/C01UH57EJKD/p1684180292599219
=> refactor(ui): update constants from struct to enum

PocketKit/Sources/PocketKit/Settings/AccountViewModel.swift
* Remove manual restore purchase `userCancelled` events from Sentry
=> Premium Purchases - Do not send user cancellations as errors to Sentry

Pocket.xcodeproj/project.pbxproj
Bumps the project version and all of its targets to 8.0.2
=> project: bump version to 8.0.2

PocketKit/Sources/PocketKit/Refresh/FeatureFlagsRefreshCoordinator.swift
Ensure we actually fetch feature flags.
=> fix(refresh): ensure we force the refresh of feature flags.

PocketKit/Sources/Localization/Resources/de-DE.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/es-ES.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/es-LA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-CA.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/fr-FR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/it-IT.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ja-JP.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ko-KR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/nl-NL.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pl-PL.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pt-BR.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/pt-PT.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/ru-RU.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/zh-CN.lproj/Localizable.strings, PocketKit/Sources/Localization/Resources/zh-TW.lproj/Localizable.strings
=> Smartling translations are completed for commit 0a1985db2464476f207e1387f2c33dff4b7a1fc3 from develop

Pocket.xcodeproj/project.pbxproj
Bump version from v8.0.4 to v8.0.5
=> project: bump version to v8.0.5

PocketKit/Sources/PocketKit/Authorization/AuthorizationClient.swift, PocketKit/Sources/PocketKit/Settings/AccountViewModel.swift, Tests iOS/Support/LaunchArguments.swift
https://getpocket.atlassian.net/browse/IN-1346
Add breadcrumb logs.
=> feat(logging) Log breadcrumb when a user signs in or out

PocketKit/Sources/PocketKit/Article/ReadableViewController.swift, PocketKit/Sources/PocketKit/Article/ReadableViewModel/ReadableViewModel.swift, PocketKit/Sources/PocketKit/Article/ReadableViewModel/RecommendationViewModel.swift, PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift, PocketKit/Tests/PocketKitTests/SavedItemViewModelTests.swift
https://getpocket.atlassian.net/browse/IN-650
Add progress recording functions to the ReadableViewModel protocol.
Implement those functions SavedItemViewModel
Add empty implementations to the RecommendationViewModel
Open a Saved item in Reader
Scroll down through the article somewhat
Back out of Reader
Re-open that same article
The article should scroll to show the point where you left off.
=> IN-650 Record user progress when viewing an article in Reader.

Pocket.xcodeproj/project.pbxproj
This reverts commit 523b7c49d6d5aa073b88f8f1327f1388e6fd8712.
=> Revert "project: update release signing identity"

Pocket.xcodeproj/xcshareddata/xcschemes/Pocket (iOS).xcscheme, PocketKit/Sources/Analytics/AppEvents/Home.swift, PocketKit/Sources/Analytics/Entities/CorpusRecommendationEntity.swift, PocketKit/Sources/PocketKit/PocketAppDelegate.swift, Tests iOS/Fixtures/corpusSlates.json, Tests iOS/HomeTests.swift, Tests iOS/Support/LaunchArguments.swift, Tests iOS/Support/RequestMatchers.swift, Tests iOS/Support/Response+factories.swift, Tests iOS/Support/SnowplowMicro.swift
* This PR updates analytics events to use the new `CorpusRecommendationEntity`
* See issue number in branch name
* Add `CorpusRecommendationEntity`
* Update `Home`, use `CorpusRecommendationEntity` in `home.slate.article.impression` and `home.slate.article.open`
* NA
=> Unified Home - Update Analytics

Pocket.xcodeproj/project.pbxproj, PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift, PocketKit/Sources/PocketKit/Collections/CollectionMetadata.swift, PocketKit/Sources/PocketKit/Collections/CollectionViewController.swift, PocketKit/Sources/PocketKit/Collections/CollectionViewModel.swift, PocketKit/Sources/PocketKit/Home/HomeViewModel.swift, PocketKit/Sources/PocketKit/Home/SlateDetailViewModel.swift, PocketKit/Sources/PocketKit/Item/Item+Extensions.swift, PocketKit/Sources/PocketKit/MyList/ItemsList/UIKit/SavedItemsList/SavedItemsListViewModel.swift, PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift, PocketKit/Sources/Sync/Collection/Collection+Extension.swift, PocketKit/Sources/Sync/Collection/CollectionUrlFormatter.swift, PocketKit/Sources/Sync/CoreDataInitializers/Item+CoreDataProperties.swift, PocketKit/Sources/Sync/NetworkPathMonitor.swift, PocketKit/Sources/Sync/PocketModel.xcdatamodeld/PocketModel 3.xcdatamodel/contents, PocketKit/Sources/Sync/RemoteMapping/Collection+remoteMapping.swift, PocketKit/Sources/Sync/RemoteMapping/Item+remoteMapping.swift, PocketKit/Tests/PocketKitTests/Collections/CollectionUrlFormatterTests.swift, PocketKit/Tests/PocketKitTests/Collections/CollectionViewModelTests.swift, PocketKit/Tests/PocketKitTests/Support/MockNetworkPathMonitor.swift, PocketKit/Tests/PocketKitTests/Support/MockSource.swift, PocketKit/Tests/PocketKitTests/Support/Space+factories.swift, PocketKit/Tests/SyncTests/Support/FetchSavesTests.swift, PocketKit/Tests/SyncTests/Support/MockNetworkPathMonitor.swift
* This PR updated the fetch logic in `CollectionViewModel`
* branch name
* Update fetch logic in `CollectionViewModel`, and refactor ui updates accordingly
* Make sure collections are still working and fetching as expected
=> Native Collections - Update fetch logic

Pocket.xcodeproj/project.pbxproj, PocketKit/Sources/PocketKit/Home/HomeCarouselItemCell.swift, PocketKit/Sources/PocketKit/Home/RecommendationCell.swift, PocketKit/Sources/PocketKit/MyList/ItemsList/UIKit/Cells/ItemsListItemCell.swift, Tests iOS/CollectionTests.swift, Tests iOS/Fixtures/collection-home.json, Tests iOS/Fixtures/collection-saves.json, Tests iOS/Fixtures/corpusSlates.json, Tests iOS/Fixtures/feature-flags.json, Tests iOS/Fixtures/initial-list-free-user.json, Tests iOS/Fixtures/initial-list-recent-saves.json, Tests iOS/Fixtures/initial-list.json, Tests iOS/Fixtures/list-for-web-view.json, Tests iOS/Fixtures/list-with-archived-item.json, Tests iOS/Fixtures/saves-loading-page-1.json, Tests iOS/Support/Elements/CollectionElement.swift, Tests iOS/Support/Elements/ItemRowElement.swift, Tests iOS/Support/Elements/PocketAppElement.swift, Tests iOS/Support/Elements/RecommendationCellElement.swift, Tests iOS/Support/RequestMatchers.swift, Tests iOS/Support/Response+factories.swift, UITests-2.xctestplan, UITests-3.xctestplan, UITestsFlaky.xctestplan
Add UI tests for native collections
N / A
Add `CollectionTests` to validate analytics and native collection feature
Added two main fixtures for providing collection data and feature flag data for native collections
- Run through tests and confirm that it passes
=> feat(collections): add UI tests
