Shared/ItemListView.swift

Initialize a remote image loader with the thumbnail URL of an item, and not the item's URL.

fix(ui): correctly load list thumbnails

---

Pocket.xcodeproj/project.pbxproj
Shared/PocketApp.swift
Shared/StaticDataCleaner.swift

Previous builds were using mock data that was being returned from the
server. Now that the server is returning actual users' lists, they are
seeing the cached mock data from before.
For this build, we'll reset core data to clear out the old mock data.
https://getpocket.atlassian.net/browse/IN-79

Reset core data for older beta builds

---

Pocket.xcodeproj/project.pbxproj
Shared/Authorization/AccessTokenStore.swift
Shared/Environment.swift
Shared/Item/ItemDestinationView.swift
Shared/Item/ItemPresenter.swift
Shared/Keys.swift
Shared/Services.swift
Sync/ApolloClient+Extensions.swift
Sync/Item+Extensions.swift
Sync/PocketModel.xcdatamodeld/PocketModel.xcdatamodel/contents
Sync/Source.swift
Sync/Space.swift
SyncTests/Fixtures/list.json
SyncTests/SourceTests.swift
SyncTests/Support/MockApolloClient.swift
Tests iOS/Fixtures/initial-list.json
Tests iOS/Fixtures/updated-list.json
Tests iOS/Support/Elements/PocketApp.swift
Tests iOS/Support/Elements/ReaderToolbar.swift
Tests iOS/Support/Elements/WebReaderScreen.swift
Tests iOS/Tests_iOS.swift

When setting up service objects (such as AuthorizationClient and
Source), do so in Services and then connect the SwiftUI.Environment to
each service as necessary.
Set up Keys struct to encapsulate keys and other shared secrets (naming
could probably be improved).
Also remove `consumerKey` requirement from `AuthTokenProvider` and just
pass it in since it should never change.

Isolate environment initialization to Services struct

---

Sync/Space.swift

Calling `sync` on the main thread results in a crash. This can be resolved by directly saving the context while on the main thread, otherwise dispatching `sync` to the main queue.

fix(sync): safely save on main thread

---

Sync/Item+Extensions.swift

I believe the mock data was returning unix timestamps in milliseconds, rather than in seconds as the backend currently does. Simple change: interpret the timestamp as a unix timestamp in seconds, rather than milliseconds.

fix(sync): interpret graphql timestamps as seconds

---

PocketKit/Sources/PocketKit/Item/ItemPresenter.swift

https://getpocket.atlassian.net/browse/IN-168

fix: show URL as item title when title is missing or empty

---

PocketKit/Sources/Sync/Particle/Decodable/ArticleComponent+Decodable.swift
PocketKit/Sources/Sync/Particle/Decodable/InlineModifer+Decodable.swift
PocketKit/Sources/Sync/Particle/Decodable/InlineStyle+Decodable.swift

These captures are causing a huge performance issue so disabling for
now. We can come up with a way to capture them in a more efficient
manner in the future.

Don't capture messages when encountering unsupported Particle elements

---

PocketKit/Sources/Sync/Source.swift
PocketKit/Tests/SyncTests/Operations/FavoriteItemTests.swift
PocketKit/Tests/SyncTests/Operations/FetchListTests.swift
PocketKit/Tests/SyncTests/Operations/UnfavoriteItemTests.swift
PocketKit/Tests/SyncTests/Support/MockApolloClient+stubs.swift
PocketKit/Tests/SyncTests/Support/Space+factories.swift

- Extract MockApolloClient+stubs
These extension methods make it a bit nicer to set up common stubs
- Extract Space+factories (in SyncTests)
A simple method for seeding an Item in CoreData for use in tests
Make use of these handy little abstractions in tests of operations to
make them a bit slimmer and easier to read.

Cleanup operation tests

---

PocketKit/Sources/PocketKit/Analytics/APIUser.swift
PocketKit/Sources/PocketKit/Item/ItemListView.swift

1. When scrolling a user's list, impression events are fired whenever a row comes on-screen. These impression events should _only_ be sent if there is a `content` context to send along with the event. Adding a guard prevents sending impression events incorrectly.
2. To determine the context of (failing) events, the `client_version` property has been added to `APIUser`, where the property refers to the build number of the app. This context is sent with each event tracked.

Fix sending impression events with no content

---

PocketKit/Sources/PocketKit/Activity/ActivityType+Pocket.swift
PocketKit/Sources/PocketKit/Activity/CopyLinkActivity.swift
PocketKit/Sources/PocketKit/Activity/CopyLinkWithSelectionActivity.swift
PocketKit/Sources/PocketKit/Activity/PocketActivity.swift
PocketKit/Sources/PocketKit/Activity/PocketItemActivity.swift
PocketKit/Sources/PocketKit/Activity/UIActivityViewController+Extensions.swift
PocketKit/Sources/PocketKit/Article/ArticleViewController.swift
PocketKit/Sources/PocketKit/Item/ItemPresenter.swift
PocketKit/Sources/PocketKit/PocketAppDelegate.swift
PocketKit/Sources/PocketKit/PocketSceneCoordinator.swift
PocketKit/Sources/PocketKit/Sync+Textile.swift

1. Fixes a crash when applying (some) modifiers. Range inconsistencies post-unescaping would in some cases cause a crash. This is a temporary resolution that will be more properly rectified during our upcoming work in article view.
2. Adds support for disabling Sentry via launch arg. This code went poof! So, let's bring it back.
3. Adds support for copying an item link, as well as the link and any selected text when viewing an article.
- Currently, the new share support exists within the article view, since the work is "skeleton" work that will have to be refactored once merged with other work in active development.
- The list (to be fixed post-refactor) will currently only copy the item URL when sharing.

Foxfooding Bug Fixes

---

PocketKit/Sources/Analytics/UIContext.swift
PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewController.swift
PocketKit/Sources/PocketKit/Main/CompactMainCoordinator.swift
PocketKit/Sources/PocketKit/Main/MainCoordinator.swift
PocketKit/Tests/SyncTests/Support/Slate+Factories.swift

This pull request builds on the work done in #73 to include the following:

Additional tracking to Home tab

---

PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewController.swift
PocketKit/Sources/PocketKit/Item/ItemViewController.swift
PocketKit/Sources/PocketKit/Main/CompactMainCoordinator.swift
PocketKit/Sources/PocketKit/Main/MainViewModel.swift
PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift

MainViewModel:
- add properties for selectedRecommendation and selectedSlateID
Compact coordinator:
- Observe selectedRecommendation and push recommendation reader when
it becomes populated
- Observe selectedSlateID and push slate detail when it is populated
- Unset selectedSlateID when navigating away from slate detail
- Unset selectedRecommendation when navigating away from reader
Regular coordinator:
- Observe selectedRecommendation and show the recommendation in reader
- Observe selectedSlateID and push slate detail–in primary view–when it is populated
- Unset selectedSlateID when navigating away from slate detail
- Rename `item` to `itemVC` for clarity
ItemViewController:
- Don't bother observing the selected item on the main view model. The
coordinators observe that property and …

Fix navigation sync on iPad

---

PocketKit/Sources/Sync/LastRefresh.swift
PocketKit/Sources/Sync/Source.swift
PocketKit/Tests/SyncTests/Support/MockLastRefresh.swift

This is only necessary when we launch the app with the `clearCoreData`
argument during development.

Clear last refresh timestamp when clearing local storage

---

PocketKit/Sources/PocketKit/Article/ArticleComponentPresenter.swift
PocketKit/Sources/PocketKit/Article/ArticleViewController.swift
PocketKit/Sources/PocketKit/Article/DIviderComponentCell.swift

This pull request sets the height of a divider component cell to `16`, which is some number that I thought looked nice. This height does _not_ account for the inter-item spacing; that will be visible _in addition to_ the height of this cell. The divider itself within the view is 1pt.

Initial marticle support for divider components

---

PocketKit/Sources/PocketKit/Article/ArticleComponentPresenter.swift
PocketKit/Sources/PocketKit/Article/ArticleViewController.swift
PocketKit/Sources/PocketKit/Article/CodeBlockComponentCell.swift
Tests iOS/Fixtures/marticle.json
Tests iOS/Tests_iOS.swift

This pull request adds initial MArticle support for code blocks.
_How_ the code block is presented is … interesting. `UITextView` does _not_ like being told what its content size is for long horizontal text. Even if you do manage to set its width appropriately, it refuses to draw past the bounds of the text view. One might think, "oh, I'll just update the text container size". Well, that doesn't work either.
SO.
There is a non-scrollable `UITextView` that dynamically sizes itself within a scroll view, which is itself sized to the height of the cell. Therefore, the text view's height will always be correct, its width will expand to fit the content, thus causing the parent scroll view to update its content size and allow for horizontal scrolling of long text. Fun times.

Initial MArticle support for code blocks

---

PocketKit/Sources/PocketKit/Home/RecommendationCell.swift
PocketKit/Sources/PocketKit/Home/RecommendationOverflowButton.swift
PocketKit/Sources/PocketKit/Home/RecommendationSaveButton.swift

We increase the tappable area of the button by setting the button's
contentInsets to something more reasonable (8pts on each edge) instead
of using a content inset of `.zero`.
In order to keep things aligned and spaced properly, we pin the edges of
the button to the edge of the cell (as opposed to the cell's layout
margin) and decrease the spacing between the excerpt text and the
button. These changes offset the additional space that is now occupied
by the button itself while maintaining the same visual alignment and
spacing.
https://getpocket.atlassian.net/browse/IN-252

Recommendation cells: Increase tappable area of save button

---

PocketKit/Sources/PocketKit/Article/ArticleComponentPresenter.swift
PocketKit/Sources/PocketKit/Article/ArticleViewController.swift
PocketKit/Sources/PocketKit/Article/UnsupportedComponentCell.swift
PocketKit/Sources/PocketKit/Item/ItemViewController.swift
PocketKit/Sources/PocketKit/Main/CompactMainCoordinator.swift
PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift
Tests iOS/Tests_iOS.swift

This pull request adds support for "rendering" tables by displaying that they are unsupported, with the ability to optionally present the item in web view.

Initial MArticle support for tables as unsupported

---

PocketKit/Sources/PocketKit/Article/ArticleComponentPresenter.swift
PocketKit/Sources/PocketKit/Article/ArticleViewController.swift
PocketKit/Sources/PocketKit/Article/BlockquoteComponentCell.swift
Tests iOS/Tests_iOS.swift

This pull request adds support for block quotes by rendering them as typically found when rendering markdown. This implementation supports "basic" markdown styling within the block quote itself, such as **bold**, _italic_, etc.

Initial MArticle support for blockquotes

---

Pocket.xcodeproj/project.pbxproj
PocketKit/Sources/PocketKit/Item/ItemViewController.swift
PocketKit/Sources/PocketKit/Main/MainViewModel.swift
PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift
PocketKit/Sources/PocketKit/MyList/MyListViewController.swift
PocketKit/Sources/PocketKit/MyList/MyListViewModel.swift
PocketKit/Sources/PocketKit/PocketAlert.swift
Tests iOS/DeleteAnItemTests.swift
Tests iOS/Support/Elements/AlertElement.swift
Tests iOS/Support/Elements/PocketAppElement.swift

This pull request adds support for presenting a confirmation dialog when performing a destructive action, such as deleting an item from a user's list. This is done by setting the appropriate new property on the main view model, which will build and present an alert controller to be presented by the parent split controller. The idea here is that each area that requires a confirmation dialog (i.e alert) will build its own definition of what needs to be presented and request that it be presented by the main view model.

Present confirmation when deleting item from list

---

PocketKit/Sources/PocketKit/Article/Cells/ArticleComponentTextCell.swift

Because the `textContainer` parameter can be nil when passed into the
ArticleComponentTextView initializer, we need to reference the
`textContainer` property when setting the line fragment padding.
https://getpocket.atlassian.net/browse/IN-454

Fix for lines being cut-off in reader

---

PocketKit/Sources/PocketKit/Article/ArticleViewController.swift

The reader view wasn't responding to changes in reader settings.
Observing our own property, as opposed to the parameter being passed in
fixes the issue, though I don't fully understand why. We should be
observing the same instance either way.

Properly observe reader settings

---

PocketKit/Sources/PocketKit/Article/ArticleMetadataPresenter.swift
PocketKit/Sources/PocketKit/Article/ArticleViewController.swift
PocketKit/Sources/PocketKit/Article/Cells/ImageComponentCell.swift
PocketKit/Sources/PocketKit/Article/Cells/MarkdownComponentCell.swift
PocketKit/Sources/PocketKit/Article/Presenters/ImageComponentPresenter.swift
PocketKit/Sources/PocketKit/Article/Presenters/MarkdownComponentPresenter.swift
PocketKit/Sources/Textile/NSAttributedString+Extensions.swift
PocketKit/Sources/Textile/Style/Style+UIKit.swift

- Caption and Credit are now combined into a single text view (using different attributes for each).
- Images have a bottom margin of 24pt
Also used a different approach to handling of line height multipliers that is more in line with how UIKit does things.

Reader: Update image component layout

---

PocketKit/Sources/PocketKit/Home/RecommendationPresenter.swift
PocketKit/Sources/Sync/Slates/Slate+remoteMapping.swift
PocketKit/Sources/Sync/Slates/Slate.swift
PocketKit/Tests/SyncTests/APISlateServiceTests.swift
PocketKit/Tests/SyncTests/Fixtures/slates.json
PocketKit/Tests/SyncTests/SourceTests.swift
PocketKit/Tests/SyncTests/Support/Slate+Factories.swift

Many collections do not have a `topImageURL` property, causing a lot of
gray rectangles to be rendered on the home tab. To avoid this issue, we
fall back to the first entry in the underlying item's images collection.

Home: Use first image URL if topImageURL is not present

---

PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/MyList/MyListViewController.swift

Two simple fixes:
1. The background color of the Home collection view was not set, so the resulting color would be the system background rather than the "Pocket" background.
2. After the "My List" refactor to use the modern APIs, it seems as if the collection view was adding implicit decoration items for each section. By explicitly setting each section's `decorationViews` to `[]`, we see the expected color when scrolling to the bottom bottom of the list, as no additional views are rendered as the "background" to each section.

Fix incorrect background colors in Home and My List

---

PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
Tests iOS/MyList/ArchiveTests.swift

Regarding the failing test that was caused by items occasionally appearing in the wrong order:
With the previous implementation, I ran the failing test 10 times with these results:
```
Executed 10 tests, with 6 failures (0 unexpected) in 74.715 (74.720) seconds
```
With this new implementation, I ran the same test 10 times with these results:
```
Executed 10 tests, with 0 failures (0 unexpected) in 67.473 (67.479) seconds
```

Preserve server's ordering of archived items

---

PocketKit/Sources/PocketKit/Article/Cells/ArticleComponentTextCell.swift
PocketKit/Sources/PocketKit/Article/ReadableViewController.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/ArchivedItemViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/ReadableAction.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/ReadableAuthor.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/ReadableEvent.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/ReadableViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/RecommendationViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift
PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewController.swift
PocketKit/Sources/PocketKit/Item/ReadableHostViewController.swift
PocketKit/Sources/PocketKit/Main/CompactMainCoordinator.swift
PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift
PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift

1. Move from using a ReadableViewModelDelegate to using published events
2. Move tracking from ReadableHostViewController to its related view models
3. Move URL opening into ReadableViewModels
- Tracking URL opens and sharing selected text were actually broken 🙃 
There's a new pattern I've introduced into the view models for the event publishers:
```swift
private var _events: PassthroughSubject<ReadableEvent, Never> = .init()
var events: AnyPublisher<ReadableEvent, Never> {
_events.eraseToAnyPublisher()
}
```
The reason I introduced this pattern is to add a little more safety with regard to _who_ can send an event. `events` here is a "read-only" publisher, whereas its underlying implementation lets us send events appropriately (whose implementation detail is also now hidden).

Refactor ReadableViewModel to send events over delegation

---

Pocket.xcodeproj/project.pbxproj
PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/Sync/Archive/ArchiveService.swift
PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Sources/Sync/Source.swift
PocketKit/Tests/PocketKitTests/Support/MockSource.swift
PocketKit/Tests/SyncTests/PocketArchiveServiceTests.swift
PocketKit/Tests/SyncTests/Support/MockArchiveService.swift
Tests iOS/Fixtures/archived-favorite-items.json
Tests iOS/MyList/ArchiveFiltersTests.swift
Tests iOS/Support/RequestMatchers.swift
Tests iOS/Support/Response+factories.swift

This pull request adds support for viewing one's archive of favorited items.
The flow here is that once a user toggles `Favorite`, a blank snapshot will be rendered by the list, until items are fetched, at which point the (un)favorited items will be displayed. The implementation is very similar to that of `SavedItemsListViewModel`.
Behind the scenes, `Source` and its conforming types have been updated with the ability to supply `isFavorite` to the query used when fetching archived items.
Unit tests have been updated to ensure that the correct calls are being made, both through the `PocketArchiveService`, and `PocketSource`.
UI tests have been written to ensure that the toggle works as expected.
I've used the term "favorited" here as the term wrapping the `isFavorite` filter, but I'm happy …

Add support for fetching favorited archived items

---

PocketKit/Sources/PocketKit/Article/ReadableViewModel/ArchivedItemViewModel.swift
PocketKit/Sources/PocketKit/Home/CompactHomeCoordinator.swift
PocketKit/Sources/PocketKit/Item/ReadableHostViewController.swift
PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift
PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/CompactMyListContainerCoordinator.swift
PocketKit/Sources/PocketKit/PocketAlert.swift
PocketKit/Tests/PocketKitTests/ArchivedItemViewModelTests.swift

This pull request adds support for the following item actions when viewing an archived item:
Additional changes:
1. Receive published values on the main queue when the handler deals with presentation
This code has primarily been reviewed live by both Jacob and myself.

Implement Reader item actions for Archived items

---

PocketKit/Sources/PocketKit/Authorization/AuthorizationClient.swift
PocketKit/Sources/PocketKit/LoggedOut/PocketLoggedOutViewModel.swift
PocketKit/Sources/PocketKit/Services.swift
PocketKit/Tests/PocketKitTests/AuthorizationClientTests.swift
PocketKit/Tests/PocketKitTests/PocketLoggedOutViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockAuthenticationSession.swift

The FxA redirect will soon be updated to add `guid` and `id` query parameters to the preexisting `access_token`. This lets us remove the solo request for the `guid` preceding login, simplifying the network requests greatly from a previously-required 3 (one each for: guid, fxa, user ID), to 1 (guid, fxa, and user ID in a single response).

Obtain session guid and user id from FxA redirect

---

PocketKit/Sources/PocketKit/Authorization/AuthorizationClient.swift
PocketKit/Sources/PocketKit/Root/RootViewModel.swift

Fully implement new FxA redirect and fix missing analytics context

---

PocketKit/Sources/PocketKit/Authorization/AuthorizationClient.swift
PocketKit/Sources/PocketKit/LoggedOut/LoggedOutViewModel.swift
PocketKit/Tests/PocketKitTests/AuthorizationClientTests.swift
PocketKit/Tests/PocketKitTests/LoggedOutViewModelTests.swift

This pull request introduces better support for handling, capturing, and presentation of authentication errors.
Under certain circumstances, errors should be presented to the user:
1. If the FxA URL could not be generated
2. If the FxA redirect could not be parsed.
The thought behind this is that if a user _sees_ these errors, they will reach out to support.
Under certain circumstances, errors should be captured and bubbled up to Sentry. Currently, any and all errors that occur during FxA authentication will bubble up to Sentry.
Under certain circumstances, errors should be ignored:
1. When tapping "Cancel" when a web session is started, it is treated as an error. This error can be ignored; other errors thrown by the web session will be captured.

Better handling, capturing, and presentation of authentication errors

---

PocketKit/Sources/PocketKit/Authorization/AuthorizationClient.swift

Using `Swift.Error`, you cannot (anymore) override `localizedDescription` to provide a description. One should instead conform to `LocalizedError`, which _inherits_ from `Swift.Error`, but allows for custom descriptions:
> A specialized error that provides localized messages describing the error and why it occurred.
This pull request makes `AuthorizationClient.Error` conform to `LocalizedError` and provide better human-readable descriptions.

Correctly set AuthorizationClient.Error descriptions

---

Pocket.xcodeproj/project.pbxproj
Pocket.xcodeproj/xcshareddata/xcschemes/SaveToPocket.xcscheme
PocketKit/Package.swift
PocketKit/Sources/SaveToPocketKit/MainViewController.swift
PocketKit/Tests/SaveToPocketKitTests/SaveToPocketKitTests.swift
SaveToPocket/Info.plist

Code signing is not yet set up as we do not yet have the correct provisioning profile(s) generated.
The activation rule is carried over from the legacy app.

Create initial Share Extension target

---

PocketKit/Sources/SaveToPocketKit/ExtensionContext.swift
PocketKit/Sources/SaveToPocketKit/MainViewController.swift
PocketKit/Sources/SaveToPocketKit/MainViewModel.swift
PocketKit/Tests/SaveToPocketKitTests/MainViewModelTests.swift
PocketKit/Tests/SaveToPocketKitTests/Support/Calls.swift
PocketKit/Tests/SaveToPocketKitTests/Support/MockExtensionContext.swift
PocketKit/Tests/SaveToPocketKitTests/Support/MockKeychain.swift

This pull request introduces automatic dismissal of the `SaveToPocket` extension after `n` number of seconds. For the app implementation, this interval is 2 seconds, which is consistent with the legacy app. For tests, this interval is 0 seconds.
There are primary cases at this time:
1. The user is not logged in
2. The user is logged in, but there is no URL to share
3. The user is logged in, and there is a URL to share
All three of these cases will result in the view being automatically dismissed.

SaveToPocket: Support automatic dismissal

---

PocketKit/Sources/ApolloCodegen/FileStructure.swift
PocketKit/Sources/Sync/API.swift
PocketKit/Sources/Sync/Operations/SyncTask.swift
PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Sources/Sync/list.graphql
PocketKit/Tests/SyncTests/PocketSourceTests.swift
Tests iOS/MyList/ArchiveTests.swift
Tests iOS/Support/RequestMatchers.swift

When moving an item from archive back to my list, we need to use the `upsertSavedItem` mutation so that the backend updates the `_createdAt` property, which is what we sort my list by.
We were using the more specific `updateSavedItemUnArchive` mutation which only updates the `isArchived` property to true but does not update the `_createdAt` property.
This PR removes the `updateSavedItemUnArchive` mutation and changes `PocketSource.unarchive()` to use the correct mutation.
We also update the `createdAt` property locally before sending the mutation so that offline behavior is still correct.
Also: this builds on a couple of previous commits:
1. The Apollo codegen package needed to be updated to point to the new schema file
2. When archiving an item, we now update the local item's …

Items should appear at top of list when resaving

---

PocketKit/Sources/PocketKit/Home/HomeCollectionViewSectionProvider.swift
PocketKit/Sources/PocketKit/Home/TopicChipCell.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewController.swift

This pull request fixes an issue where topic chip cells were a constant height, and not calculated based on the current font as updated by the user's accessibility settings.

Accessibility: calculate topic chip cell heights

---

PocketKit/Sources/PocketKit/Article/ReadableViewModel/RecommendationViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift
PocketKit/Sources/PocketKit/Home/RecommendationPresenter.swift
PocketKit/Sources/PocketKit/Item/Item+Extensions.swift
PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListItem.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListItemPresenter.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewController.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItem+ItemsListItem.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/PocketKit/URL+Extensions.swift
PocketKit/Sources/Sync/Item+extensions.swift
PocketKit/Tests/PocketKitTests/ArchivedItemsListViewModelTests.swift
PocketKit/Tests/PocketKitTests/ItemsListItemPresenterTests.swift
PocketKit/Tests/PocketKitTests/SavedItemsListViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockItemsListItem.swift
PocketKit/Tests/PocketKitTests/Support/MockSource.swift
PocketKit/Tests/PocketKitTests/Support/SavedItem+factories.swift

This pull request adds support for pending saved items. A pending saved item is defined as a `SavedItem` where `item == nil`. In order to better support pending saved items, three things need to take place:
Since we _are_ now able to parse the host our of the saved item's URL, I've also added support for using the URL's host as a fallback across archived and recommended items.
This pull request fulfills these three items, as well as adds tests for two types: 
1. `ItemsListItemPresenter` - verifies that the `attributedTitle` and `attributedDetail` return the correct strings and styles based on what values an item has present
2. `SavedItemsListViewModel` - verifies that `shouldSelectCell` returns the correct value for (non-)pending items

Add support for pending saved items

---

PocketKit/Sources/PocketKit/Home/CompactHomeCoordinator.swift
PocketKit/Sources/PocketKit/MyList/CompactMyListContainerCoordinator.swift
PocketKit/Sources/PocketKit/ReaderSettings/ReaderSettingsView.swift

There are a few extra properties we can set on `UISheetPresentationController` to ensure that the view controller is dismissable in landscape. One oddity here is that we have to set both `.medium()` and `.large()` detents to support autorotate, as if we only set `.medium()`, then the landscape presentation using the new properties causes an exception, where having both detents is the workaround 🙃 
This does not change the iPad implementation, which uses a menu.

Fix display settings not dismissable in landscape

---

Info.plist
Pocket.xcodeproj/project.pbxproj
PocketKit/Sources/PocketKit/LoggedOut/LoggedOutViewController.swift
PocketKit/Sources/SaveToPocketKit/InfoView.swift
PocketKit/Sources/SaveToPocketKit/LoggedOut/LoggedOutViewController.swift
PocketKit/Sources/SaveToPocketKit/LoggedOut/LoggedOutViewModel.swift
PocketKit/Sources/SaveToPocketKit/MainViewController.swift
PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewController.swift
PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewModel.swift
PocketKit/Sources/SaveToPocketKit/Style+Extensions.swift
PocketKit/Tests/SaveToPocketKitTests/LoggedOutViewModelTests.swift
PocketKit/Tests/SaveToPocketKitTests/SavedItemViewModelTests.swift
PocketKit/Tests/SaveToPocketKitTests/Support/MockExtensionContext.swift
Tests iOS/SaveToPocketTests.swift
Tests iOS/Support/Elements/PocketAppElement.swift

This pull request adds support for presenting a "Log in to Pocket" button when opening the extension if the user is logged out. 
This view model has been updated to return a presenter (type: `MainViewPresenter` based on state and origin. This presenter is then used to conditionally show (or not show) an additional view at the bottom of `MainViewController` based on the usability of the presenter. In a logged out state, this is based on whether there is a `UIResponder` in the chain that can handle opening URLs. 
This type has been added as a protocol with one required property: `view: UIView?`. This view is what is conditionally shown at the bottom of `MainViewController`. Currently, there are two presenters: `SavedViewPresenter` (for when an item has been saved) and …

SaveTo: Add "Log In to Pocket" button when logged out

---

PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewController.swift
PocketKit/Sources/PocketKit/MyList/MyListContainerViewController.swift

Fixes an issue where the navigation bar state could be out-of-sync with the expected state based on the current visible collection view's content offset after toggling list selection.

Fix list switcher layout issue after toggling lists

---

PocketKit/Sources/PocketKit/Refresh/RefreshCoordinator.swift
PocketKit/Sources/Sync/OSNotificationCenter.swift
PocketKit/Sources/Sync/PocketModel.xcdatamodeld/PocketModel.xcdatamodel/contents
PocketKit/Sources/Sync/PocketSaveService.swift
PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Sources/Sync/Requests.swift
PocketKit/Sources/Sync/Source.swift
PocketKit/Sources/Sync/Space.swift
PocketKit/Tests/PocketKitTests/Refresh/RefreshCoordinatorTests.swift
PocketKit/Tests/PocketKitTests/Support/MockSource.swift
PocketKit/Tests/SyncTests/PocketSaveServiceTests.swift
PocketKit/Tests/SyncTests/PocketSourceTests+savedItemEvents.swift
PocketKit/Tests/SyncTests/PocketSourceTests.swift

- Listen for "unresolvedSavedItemCreated" notification
When this notification is recieved, we enqueue a `saveItem` sync task
that will be executed the next time a network connection becomes
available.
- Add `resolveUnresolvedSavedItems` method that can be called from
higher level code (such as PocketKit.RefreshCoordinator when the app
enters foreground)
- Send `.unresolvedSavedItemCreated` notification when:
- the expiring activity expires
- the request to client-api fails for any reason (such as a network timeout
or airplane mode being enabled)
- tell `source` to `resolveUnresolvedSavedItems` when app enters
foreground

ShareTo: Support saving items while offline

---

PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift
PocketKit/Sources/PocketKit/ItemAction.swift
PocketKit/Sources/PocketKit/ItemContextualAction.swift
PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListItemCell.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewController.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Tests/PocketKitTests/ArchivedItemsListViewModelTests.swift
PocketKit/Tests/PocketKitTests/SavedItemViewModelTests.swift
Tests iOS/ArchiveAnItemTests.swift
Tests iOS/MyList/ArchiveTests.swift
Tests iOS/Support/Elements/MyListElement.swift
Tests iOS/Support/Elements/PocketAppElement.swift

This pull request adds support for the "Move to My List" action via swipe when viewing one's archive.
- `trailingSwipeActions(for objectID: ItemIdentifier)` now returns `[ItemAction]?` instead of `UIContextualAction`, following a similar pattern to overflow actions.
- `Re-add` has been renamed to `Move to My List`, and all occurrences have been replaced.
- Any APIs that utilize a `Move to My List` action have been renamed accordingly for consistency.
- `(Pocket)Source` APIs have not been updated, and maintain `unarchive` as a naming convention.
- UI tests have been added for both swiping to archive from "My List", and swiping to "Move to My List" when viewing "Archive"

Add support for "Move to My List" via swipe in Archive

---

PocketKit/Sources/PocketKit/Article/ReadableViewModel/RecommendationViewModel.swift
PocketKit/Sources/PocketKit/Home/CompactHomeCoordinator.swift
PocketKit/Sources/PocketKit/Home/HomeCollectionViewSectionProvider.swift
PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Home/RecommendationPresenter.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewController.swift
PocketKit/Sources/PocketKit/Home/SlateHeaderPresenter.swift
PocketKit/Sources/PocketKit/Main/MainViewModel.swift
PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift
PocketKit/Sources/PocketKit/Report/ReportRecommendationHostingController.swift
PocketKit/Sources/PocketKit/Report/ReportRecommendationView.swift
PocketKit/Sources/Sync/PocketModel.xcdatamodeld/PocketModel.xcdatamodel/contents
PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Sources/Sync/RemoteMapping/SavedItem+RemoteMapping.swift
PocketKit/Sources/Sync/RemoteMapping/SlateLineup+remoteMapping.swift
PocketKit/Sources/Sync/Requests.swift
PocketKit/Sources/Sync/SavedRecommendationsService.swift
PocketKit/Sources/Sync/Slates/Slate+remoteMapping.swift
PocketKit/Sources/Sync/Slates/SlateService.swift
PocketKit/Sources/Sync/Slates/UnmanagedSlate.swift
PocketKit/Sources/Sync/Source.swift
PocketKit/Sources/Sync/Space.swift
PocketKit/Tests/PocketKitTests/Support/MockSource.swift
PocketKit/Tests/SyncTests/APISlateServiceTests.swift
PocketKit/Tests/SyncTests/PocketSourceTests.swift
PocketKit/Tests/SyncTests/Support/Item+factories.swift
PocketKit/Tests/SyncTests/Support/MockSlateService.swift
PocketKit/Tests/SyncTests/Support/SavedItem+factories.swift
PocketKit/Tests/SyncTests/Support/SlateLineup+factories.swift
PocketKit/Tests/SyncTests/Support/UnmanagedSlate+Factories.swift

Transition Slate(Lineup) to Core Data

---

Pocket.xcodeproj/project.pbxproj

Our development certificate has expired, so I've generated a new one.
The last one was created by "Mozilla Release Engineering" user, back
before we had permission to create one for ourselves.
I created the new one myself, and Apple sets the name of the cert to the
name of the user creating it. Hence the different name.

Update signing certificate

---

PocketKit/Sources/PocketKit/Article/Cells/ImageComponentCell.swift
PocketKit/Sources/PocketKit/Article/Presenters/ImageComponentPresenter.swift
PocketKit/Tests/PocketKitTests/ImageComponentPresenterTests.swift

**Summary**
In our article reader view, we have images that have a grey background if the image does not span to the entire width of the screen. We only want the grey background to appear if there is an image with a small image size and has an associated caption. If there is no caption, then we want to set the background of the image view to `.clear` instead of grey.
**Testing Steps**
1. Navigate to Home tab on an iPad and tap on the following article: [Night Shifts, by Michael W. Clune](https://harpers.org/archive/2022/04/night-shifts-dream-incubation-technology-sleep-research/)
2. Scroll through the article and verify that images have a clear background
3. Navigate to this following article: [How to Train Your Brain to Get What You Want in 60 Days] …

Omit gray image background when caption is not present

---

PocketKit/Sources/PocketKit/LoggedOut/LoggedOutViewController.swift

**Issue:** Progress indicator for the Login slideshow onboarding overlaps the readable text in Landscape view for iPhone
**Fix:** Disabled landscape view for iPhone and leave iPad view as is

IN-591: Constrain Logout Screen to Portrait View

---

PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift
PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/CompactMyListContainerCoordinator.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Tests/PocketKitTests/ArchivedItemsListViewModelTests.swift
PocketKit/Tests/PocketKitTests/SavedItemsListViewModelTests.swift

This issue is not specific to only video content but is related to items that are using the `SFSafariViewController` as they were not calling the `selectionCleared` event to deselect the cell.
1. Fix issue where safari view items were not auto-deselecting (iPhone)
2. Fix issue where archived items in reader view were not highlighting (iPad)
3. Refactor to use enum as the selected item could either be readable view or web view
1. Save a youtube video
2. Open it in My List View
3. Select "Done" in the upper left
4. Verify that item auto-deselects (de-highlights) itself
1. Save a YouTube video and archive it in My List View
2. Navigate to Archive View and tap on any of the items
3. Verify that the item does not deselect itself and is still highlighted (similar to the My List View)

IN-590: Fix Highlight For Item Selection

---

PocketKit/Sources/SaveToPocketKit/InfoView.swift
PocketKit/Sources/SaveToPocketKit/LoggedOut/LoggedOutViewController.swift
PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewController.swift
PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewModel.swift
PocketKit/Tests/SaveToPocketKitTests/SavedItemViewModelTests.swift

IN-586
IN-587
1. Fix incorrect text when saving pre-existing item
2. Add whitespace under dismiss label
3. Set explicit width of capsule on iPad
4. Fix padding between capsule icon and text
5. Add error state
6. Add support for saving items that conform to `public.plain-text` UTI (e.g Medium)

SaveTo: UI fixes and improved URL support

---

PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListItemCell.swift
PocketKit/Sources/Textile/Style/Style+UIKit.swift

**Issue:** My List/Archive item action buttons sizing does not match designs. This is due to the image being set as the background image and not the foreground image of the button. Also, the image were not conforming to 20x20 as specified in the Figma file.
**Fix:** Add resizable function to adjust image size and set images to the foreground instead of background of the button.
Reference: https://nshipster.com/image-resizing/
1. Navigate to MyList
2. Verify action button items (favorite, share, more) resemble the sizes in Figma file for iPhone and iPad.

IN-569: Fix List Item Action Buttons Sizing

---

PocketKit/Sources/SharedPocketKit/KeychainStorage.swift
PocketKit/Sources/SharedPocketKit/Session/Session.swift
PocketKit/Tests/SharedPocketKitTests/KeychainStorageTests.swift

This pull request modifies `KeychainStorage` to remove duplicates when publishing value changes. One such scenario where this was causing issue was when a user was logged out, and multiple `currentSession` values would be published despite the fact that the user was (still) logged out. The user, in this case, would see flickering because the scene was being updated and re-set up multiple times.
Due to how caching in `KeychainStorage` is handled, when the cached value is `nil`, the next "get" attempts to read from the keychain. This new value is set as the cached value. However, it is possible for `nil` to be read first, followed by another `nil` when attempting to "get" again, which in turn updates the cached value (to the same value). Updating the cached value published a change each …

Do not publish duplicate KeychainStorage values

---

PocketKit/Sources/SaveToPocketKit/LoggedOut/LoggedOutViewController.swift
PocketKit/Sources/SaveToPocketKit/LoggedOut/LoggedOutViewModel.swift
PocketKit/Sources/SaveToPocketKit/MainViewController.swift
PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewModel.swift
PocketKit/Tests/SaveToPocketKitTests/LoggedOutViewModelTests.swift
PocketKit/Tests/SaveToPocketKitTests/SavedItemViewModelTests.swift

As mentioned in the title, this updates the save extension to not autodismiss when there is an error. An error occurs when (1) a user is logged out, or (2) there is no URL within the extension context to save.

SaveTo: do not autodismiss on error

---

PocketKit/Sources/PocketKit/Authorization/AuthorizationClient.swift
PocketKit/Sources/PocketKit/LoggedOut/LoggedOutViewModel.swift
PocketKit/Tests/PocketKitTests/AuthorizationClientTests.swift
PocketKit/Tests/PocketKitTests/LoggedOutViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockAuthenticationSession.swift

This pull request adds authentication safeguards to ensure there is only one active authentication session while the user is logged out
IN-608
- Ensure the AuthorizationClient can only start one session at a time
- No-op LoggedOutViewModel.logIn and LoggedOutViewModel.signUp if the user is already logged in
Unit tests have been added, and self-QA was performed to ensure on-device authentication still worked as intended.

Add authentication safeguards against multiple attempts

---

PocketKit/Sources/PocketKit/ItemContextualAction.swift

This creates a much smoother animation and fixes the bug described in
the linked ticket.
Co-authored-by: David Skuza <dskuza@getpocket.com>
Co-authored-by: Cyndi Chin <cchin@mozilla.com>
IN-647

IN-647: Use ".destructive" style for swipe actions that remove a cell

---

PocketKit/Sources/PocketKit/Article/ArticleMetadataPresenter.swift
PocketKit/Sources/PocketKit/ReaderSettings/ReaderSettings.swift
PocketKit/Sources/SaveToPocketKit/Style+Extensions.swift
PocketKit/Sources/Textile/FontStyling/BlancoOSFStyling.swift
PocketKit/Sources/Textile/FontStyling/FontStyling.swift
PocketKit/Sources/Textile/FontStyling/GraphikLCGStyling.swift
PocketKit/Sources/Textile/NSAttributedString+Extensions.swift
PocketKit/Sources/Textile/Style/Paragraph/ParagraphStyle.swift
PocketKit/Sources/Textile/Style/Paragraph/TextAlignment.swift
PocketKit/Sources/Textile/Style/Style+Definitions.swift
PocketKit/Sources/Textile/Style/Style+UIKit.swift
PocketKit/Sources/Textile/StylerModifier.swift
PocketKit/Sources/Textile/TextileStyler.swift

This pull request updates the UI of the SaveTo extension, such as padding around capsule text, and the weight of the capsule font. Additionally, `TextileStyler` had to be updated to support the correct font weight (e.g semibold vs medium), based on the selected font family when reading an article.
In order for the updated font weights to be visible, the fonts that are included at build-time have to be updated. These fonts will be distributed async, as they are not licensed for inclusion in our open source repo.
IN-628
During design review, the SaveTo extension had incorrect padding when multi-line text was visible in the capsule. It was determined that the difference is due to how Figma uses the CSS "line-height" property vs how iOS renders text. "line-height" will center text within the …

Update SaveTo capsule styling and overall font styling

---

PocketKit/Sources/PocketKit/Article/ReadableViewModel/RecommendationViewModel.swift
PocketKit/Sources/PocketKit/Home/CompactHomeCoordinator.swift
PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift
PocketKit/Tests/PocketKitTests/RecommendationViewModelTests.swift
Tests iOS/ReportARecommendationTests.swift
Tests iOS/Support/Elements/PocketAppElement.swift

This pull request adds support for reporting an (unsaved) item from the Home feed, i.e a recommendation, from the reader when opening the action menu.
IN-432
A new `ItemAction` has been added to `RecommendationViewModel`, which is the `ReadableViewModel` generated when an item from the Home feed is opened. This action has only been added when an item is unsaved (i.e not in "My List" or "Archive"). This introduces a new `selectedRecommendationToReport` property that mimics that of `HomeViewModel`. This property is them sinked to within both regular and compact coordinators, at which point the report modal is presented for the recommendation. Additionally, the `report` function in the coordinators has been refactored to accept a closure that will be called on dismissal of the report view. …

Support reporting a recommendation from the reader

---

.github/pull_request_template.md

Adds template to repo for engineers to use when creating PRs
Reference: https://getpocket.atlassian.net/wiki/spaces/~625c9c3cd7f1b80069bcb183/pages/2720628737/iOS+Next+Templates

Add PR template to repository

---

PocketKit/Sources/PocketKit/Home/TopicChipCell.swift
PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/EmptyStates/ItemsList/ItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift
Tests iOS/MyList/ArchiveFiltersTests.swift
Tests iOS/MyList/EmptyStateTests.swift
Tests iOS/MyList/MyListFiltersTests.swift
Tests iOS/Support/Elements/MyListElement.swift

This pull request adds an "All" filter button to MyList and Archive.
IN-567
A new case `all` has been added to the `ItemsListFilter` enum. The initial `selectedFilters` will include the `all` case as default and a new private function `handleFilterSelection` contains the logic of how the selected filters behave depending on the different use cases mentioned in the Test Steps below.
There was also modifications in the logic to determine whether the filter button should present an image or not. 
**My List**
when I tap “All”,  then “All” should be selected, and “Favorites” deselected, and all my unarchived items should be visible.
**Archive**
then “All” should be selected and “Favorites” deselected, and all my archived items should be visible.

IN-567: Add All Filter Button

---

PocketKit/Sources/PocketKit/Home/HomeCollectionViewSectionProvider.swift
PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Home/LoadingCell.swift
PocketKit/Tests/PocketKitTests/HomeViewModelTests.swift

Adds an activity indicator when first loading the Home feed.
IN-672
`HomeViewModel.Section` and `HomeViewModel.Cell` each have a new `loading` case. When `HomeViewModel` is first initialized, it sets its initial snapshot to that of a "loading" snapshot - a snapshot that only contains a single `loading` section with a single `loading` item. `HomeViewControllerSectionProvider` returns a single section/group/item, which is then used to return a single `LoadingCell`. This cell is simple - it's a `UICollectionViewCell` subclass that houses a `UIActivityIndicatorView` that is always animating (since the loading cell is only ever present for a "loading" section and is not reused otherwise).

Home: show activity indicator on initial load

---

PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift

Fix delete and share action in the overflow menu for a recent saves item (iPad)
IN-698
* Added presentation logic for the alert and share sheet for iPad via `RegularMainCoordinator` (similar to the logic that was added for iPhone via `CompactHomeCoordinator`)

IN-698: Fix Delete + Share Action for Recent Saves on iPad

---

PocketKit/Sources/PocketKit/Home/RecommendationOverflowButton.swift
PocketKit/Sources/PocketKit/Home/RecommendationSaveButton.swift

Increase the tap areas of the "Save" and "Report" buttons in (Home) recommendation cells.
We are using a button configuration's `contentInsets` property to inset the image / text (i.e content) of the button a certain amount. Previously, this was 8pts in each direction. For the save button, all but the leading insets were increased to 16pts (as to keep the leading margin the same, else the button is inset too far into the cell). For the report button, all but the trailing insets were increased to 16pts (as to keep the trailing margin the same, else the button is inset too far into the cell).
This pull request can be automatically merged and will be fully "reviewed" during the integration / acceptance phase.

Increase tap area of recommendation save and report buttons

---

PocketKit/Sources/PocketKit/Home/HomeRecommendationCellViewModel.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewController.swift

Fix crash when reloading Home tab with items to be deleted due to SlateService.fetchSlateLineup(_:) deleting any unsaved items, which would publish changes upwards, resulting in erroneous snapshots being published.
IN-693
This one's a little… weird. The major change here is that we empty out `HomeViewModel.viewModels` and `HomeViewModel.viewModelSubscriptions` when refreshing the Home feed (with visible items saved). By emptying out these values, we ensure that we are (primarily) not observing changes to Core Data related to unsaved items being deleted from the database. Below is I _believe_ what was happening:
1. On first load (refresh), a new slate lineup is fetched and added to Core Data, resulting in a new snapshot being generated and applied for the slate lineup and its initial …

Fix crash when reloading Home tab with items to be deleted

---

PocketKit/Sources/Sync/Operations/FetchList.swift
PocketKit/Sources/Sync/Operations/RetriableOperation.swift
PocketKit/Sources/Sync/Operations/SaveItemOperation.swift
PocketKit/Sources/Sync/Operations/SavedItemMutationOperation.swift
PocketKit/Tests/SyncTests/Operations/RetriableOperationTests.swift
PocketKit/Tests/SyncTests/PocketSourceTests+networkMonitoring.swift
Tests iOS/DeleteAnItemTests.swift

It's technically possible for network operations to fail enough time to exceed our maximum number of allowed retries, but we don't actually know how often (if ever) this actually happens in practice. In order to get some more information about when/why/how this might happen, we add some logging (via Sentry).
https://getpocket.atlassian.net/browse/IN-709

Log errors when aborting retriable operations

---

PocketKit/Sources/PocketKit/Article/Cells/ArticleComponentTextCell.swift
PocketKit/Sources/PocketKit/Article/ReadableViewController.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/ReadableViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/RecommendationViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift
PocketKit/Sources/PocketKit/ItemAction.swift
PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Sources/Sync/Source.swift
PocketKit/Tests/PocketKitTests/RecommendationViewModelTests.swift
PocketKit/Tests/PocketKitTests/SavedItemViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockSource.swift
PocketKit/Tests/SyncTests/PocketSourceTests.swift

Presents a context menu to the user when tapping and holding links from text views in the reader.
IN-618
`ArticleComponentTextView` handles adding a `UIContextMenuInteraction` _to_ the text view, so that we can handle long presses. However, a `UITextView` adds its own context menu interaction upon initialization, so we have to filter out these existing context menu interactions and remove them, so we can handle our own. `ArticleComponentTextView` then handles the context menu interaction, only requesting a context menu when the location of the tap is _on_ a link. A request for the context menu to present is then requested up the delegate chain, finally reaching `ReadableViewController`. This view controller requests "external actions" (actions for links aside from the item url itself) …

Present context menu when tapping and holding links in reader

---

PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Sources/Sync/Source.swift
PocketKit/Tests/PocketKitTests/SavedItemsListViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockSource.swift
PocketKit/Tests/SyncTests/PocketSourceTests+networkMonitoring.swift

Sometimes network operations fail due to lack of connectivity or server errors. When this happens, those operations go into a "paused" state until they receive a signal to try again. That signal is sent at various times in the app lifecycle.
We consider the user-initiated "Pull to refresh" to be a strong signal that the network connection is probably available, so we initiate any retries immediately upon that interaction.
https://getpocket.atlassian.net/browse/IN-685
* `PocketSource` gains new method `retryImmediately`
* `SavedItemsListViewModel` calls this method when user initiates pull-to-refresh
1. Use [network link conditioner][0] to cause network traffic to fail 100% of the time
2. Favorite an item
3. Configure network link conditioner to have a solid connection
4. On a second …

Retry immediately on refresh

---

PocketKit/Sources/PocketKit/Home/HomeRecommendationCellViewModel.swift
PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewModel.swift
PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/Sync/Requests.swift
PocketKit/Tests/PocketKitTests/HomeRecommendationViewModelTests.swift

Immediately processing changes to the `isSaved` property of a recommendation cell's view model can be problematic due to the possibility that other significant changes are being made to the underlying recommendation in core data (i.e. it's being deleted).
Instead, we observe changes made at the CoreData level so that we don't send collection view snapshots too often.
https://getpocket.atlassian.net/browse/IN-711
Instead of using Key-value observation to respond to changes to a recommendation, we use an NSFetchedResultsController. This means we get notified of changes when the context is saved, as opposed to immediately when the property changes.
- Launch the app
- Make sure it doesn't crash ;)

Home crasher

---

PocketKit/Sources/Analytics/Context/UIContext.swift
PocketKit/Sources/PocketKit/Home/CompactHomeCoordinator.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewModel.swift
PocketKit/Sources/PocketKit/Item/Item+Extensions.swift
PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift
PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Tests/PocketKitTests/HomeViewModelTests.swift
Tests iOS/HomeTests.swift
Tests iOS/Support/Elements/HomeViewElement.swift

Add support for opening a recent save (either in Safari or in the reader) on tap.
IN-690
The biggest change here is moving from the `selectedReadableViewModel` to a more generic `selectedReadableType` enum, which supports two cases: recent save, and recommendation. I was hoping that we could just repurpose `ReadableViewModel` and publish a property of this type so that we could subscribe to all published properties in one spot, but there is one difference that prevented me from doing so: the fact that a `RecommendationViewModel` has to support reporting a recommendation, which I did not want to just add to the `ReadableViewModel` protocol since it is not shared with a `SavedItemViewModel`. Otherwise, everything is handled the same - tapping an item (recent save or recommendation) updates …

Home: open item when tapping on recent save

---

Pocket.xcodeproj/project.pbxproj
PocketKit/Sources/PocketKit/Home/HomeCarouselItemCell.swift
PocketKit/Sources/PocketKit/Home/HomeCollectionViewSectionProvider.swift
PocketKit/Sources/PocketKit/Home/HomeRecommendationCellViewModel.swift
PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Home/RecentSavesItemCell.swift
PocketKit/Sources/PocketKit/Home/RecommendationCarouselCell.swift
PocketKit/Sources/PocketKit/Home/RecommendationCell.swift
PocketKit/Sources/PocketKit/Home/RecommendationOverflowButton.swift
PocketKit/Sources/PocketKit/Home/RecommendationSaveButton.swift
PocketKit/Sources/PocketKit/Home/SectionHeaderView.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewController.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewModel.swift
PocketKit/Sources/PocketKit/Main/CompactMainCoordinator.swift
PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListItemCell.swift
PocketKit/Sources/PocketKit/Style/StyleConstants.swift
PocketKit/Sources/Textile/Style/Colors/Colors.xcassets/UI/border.colorset/Contents.json
PocketKit/Sources/Textile/Style/Colors/Palettes.swift
PocketKit/Tests/PocketKitTests/HomeViewModelTests.swift
PocketKit/Tests/PocketKitTests/SlateDetailViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockSource.swift
Tests iOS/HomeTests.swift
Tests iOS/HomeWebViewTests.swift
Tests iOS/ReportARecommendationTests.swift
Tests iOS/Support/Elements/HomeViewElement.swift
Tests iOS/Support/Elements/RecentSavesCellElement.swift
Tests iOS/Support/Elements/RecommendationCellElement.swift

Polishes the Home Design to better match the Figma File and added horizontal carousel for the recommendation cells.
IN-700, IN-707
Separated the Slate section to use two types of section `.slateHero` and `.slateCarousel`. Also, separated the slate cells from `.recommendation` to using `.recommendationHero` and `.recommendationCarousel`. Modified the `RecommendationCell` which is used for the hero card and added a new cell called `HomeCarouselItemCell` that is used for both recent saves and the horizontal recommendation cells. Made a couple of design tweaks such as adding section titles to the See All views, changing report button flow and made sure design worked for both dark / light mode. 
Note: This work does not take care of dynamic fonts. That work will be addressed in a new ticket: …

IN-700: Home Design Polish

---

PocketKit/Sources/PocketKit/Home/HomeCarouselItemCell.swift
PocketKit/Sources/Textile/Style/Colors/Colors.xcassets/UI/teal1.colorset/Contents.json

Update Toggle Text for Dark Mode + Fix for Image Aspect Mode for Home Carousel Cell
IN-725
Added Dark Mode color for `teal1` asset. Change image mode for `HomeCarouselItemCell` from `.aspectFit` to `.aspectFill`

IN-725: Update Toggle Text for Dark Mode + Fix Image Mode for Home Cell

---

PocketKit/Sources/PocketKit/Home/HomeRecommendationCellViewModel.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Home/RecommendationCarouselCell.swift
PocketKit/Sources/PocketKit/Home/RecommendationCell.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewModel.swift
PocketKit/Tests/PocketKitTests/HomeViewModelTests.swift
PocketKit/Tests/PocketKitTests/SlateDetailViewModelTests.swift
Tests iOS/Fixtures/save-recommendation-1.json
Tests iOS/Fixtures/save-recommendation-2.json
Tests iOS/HomeTests.swift
Tests iOS/Support/Elements/RecommendationCellElement.swift
Tests iOS/Support/Response+factories.swift

When adding a button action *that should replace another button action*,
it's crucial that the two actions have the same identifier.
Per Apple's documentation:
> UIActions are uniqued based on their identifier, and subsequent
> actions with the same identifier replace previously added actions.
In the case of save/archive actions, the save action should be replaced
by the archive action, so the two need to have the same identifier.
https://getpocket.atlassian.net/browse/IN-724

Use consistent action identifiers when attaching button actions

---

PocketKit/Sources/PocketKit/Home/HomeCarouselItemCell.swift
PocketKit/Sources/PocketKit/Home/HomeCollectionViewSectionProvider.swift
PocketKit/Sources/PocketKit/Home/HomeRecommendationCellViewModel.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Home/RecentSavesItemCell.swift
PocketKit/Sources/PocketKit/Home/RecommendationCarouselCell.swift
PocketKit/Sources/PocketKit/Home/RecommendationCell.swift
PocketKit/Sources/PocketKit/Home/RecommendationSaveButton.swift
PocketKit/Sources/PocketKit/Home/SectionHeaderView.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewController.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewModel.swift
PocketKit/Sources/PocketKit/Home/TopicChipCell.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListItemCell.swift
PocketKit/Sources/PocketKit/MyList/MyListTitleView.swift
PocketKit/Sources/PocketKit/Style/StyleConstants.swift
PocketKit/Sources/Textile/Style/Style+UIKit.swift
PocketKit/Sources/Textile/Style/Style.swift

Allow users to be able to read and view items in their preferred font size for Home, Slate Detail, My List / Archive
IN-723
Home
* Carousel cells are using a static height of 146, which gets scaled using `UIFontMetrics.default.scaledValue`, but because of additional white space for larger fonts, we cap this value to 300
* Hero Recommendation cells are configured based on the height calculations of the margins and views within the cell
* Set border on the view itself vs. content view because the content view was not resizing properly with the height change of the cell
* Added `maxScaleSize` to our Style extension as some labels we don't want to scale larger than a certain size (i.e. time to read, see all button, save)
SlateDetail
* Uses similar height calculation for a single card …

IN-700: Accessibility - Dynamic Fonts

---

PocketKit/Sources/PocketKit/Root/RootViewModel.swift

* I noticed that we were not attaching the user identifier to Sentry when doing my weekly sentry perusal.
* https://docs.sentry.io/platforms/apple/guides/ios/
* Added a call to set the sentry user identifier
* Trigger a crash
* Check sentry to ensure your hashed user id is linked in the sentry issue

fix(sentry): attaching the user id to sentry

---

PocketKit/Sources/PocketKit/Article/ReadableViewModel/ReadableViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/RecommendationViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift
PocketKit/Sources/PocketKit/Home/CompactHomeCoordinator.swift
PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewController.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewModel.swift
PocketKit/Sources/PocketKit/LoggedOut/LoggedOutCoordinator.swift
PocketKit/Sources/PocketKit/Main/CompactMainCoordinator.swift
PocketKit/Sources/PocketKit/Main/MainCoordinator.swift
PocketKit/Sources/PocketKit/Main/MainViewModel.swift
PocketKit/Sources/PocketKit/Main/RegularHomeCoordinator.swift
PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift
PocketKit/Sources/PocketKit/Main/RegularMyListCoordinator.swift
PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/CompactMyListContainerCoordinator.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/MyListContainerViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/PocketKit/Root/RootCoordinator.swift
Tests iOS/HomeTests.swift

* Refactor coordinators and properly unwind navigational view model properties
The goal of our coordinators is twofold:
1. We want to be able to encapsulate all business logic within our
view models, and simply observe their state to know when to present
modal views or push views onto a navigation controller.
2. When users transition from compact to regular size classes (or vice
versa), we can keep our compact view hiearchy in sync with the split
view's hiearchy.
The theoretical concept is mostly good —containing state within view
models that are shared between both the regular and compact coordinators
allows us to easily reconstruct the view hiearchy when the user
transitions size classes.
However, the practical reality is...less good. One of the complications
with this approach is that …

Refactor coordinators and properly unwind navigational view model properties

---

PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewModel.swift
PocketKit/Tests/PocketKitTests/HomeViewModelTests.swift
PocketKit/Tests/PocketKitTests/SlateDetailViewModelTests.swift

Add Loading Spinner to Home + Slate Detail
IN-672, IN-692
Check if the snapshot has any sections, if not, then show loading state via `loadingSnapshot`
when I view the Home tab and data has not yet been loaded,
then I should see a spinner in the middle of the screen.
when data has been loaded,
then the spinner should disappear and the Home content should be visible.
when I view the Home tab and tap on a slate topic and data has not yet been loaded,
then I should see a spinner in the middle of the screen.
when data has been loaded,
then the spinner should disappear and the Home content should be visible.

IN-672: Add Loading State to Home / Slate Detail View

---

Pocket (iOS).entitlements
Pocket.xcodeproj/project.pbxproj
PocketKit/Sources/SharedPocketKit/KeychainStorage.swift
PocketKit/Sources/Sync/PersistentContainer.swift
PocketKit/Tests/SharedPocketKitTests/KeychainStorageTests.swift
SaveToPocket/SaveToPocket.entitlements

Update the project to use provisioning profiles and certificates for development from the RIL team. This does not yet contain changes for release (i.e Bitrise).
IN-729

Transition provisioning profiles and app groups to RIL

---

PocketKit/Sources/PocketKit/Home/CompactHomeCoordinator.swift
PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewController.swift
PocketKit/Sources/PocketKit/Main/CompactMainCoordinator.swift
PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift
PocketKit/Sources/PocketKit/MyList/CompactMyListContainerCoordinator.swift
PocketKit/Sources/PocketKit/MyList/MyListContainerViewController.swift
PocketKit/Sources/PocketKit/Settings/AccountViewController.swift
PocketKit/Sources/PocketKit/Settings/CompactAccountCoordinator.swift

Disable iPhone support for landscape rotation in all views except the reader.
IN-701
`UINavigationController`, `UITabBarController`, and `UISplitViewController` each have delegate methods for returning their supported interface orientation(s). Since we're doing this on a per-viewcontroller basis (since Reader is separate), we have to return the value for the currently-displayed view controller. For `UINavigationController`, this is `visibleViewController`. For `UITabBarController`, this is `selectedViewController`. For `UISplitViewController`, on iPhone we defer to the compact view controller's supported interface orientations (i.e the tab bar controller when logged in). Each `UIViewController` then overrides `supportedInterfaceOrientations`.
The one extra "goofy" case is when popping …

Only support landscape in the reader on iPhone

---

PocketKit/Sources/PocketKit/Home/HomeCollectionViewSectionProvider.swift
PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListOfflineCell.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewController.swift
PocketKit/Sources/PocketKit/PocketSceneDelegate.swift
PocketKit/Tests/PocketKitTests/HomeViewModelTests.swift

This pull request adds support for presenting an "offline view" when there is no network connection (e.g airplane mode). When the user regains connection, Home will automatically refresh. Additionally, this functionality is mimicked in the Archive, where upon regaining network connection, the Archive will automatically refresh as well.
IN-694
IN-727
Given the app has not been opened and I am in airplane mode,
when I open the app and the Home tab is visible,
then I should see an offline screen.
Given the app has been opened and I am in airplane mode with the offline screen visible,
when I turn off airplane mode,
then the loading state should appear.
Given I have some recent saves
And I have airplane mode turned on
When I view the home tab and attempt to refresh,
Then I should see my recent …

Home: show offline view when there is no network connection

---

PocketKit/Sources/PocketKit/Tags/AddTagsView.swift
PocketKit/Sources/PocketKit/Tags/AddTagsViewModel.swift
PocketKit/Sources/Sync/API.swift
PocketKit/Sources/Sync/Operations/FetchList.swift
PocketKit/Sources/Sync/Operations/SaveItemOperation.swift
PocketKit/Sources/Sync/Operations/SavedItemMutationOperation.swift
PocketKit/Sources/Sync/Operations/SyncOperationFactory.swift
PocketKit/Sources/Sync/PocketModel.xcdatamodeld/PocketModel.xcdatamodel/contents
PocketKit/Sources/Sync/PocketSaveService.swift
PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Sources/Sync/RemoteMapping/SavedItem+RemoteMapping.swift
PocketKit/Sources/Sync/Requests.swift
PocketKit/Sources/Sync/Source.swift
PocketKit/Sources/Sync/Space.swift
PocketKit/Sources/Sync/list.graphql
PocketKit/Tests/PocketKitTests/AddTagsViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockSource.swift
PocketKit/Tests/SyncTests/Operations/ItemMutationOperationTests.swift
PocketKit/Tests/SyncTests/PocketSourceTests.swift
PocketKit/Tests/SyncTests/SpaceTests.swift
PocketKit/Tests/SyncTests/Support/MockOperationFactory.swift
Tests iOS/AddTagsItemTests.swift
Tests iOS/Fixtures/initial-list.json
Tests iOS/Support/Elements/AddTagsViewElement.swift

Add Tags Screen: user can select from list of existing tags
IN-232
* Added new section in SwiftUIView called `OtherTagsView` which shows list of tags not included in the input list. 
* Added new requests methods `fetchTagsWithNoSavedItems` and `fetchTags(excluding tags: [String])` to figure out which tags to delete and which tags to show in other tags view respectively. 
* For adding tags, we had to include 2 GraphQL mutations `UpdateSavedItemRemoveTagsMutation` and `ReplaceSavedItemTagsMutation` (see ticket for slack link with context). To allow the operation to take in both mutations in a clean way, we created AnyMutation as there was a generic constraint using GraphQLMutation.
and the user views the all tags section, 
then the user should be able to see existing tags (unless included …

IN-232: Add Tags Screen - User Can Select From Existing Tags

---

.swiftlint.yml
PocketKit/Sources/PocketKit/Main/RegularMyListCoordinator.swift
PocketKit/Sources/PocketKit/Root/RootCoordinator.swift
PocketKit/Sources/PocketKit/Root/RootViewModel.swift
PocketKit/Tests/SyncTests/PocketSourceTests+savedItemEvents.swift
Tests iOS/HomeTests.swift

A few touch ups after enabling swiftlint:
[Enable `multiline_arguments_brackets` in swiftlint](e52d3b811efec029a6abada46e3159d91aaddad0) (There were only three violations this rule 👍)
[Remove AnyObject from protocol constraints list](a736baedee6324d98f51bff11a4a7611897763db)
[Work around Swift's warning for unused constant](9daf2578e0aa52f7685642054f26096277640bbf)

Swiftlint: Enable multiline_arguments_brackets

---

Config/secrets.xcconfig.example
Pocket.xcodeproj/project.pbxproj
Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Pocket.xcodeproj/xcshareddata/xcschemes/Pocket (iOS).xcscheme
PocketKit/Package.swift
PocketKit/Sources/PocketKit/PocketAppDelegate.swift
PocketKit/Sources/SaveToPocketKit/Keys.swift
PocketKit/Sources/SaveToPocketKit/MainViewController.swift
PocketKit/Sources/SaveToPocketKit/Services.swift
PocketKit/Sources/Sync/Crashlogger.swift
SaveToPocket/Info.plist
bitrise.yml

* Update sentry implementation to always init. This is ok because if sentry has an invalid DSN or none, it will auto disable itself.
* Upgrade the sentry SDK to the latest version
* Only enable sentry debug mode and logging in a development/debug build
* Add sentry to the save extension
* Disabling bitcode since apple is retiring it and it makes uploading symbols much more difficult.
* Switching to deploy pipelines for parallelization (future test improvements ;) )
* https://getpocket.atlassian.net/browse/IN-817

chore(sentry): adding sentry enhancements [IN-817]

---

Config/secrets.xcconfig.example
Info.plist
Pocket (iOS).entitlements
Pocket.xcodeproj/project.pbxproj
Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PocketKit/Package.swift
PocketKit/Sources/PocketKit/Keys.swift
PocketKit/Sources/PocketKit/PocketAppDelegate+PocketNotificationService.swift
PocketKit/Sources/PocketKit/PocketAppDelegate.swift
PocketKit/Sources/PocketKit/PocketNotificationService.swift
PocketKit/Sources/PocketKit/Services.swift
PushNotificationServiceExtension/Info.plist
PushNotificationServiceExtension/NotificationService.swift
PushNotificationStoryExtension/Info.plist
PushNotificationStoryExtension/NotificationViewController.swift
bitrise.yml

* Allow us to use Braze for push notifications and in app messages
* https://getpocket.atlassian.net/browse/IN-668
* Push notifications are registered for a user [provisionally](https://www.braze.com/docs/user_guide/message_building_by_channel/push/ios/notification_options/#provisional-push) as soon as the application is launched (not after they login), this will cause a user to not see a modal for push and allow us to push notifications to the notification center quietly. Braze recommends this, because it allows us to start sending push notifications and give a user a taste of what they can get if they explicitly opt in.
* An update to the Braze SDK in September will allow us to use in-app messages to also convince a user to give Pocket explicit push action after they perform a …

[IN-668] Braze SDK Integration

---

bitrise.yml

* Noticed we should be using the example secrets for tests

fix(tests): making tests use example secrets

---

fastlane/Fastfile

* Switching to fastlane maintainers recommended solution for internal testflight builds, looks like I originally had it wrong.
https://github.com/fastlane/fastlane/pull/19735#issuecomment-1028398066

fix(fastlane): switching to recomended flow

---

PocketKit/Sources/PocketKit/Home/HomeCollectionViewSectionProvider.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Home/SectionHeaderView.swift
PocketKit/Sources/PocketKit/Main/MainViewModel.swift
PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift
PocketKit/Sources/PocketKit/Navigation/NavigationSidebarCell.swift
PocketKit/Sources/PocketKit/Navigation/NavigationSidebarCellViewModel.swift
PocketKit/Sources/PocketKit/Navigation/NavigationSidebarViewController.swift

Hide the chevron for "My List" button by giving the corresponding view model a `buttonImage` property that can be passed in.
Also:
- A fix for when an edge case where the sidebar is already showing Settings or My List, but the user taps the "My List" button on Home. To handle this case, we explicitly set the navigation stack to what it should be (as opposed to simply pushing the next view controller).
- Better handling for selection status in the sidebar. We reload each cell whenever the selected section changes so that the correct cell is highlighted.
https://getpocket.atlassian.net/browse/IN-760

Hide chevron in "My List" button

---

fastlane/Fastfile

* After digging through fastlane code, we still need to wait for the build to process.
However we will need to wait till https://github.com/fastlane/fastlane/pull/20644 is merged or another answer is provided

fix(testflight): wait for build to process

---

PocketKit/Sources/Sync/API.swift
PocketKit/Sources/Sync/Operations/FetchList.swift
PocketKit/Sources/Sync/RemoteMapping/SavedItem+RemoteMapping.swift
PocketKit/Sources/Sync/list.graphql
PocketKit/Tests/SyncTests/Operations/FetchListTests.swift

* In apollo studio unless you drill down it was hard to realize that UserByToken was for fetching a user's saves. This renames it so it is clear to others.

fix(query): updating list query name to be representiative

---

PocketKit/Sources/Sync/API.swift
PocketKit/Sources/Sync/RemoteMapping/SavedItem+RemoteMapping.swift
bitrise.yml

* The find and replace of UserByToken accidentally took API.swift with it in ways it should not have.  This fixes that bug. 
* Note that the tests continued to pass because API.swift was modified and checked in. Moving forward I updated bitrise.yml always to download the latest API Schema which would have caught this bug after the find and replace.

fix(rename): fixing bug in rename

---

Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Pocket.xcodeproj/xcshareddata/xcschemes/Pocket (iOS).xcscheme
PocketKit/Dangerfile.swift
PocketKit/Package.resolved
PocketKit/Package.swift
PocketKit/Sources/DangerDependencies/Fake.swift
bitrise.yml

* Turns on xcode coverage
* Adds in Danger.systems to post code coverage of changed files to the pr comments
*  Note: we can build more on danger later if we want.
* https://pocket.slack.com/archives/C01UH57EJKD/p1663186743065739
* This implements danger with swift which adds some dependencies.
* Note that code coverage is on for all targets, this is because for some reason Xcode won't generate code coverage  unless it we tell it all.

feat(coverage): adding code coverage reports

---

PocketKit/Sources/PocketKit/Article/ReadableViewModel/RecommendationViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift
PocketKit/Sources/PocketKit/Banner/BannerView.swift
PocketKit/Sources/PocketKit/Banner/BannerViewModel.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewModel.swift
PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/PocketKit/Pasteboard.swift
PocketKit/Sources/PocketKit/Root/RootCoordinator.swift
PocketKit/Sources/PocketKit/Root/RootViewModel.swift
PocketKit/Tests/PocketKitTests/LoggedOutViewModelTests.swift
PocketKit/Tests/PocketKitTests/RecommendationViewModelTests.swift
PocketKit/Tests/PocketKitTests/SavedItemViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockPasteboard.swift
PocketKit/Tests/SyncTests/PocketSourceTests+networkMonitoring.swift
Tests iOS/BannerViewTests.swift
Tests iOS/HomeTests.swift
Tests iOS/HomeWebViewTests.swift
Tests iOS/MyList/ArchiveTests.swift
Tests iOS/MyList/MyListTests.swift
Tests iOS/Support/Elements/AddTagsViewElement.swift
Tests iOS/Support/Elements/PocketAppElement.swift
Tests iOS/Support/XCTestCase+extensions.swift
bitrise.yml

The biggest change here is the switch from using a regular `UIButton` to trigger a save action from a URL in the clipboard. It also contains a few other fixes to unit and UI tests to account for slight changes in behavior in the new version of XCTest.
- [Avoid usages of pasteboard in unit tests](https://github.com/Pocket/pocket-ios/commit/70a9be36410387784cd2930a872979a9665e3ba1)
- [Run tests via MainActor when necessary](https://github.com/Pocket/pocket-ios/commit/ef800f851517c477677bb32fa6f6505cd0c25508)
- [Avoid system alert when pasting URLs](https://github.com/Pocket/pocket-ios/commit/83e617aff092a7a49e842383f480a3d2c687c623)
- [Fix a network retry tests](https://github.com/Pocket/pocket-ios/commit/4c1cafbe1ee45b31bbf371d1f87f32a59929737f …

Updates for Xcode 14

---

PocketKit/Sources/PocketKit/Main/RegularMyListCoordinator.swift
PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/CompactMyListContainerCoordinator.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewController.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SortFilterMenu/View/ListOptions.swift
PocketKit/Sources/PocketKit/MyList/SortFilterMenu/View/SortMenuViewCell.swift
PocketKit/Sources/PocketKit/PocketSceneDelegate.swift
PocketKit/Sources/Sync/Operations/ArchiveService.swift
PocketKit/Sources/Sync/Operations/FetchList.swift
PocketKit/Tests/PocketKitTests/ArchivedItemsListViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockArchiveService.swift
PocketKit/Tests/SyncTests/Operations/PocketArchiveServiceTests.swift
Tests iOS/MyList/ArchiveTests.swift
Tests iOS/MyList/MyListTests.swift

Fixed sorting issue when switching between Archive and Saved List
Consuming SortMenu View to implement sorting functionality for Archive List.
[IN-509](https://getpocket.atlassian.net/browse/IN-509)
Consuming SortMenu View to implement sorting functionality for Archive List.
Given I have opened the Pocket app,
when I view the My List tab and switch to Archive List, it shows Archive items in All and Favorite.
then I should be able to click on 'Sort/Filter' menu and apply sorting by choosing 'Newest option'. Archive items should sort by 'Newest' archive items.
Given I have opened the Pocket app,
when I view the My List tab and switch to Archive List, it shows Archive items in All and Favorite.
then I should be able to click on 'Sort/Filter' menu and apply sorting by choosing 'Oldest …

IN-509-Implement sort functionality for Archive list

---

bitrise.yml

When we moved to smaller machines the tests got very flaky in our CI.  
For now, we have the approval to put this back and look into this at a later date.

fix(bitrise): move back to larger machines for now

---

PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift
PocketKit/Sources/PocketKit/Home/CompactHomeCoordinator.swift
PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift
PocketKit/Sources/PocketKit/Main/RegularMyListCoordinator.swift
PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/CompactMyListContainerCoordinator.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/PocketKit/Settings/SettingsView.swift
PocketKit/Sources/PocketKit/Tags/PocketAddTagsViewModel.swift
PocketKit/Sources/SaveToPocketKit/LoggedOut/LoggedOutViewModel.swift
PocketKit/Sources/SaveToPocketKit/MainViewController.swift
PocketKit/Sources/SaveToPocketKit/SaveToAddTagsViewModel.swift
PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewController.swift
PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewModel.swift
PocketKit/Sources/SaveToPocketKit/Style+Extensions.swift
PocketKit/Sources/Sync/PocketSaveService.swift
PocketKit/Sources/Sync/SaveService.swift
PocketKit/Sources/Textile/Views/Tags/AddTagsView.swift
PocketKit/Sources/Textile/Views/Tags/AddTagsViewModel.swift
PocketKit/Tests/PocketKitTests/PocketAddTagsViewModelTests.swift
PocketKit/Tests/SaveToPocketKitTests/SaveToAddTagsViewModelTests.swift
PocketKit/Tests/SaveToPocketKitTests/SavedItemViewModelTests.swift
PocketKit/Tests/SaveToPocketKitTests/Support/MockSaveService.swift
PocketKit/Tests/SaveToPocketKitTests/Support/PersistentContainer+testContainer.swift
PocketKit/Tests/SaveToPocketKitTests/Support/Space+factories.swift
PocketKit/Tests/SyncTests/Fixtures/add-tags.json
PocketKit/Tests/SyncTests/Fixtures/update-tags.json
PocketKit/Tests/SyncTests/PocketSaveServiceTests.swift
Tests iOS/SaveToPocketTests.swift

Added the ability for users to add tags to a Saved Item via Save Extension
IN-321
* Move `AddTagsView` into the shared UI Component `Textile` and created a two view models (one for PocketKit and one for SaveTo Extension) which both conform to `AddTagsViewModel` protocol. Modified the `PocketSaveService` to be able to send the GraphQL mutations related to tags and update the saved item accordingly. Added a new `infoViewModel` called `.taggedItem` to show the user a confirmation view.
* Change the copy of existing item from `You've already saved this before. We'll move it to the top of your list.` to `You've already saved this. We'll move it to the top of your list.` as confirmed with product.
* Extended dismiss timer as it disappeared too quickly
and the user taps on Add Tags button, 
then …

IN-321: Add Tags to Save Extension

---

PocketKit/Sources/PocketKit/Article/Presenters/UnsupportedComponentPresenter.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/ReadableViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/RecommendationViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift
PocketKit/Sources/PocketKit/Home/CompactHomeCoordinator.swift
PocketKit/Sources/PocketKit/Item/ReadableHostViewController.swift
PocketKit/Sources/PocketKit/Main/RegularHomeCoordinator.swift
PocketKit/Tests/PocketKitTests/SavedItemViewModelTests.swift
Tests iOS/ArchiveAnItemTests.swift

* added archive to top level of Reader view
* [IN 876](https://getpocket.atlassian.net/jira/software/projects/IN/boards/80?selectedIssue=IN-876)
* Added coordinator handlers for CompactHome and RegularHome
* removed overflow menu archive
* added navigation item for archive
* Go to home
* select an article with reader
* archive should be visible in top navigation menu (left of Safari)
* click archive
* should archive the item and bring you back to home
* go to my list
* select an article with reader
* archive should be visible in top navigation menu
* click archive
* should archive the item and bring you back to my list
<details>
</details>

IN 876 - top level archive

---

.swiftlint.yml
PocketKit/Sources/PocketKit/Activity/CopyLinkActivity.swift
PocketKit/Sources/PocketKit/Activity/CopyLinkWithSelectionActivity.swift
PocketKit/Sources/PocketKit/Article/Cells/MarkdownComponentCell.swift
PocketKit/Sources/PocketKit/Article/Presenters/UnsupportedComponentPresenter.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/RecommendationViewModel.swift
PocketKit/Sources/PocketKit/Authorization/AuthorizationClient.swift
PocketKit/Sources/PocketKit/Banner/BannerView.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListItemCell.swift
PocketKit/Sources/PocketKit/OnDismissHostingController.swift
PocketKit/Sources/PocketKit/ReaderSettings/ReaderSettingsViewController.swift
PocketKit/Sources/PocketKit/Settings/Components/PremiumRow.swift
PocketKit/Sources/PocketKit/Settings/Components/SettingsRowLink.swift
PocketKit/Sources/SharedPocketKit/DeviceUtilities.swift
PocketKit/Sources/Sync/PocketModel.xcdatamodeld/PocketModel.xcdatamodel/contents
PocketKit/Tests/PocketKitTests/SlateDetailViewModelTests.swift
PocketKit/Tests/SyncTests/PocketSaveServiceTests.swift
PocketKit/Tests/SyncTests/PocketSourceTests.swift

Update swiftlint rules that have been voted on according to the SwiftLint Mozilla spreadsheet
https://docs.google.com/spreadsheets/d/1UY2rqwVFDbyJYj4oSnwSrdE4Fj2Wy-RhuH4AFaBUogY/edit#gid=841652337
IN-900
Added rules based on the spreadsheet mentioned above as some rules in the Firefox repo was not included even though it was voted on. This is due to a lot of changes and they treat them as errors vs warnings, so they haven't gotten a chance to integrate the rules. There were a couple of rules that still need to be added, but due to more changes - decide to postpone that for a future PR. 
With this work, we add the following:
- anyobject_protocol
- array_init
- attributes
- capture_variable
- closure_spacing
- compiler_protocol_init
- computed_accessors_order
- duplicate_enum_cases
- …

ci(swiftlint): SwiftLint Updates

---

PocketKit/Sources/PocketKit/Home/HomeRecommendationCellHeroWideViewModel.swift
PocketKit/Sources/PocketKit/Home/HomeRecommendationCellViewModel.swift
PocketKit/Sources/PocketKit/Recommendation/Recommendation+Extenstions.swift
PocketKit/Sources/Sync/API.swift
PocketKit/Sources/Sync/PocketModel.xcdatamodeld/PocketModel.xcdatamodel/contents
PocketKit/Sources/Sync/RemoteMapping/Item+remoteMapping.swift
PocketKit/Sources/Sync/RemoteMapping/SlateLineup+remoteMapping.swift
PocketKit/Sources/Sync/Slates/SlateService.swift
PocketKit/Sources/Sync/archive.graphql
PocketKit/Sources/Sync/home.graphql
PocketKit/Sources/Sync/itemFragments.graphql
PocketKit/Sources/Sync/list.graphql
PocketKit/Tests/PocketKitTests/Recomendation/RecomendationExtensionTests.swift
PocketKit/Tests/PocketKitTests/Support/Space+factories.swift
PocketKit/Tests/SyncTests/Fixtures/archived-items.json
PocketKit/Tests/SyncTests/Fixtures/slate-detail.json
PocketKit/Tests/SyncTests/Fixtures/slates.json
Tests iOS/Fixtures/slate-detail-1.json
Tests iOS/Fixtures/slate-detail-2.json
Tests iOS/Fixtures/slate-detail-web-view.json
Tests iOS/Fixtures/slates-web-view.json
Tests iOS/Fixtures/slates.json
Tests iOS/Fixtures/updated-slates.json
Tests iOS/HomeTests.swift
Tests iOS/ReportARecommendationTests.swift

* Ensure that we follow how other clients choose to display item recommendation data, until this logic is fully upserted into the Pocket Graph. 
* https://getpocket.atlassian.net/browse/IN-748
* I followed the derivers implemented by the Web team [here](https://github.com/Pocket/web-client/blob/75f606321564cd85da82cc8ace0a8e14c799a48c/src/common/api/derivers/item.js#L268)
* I moved queries and fragments out of list.graphql into their own files. Once we have Apollo 1.0 setup and merged, this organization will get even more cleaner: https://github.com/Pocket/pocket-ios/pull/277
* Switching to Unified Home + Corpus Items
* View Home
* When home is viewed, and we have curated metadata present it is displayed.
* You can verify correct metadata is shown by navigating to our curation tools and …

fix(curatedInfo): pulling in old curatedInfo object for recomendations

---

PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SortFilterMenu/SortMenuModel.swift
PocketKit/Sources/PocketKit/MyList/SortFilterMenu/SortMenuViewModel.swift
PocketKit/Sources/PocketKit/MyList/SortFilterMenu/View/ListOptions.swift
PocketKit/Sources/PocketKit/PocketSceneDelegate.swift
PocketKit/Tests/PocketKitTests/ArchivedItemsListViewModelTests.swift
PocketKit/Tests/PocketKitTests/SavedItemsListViewModelTests.swift
PocketKit/Tests/PocketKitTests/SortMenuViewModelTests.swift

- IN-508-Sort by longest and shortest time to read for Saved Item List
- Remove/exclude 'Shortest time to read' & 'Longest time to read' options for Archive item list
- Two separate ListOptions properties for Saved & Archive: This does mean, sorting selection of Saved and Archive list will be independent and will not have impact on each other.
- List Options: For saved & archive lists, the both properties of ListOptions were observed parallel when only 1 need events to be notified. Changes are done in ListOptions class to accommodate the optimization so only 1 ListOption listen and notified when needed at a time since user will either be on Saved List or Archive List.
[IN-508](https://getpocket.atlassian.net/browse/IN-508)
Consuming SortMenu to add and implement sort options - 'Shortest …

IN-508-Sort by longest and shortest time to read for Saved Item List only, exclude in Archive list

---

Tests iOS/SaveToPocketTests.swift

* TypeText was missing the "g" in "tag" every so often causing the test to fail
* [IN-908](https://getpocket.atlassian.net/jira/software/projects/IN/boards/80?selectedIssue=IN-908)
* added each character individually based on David's expertise
* run `test_userAddTags_showsConfirmationView`

refactor(failing test): typeText not 100% correct [IN-908]

---

Pocket.xcodeproj/project.pbxproj
Pocket.xcodeproj/xcshareddata/xcschemes/Pocket (iOS).xcscheme
UITests-2.xctestplan
UITests-3.xctestplan
UITests.xctestplan
UnitTests.xctestplan
bitrise.yml

https://getpocket.atlassian.net/browse/IN-902
- Figure out how to de-dupe build steps
- Add multiple device types
* This builds on https://github.com/Pocket/pocket-ios/pull/244

build(concurency): switch to concurrent tests and test plans [IN-902]

---

PocketKit/Sources/Sync/Operations/RetriableOperation.swift

Log breadcrumb instead of capturing a message so the error details are associated to the sentry error.

Better error logging when max retries are exceeded

---

Tests iOS/SaveToPocketTests.swift

When typing, you can call `typeText` on the app in the foreground to make sure the keyboard is always available. If you try and type within a specific UI element, it's liable to fail if that element becomes obscured (sometimes by the keyboard itself)

Scope `typeText` to entire app instead of a single text field

---

PocketKit/Sources/PocketKit/Main/CompactMainCoordinator.swift
PocketKit/Sources/PocketKit/Settings/SettingsView.swift
PocketKit/Sources/Textile/Views/SFIcon/SFIconModel.swift

Note: In draft - waiting on confirmation from design
* Updates Settings background color to match Saves/Home background color
* Updates icon to match text in Dark Mode
IN-864
There has been a change in how to modify the color of the background of a List / Form natively in SwiftUI for iOS 16. Updated the code to utilize this new way as well update the colors so that it looks similar in iOS 15.
https://sarunw.com/posts/swiftui-list-background-color/#how-to-hide-swiftui-list-background
Also, had to change how we are implementing the tab bar style by using the new APIs in changing its appearance.
1. Navigate to Settings
2. Verify background color is consistent across tabs and devices 
|Light Mode|Dark Mode|
|------|-----|
|![Light Mode](https://user-images.githubusercontent.com/6743397/1975647 …

fix(settings): Fix Background Color [IN-864]

---

PocketKit/Sources/PocketKit/Home/CompactHomeCoordinator.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewModel.swift
PocketKit/Sources/PocketKit/Main/RegularHomeCoordinator.swift
Tests iOS/ShareAnItemTests.swift

* Adding a `Share` function to the home screen and the slates screen
* [IN-743](https://getpocket.atlassian.net/jira/software/projects/IN/boards/80/backlog?selectedIssue=IN-743)
* Added the `Share` function to the overflow menus for Home and Slates
* While on Home, clicking on the overflow menu of any card should show a `share` function
* clicking on `share` would bring up a pop-up for sharing
* navigating to Slate Details (`See All` section) will also show an overflow menu with a `share` function
* clicking on `share` will also bring up a pop-up for sharing
<details>
<summary>Overflow videos</summary>
|Home|Slate|
|------|-----|
|![Home screen share](https://user-images.githubusercontent.com/111293209/194321837-01c675ca-83c5-47ec-9fec-ad2b905130ee.gif)|![Slate …

IN-743 added share to Home and Slates

---

Pocket.xcodeproj/project.pbxproj
Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PocketKit/Package.swift

* Braze Push Service targets need braze included in the project root packages to work, but they need to be bumped when Package.swift is also bumped or it conflicts.

fix(braze): versioning in the root project was different

---

PocketKit/Sources/Sync/Operations/FetchList.swift

Fix issue where tags were not all downloading after a user adds a tag on a different device and then signs in and view tags on another device.
IN-866
Made changes to how we are passing in the input values in our GraphQL query for PaginationInput. We may want to handle the case in which we don't pass any input values and throw an error or return default via backend, but making this fix for now.
See slack convo here: https://pocket.slack.com/archives/C01VDFM30J2/p1666800998893259
1. Sign out of pocket
2. Add new tag to oldest Archive item on Web
3. Sign into Pocket
4. Navigate to Saves on iOS 
5. Tap on Add Tags + Filter Tags
6. Verify that new tag appears

fix(tags): Download All Tags [IN-866]

---

PocketKit/Package.swift
PocketKit/Sources/Analytics/Context/UIContext.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift
PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListItemCell.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewController.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/SaveToPocketKit/MainViewController.swift
PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewModel.swift
PocketKit/Sources/SaveToPocketKit/Services.swift
PocketKit/Tests/SaveToPocketKitTests/SavedItemViewModelTests.swift
PocketKit/Tests/SaveToPocketKitTests/Support/MockTracker.swift

Track engagement event when adding tag(s) + save extension
```
Two engagement events for Add Tags Flow:
* When a user views an item in My List and goes to overflow menu and taps on Add Tag button
* When a user views an item in Reader and taps the Tag button from the overflow menu
Three engagement events for Save Extension:
* User taps share button and add To Pocket
* User clicks add tags option.
* User adds the relevant tags and then clicks Done.
```
IN-151
Added PocketTracker to be used in the Save Extension and track general add tags call
1. Follow the testing steps in this doc to setup snowplow locally:
https://getpocket.atlassian.net/wiki/spaces/PFC/pages/2779447327/Testing+Analytics+for+iOS+Next
2. Use steps here to trigger calls: …

feat(tags): Analytics for Add Tags [IN-151]

---

PocketKit/Sources/Analytics/Tracker/PocketSnowplowTracker.swift

Enable Automatic View Tracking in Snowplow
IN-832
Added Screen View Tracking which is composed of 2 settings:
* `screenViewAutotracking`: the tracker automatically tracks each screen change (triggered by viewDidAppear in a ViewController) using a ScreenView event
```
"data": {
"schema": "iglu:com.snowplowanalytics.mobile/screen_view/jsonschema/1-0-0",
"data": {
"id": "B4C81E97-4835-49D1-A540-76CFF0025BCB",
"previousName": "UINavigationController",
"previousType": "SplitView",
"name": "PocketKit.HomeViewController",
"type": "SplitView",
"previousId": "B8132DD0-92CD-453A-B4C1-0563BE17F229"
}
}
```
Note: Some of the automatic capture are inconsistent with our manual calls. This is due to our calls being triggered prior to the `viewDidAppear`
* `screenContext`: the tracker attaches a Screen …

feat(snowplow): Add Auto Screen View Tracking [IN-832]

---

PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewController.swift
PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewModel.swift
PocketKit/Tests/SaveToPocketKitTests/SavedItemViewModelTests.swift
Tests iOS/SaveToPocketTests.swift

* Auto-dismiss the save to pocket modal when adding tags
* [IN-925](https://getpocket.atlassian.net/jira/software/projects/IN/boards/80?selectedIssue=IN-925)
* added `finish()` and `context` to `addTags` in `SavedItemViewModel`
* navigate to another app
* share an article to pocket
* when the pop-up shows, click add tag
* add a tag
* should dismiss
* navigate to another app
* share an article to pocket
* when the pop-up shows, click add tag
* cancel
* should take you to initial modal

feat(tags): auto-dismiss on adding tags [IN-925]

---

.swiftlint.yml
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListItemPresenter.swift
PocketKit/Tests/PocketKitTests/ArchivedItemsListViewModelTests.swift
PocketKit/Tests/PocketKitTests/Recomendation/RecomendationExtensionTests.swift
PocketKit/Tests/PocketKitTests/RecommendationViewModelTests.swift
PocketKit/Tests/PocketKitTests/SavedItemsListViewModelTests.swift
PocketKit/Tests/PocketKitTests/SlateDetailViewModelTests.swift
PocketKit/Tests/SaveToPocketKitTests/SaveToAddTagsViewModelTests.swift
PocketKit/Tests/SaveToPocketKitTests/SavedItemViewModelTests.swift
PocketKit/Tests/SaveToPocketKitTests/Support/Fixture.swift
PocketKit/Tests/SyncTests/PocketSaveServiceTests.swift
PocketKit/Tests/SyncTests/Support/Fixture.swift

Update swiftlint rules that have been voted on according to the SwiftLint Mozilla spreadsheet
https://docs.google.com/spreadsheets/d/1UY2rqwVFDbyJYj4oSnwSrdE4Fj2Wy-RhuH4AFaBUogY/edit#gid=841652337
IN-995
With this work, we add the following:
- duplicate_imports
- unused_optional_binding
- unused_setter_value
- unused_import
- yoda_condition
There are four more rules that we need to implement, which may need a discussion so will save it for the next round.
Build project and confirm that rules are enabled and no warnings associated with those rules

ci(swiftlint): Update Rules

---

PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/PocketSceneDelegate.swift
PocketKit/Sources/PocketKit/Refresh/HomeRefreshCoordinator.swift
PocketKit/Sources/PocketKit/Services.swift
PocketKit/Tests/PocketKitTests/HomeViewModelTests.swift
PocketKit/Tests/PocketKitTests/Refresh/HomeRefreshCoordinatorTests.swift
PocketKit/Tests/PocketKitTests/Support/MockHomeRefreshCoordinator.swift

Add Home Refresh Rule so that when user opens app, it does not automatically refresh unless last refresh is >= 12 hours
IN-744
Added `HomeRefreshCoordinator` that uses user defaults to capture the timestamp of a refresh. Modify `refresh` in `HomeViewModel` to use this coordinator as well. 
AND 12+ hours have elapsed since Home was last refreshed
THEN Home should automatically refresh
AND < 12 hours have elapsed since Home was last refreshed
THEN Home should not automatically refresh
AND I pull to refresh
AND 12+ hours have elapsed since Home was last refreshed
THEN Home should refresh
AND I pull to refresh
AND < 12 hours have elapsed since Home was last refreshed
THEN Home should refresh

feat(refresh): Add Home Refresh Rule [IN-744]

---

PocketKit/Sources/PocketGraph/Operations/Queries/GetSlateLineupQuery.graphql.swift
PocketKit/Sources/PocketGraph/Operations/Queries/GetSlateQuery.graphql.swift
PocketKit/Sources/Sync/Slates/SlateService.swift

Update the GraphQL schema and auto-generated code to include changes to the `getSlateLineup` and `getSlate` queries. This change made the return type of these queries non-optional, which we then had to reflect in our usage of these queries in `Sync`.
The commands (in our README) to redownload and regenerate code based on our GraphQL schema were called.

build(graphql): generate updated schema

---

UITests-2.xctestplan
UITests.xctestplan

Update test plans so that `SavesTests` and `SavesFilterTests` only run for `AllTests` plan and `UITests-3` plan
Slack convo: https://pocket.slack.com/archives/C01UH57EJKD/p1669998489687399
Remove MyList test plans and add Saves test plans where necessary
1. Navigate to test plans
2. Verify tests are located in the correct test plans 

ci(tests): update tests plans

---

PocketKit/Sources/PocketKit/Authorization/AuthorizationClient.swift
PocketKit/Sources/PocketKit/LoggedOut/LoggedOutViewModel.swift

Add Breadcrumbs to Authorization Client.
Sentry Issue: [IOS-NEXT-7C](https://sentry.io/organizations/pocket/issues/3574089481/?referrer=jira_integration)
`PocketKit.AuthorizationClient.Error: Code: 3`
IN-983
Add breadcrumbs to retrieve more details for errors. I think the error message is due to this following error, where Code: 3 refers to `presentationContextInvalid` (ignore highlight)
N / A. I don't know how to test these errors, but just verify that we receive more Information in Sentry.

fix(sentry): add breadcrumbs to authclient errors

---

PocketKit/Sources/Analytics/Context/UIContext.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/ReadableViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/RecommendationViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift
PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift
PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SortFilterMenu/SortMenuViewModel.swift
PocketKit/Sources/PocketKit/Navigation/NavigationSidebarViewController.swift

This pull request fixes various missing analytics. The following have been implemented:
- `content_open` when opening web view from the reader
- `engagement` when selecting a sort / filter option
- `content_open` when opening items from saves or archive
- `impression` when opening the navigation sidebar is opened on iPad
IN-1111

fix(analytics): implement various missing analytics

---

Pocket (iOS).entitlements
Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PocketKit/Sources/PocketKit/MyList/ArchivedItemsList/ArchivedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/PocketKit/PocketSceneDelegate.swift
PocketKit/Sources/PocketKit/Router.swift
PocketKit/Tests/PocketKitTests/RouterTests.swift

Add deep link support for saving a URL to Pocket. This only supports saving the URL as an item and not presenting it in reader or article view.
**Status:** waiting on confirmation if we can modify the AC as well as waiting for updated app association file PR to be in prod https://github.com/Pocket/dotcom-gateway/pull/93
IN-1094
Added `associated domain` in entitlements and created `Router` class to handle our deep-links. Currently, using 
`https://getpocket.com/app/read?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FDuck` instead of format in `https://getpocket.com/add?url=*` for testing purposes as the app association file is not updated.
https://getpocket.com/.well-known/apple-app-site-association
THEN the Pocket iOS app opens
AND the URL is saved to Pocket

feat(deeplinks): save url

---

Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PocketKit/Sources/PocketKit/MyList/ItemsList/SwiftUI/Components/ItemDetails.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SwiftUI/Components/ItemTags.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SwiftUI/Components/OverflowMenu.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SwiftUI/ListItem.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchItem.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchSavedItemParts+ItemsListItem.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Tests/PocketKitTests/SearchViewModelTests.swift

Display search results using SwiftUI cells. This PR purely handles the visuals and additional logic / tests to complete the search feature will be addressed in future tickets.
IN-894
Used `ItemsListItemPresenter` to hold the logic for the data we need to present the items in search view (i.e. title, detail). This presenter will be a property on `SearchItem`. By doing so, we will use `NSAttributedString` types even though we only care about strings in SwiftUI . When we move towards SwiftUI  we can replace the attributed strings with just String, but for now we can access them via `attributedString.string`. 
AND there are 1+ search results
THEN the search results display in a list
|Saves Free User|All Items Premium User|
|------|-----| …

feat(search): display search results (IN-894)

---

Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Tests iOS/MyList/SavesTests.swift

test_tappingItem_displaysNativeReaderView in SavesTests.swift has this strange behavior where it's spending a lot of extra time scrolling the Reader UI. The test isn't currently breaking but it's using a lot of extra time so I'll add this as something to look into and fix as part of the Flakey tests work.
Jira ticket https://getpocket.atlassian.net/browse/IN-950
I'm going to change how the elements are found and scrolled to in order to fix this.
The test should take much less time to complete after the changes.
Gif in Slack:
https://pocket.slack.com/archives/C01UH57EJKD/p1670535231375889

ci(tests): laggy reader test fix

---

PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Tests/PocketKitTests/SearchViewModelTests.swift
Tests iOS/Fixtures/search-list-all.json
Tests iOS/Fixtures/search-list-archive.json
Tests iOS/MyList/SearchTests.swift
Tests iOS/Support/RequestMatchers.swift
Tests iOS/Support/Response+factories.swift

Switching scopes during an active search performs a search and results are cached if already performed a search for the term. _Note: Loading state will replace current empty state in future ticket._
IN-973
Add new parameter for `updateScope` to take in search term if use switch scopes. This triggers a new search. Created new property `cachedSearchResults` to store cached results in a session and clear when user exits search experience.
AND I switch scopes
AND we have not yet performed a search for this search term and scope during this search session
THEN we perform the search (if possible)
AND I switch scopes
AND we have performed a search for this search term and scope during this search session
THEN we display the previously displayed search results
Note: show offline view if no …

feat(search): select search scopes

---

Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PocketKit/Sources/Sync/Crashlogger.swift

Sets diagnostic level to .warning to prevent excessive console logging.

project(sentry): update sentry diagnostic level

---

Package.swift
Pocket.xcodeproj/project.pbxproj
Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PocketKit/Package.swift

Update usage of Swift Package Manager to utilize exact versions instead of up to next major. This is in hopes that this helps us resolve issues with conflicting `Package.resolved` files, or repeatedly seeing file change when switching branches.
IN-1126
- Update both `Package.swift` files
- Additionally update all files to use latest APIs and Swift 5.7
- Update package(s) within Pocket project settings

project(spm): use exact dependency versions

---

PocketKit/Sources/PocketKit/MyList/EmptyStates/ArchiveEmptyStateViewModel.swift
PocketKit/Sources/PocketKit/MyList/EmptyStates/EmptyStateView.swift
PocketKit/Sources/PocketKit/MyList/EmptyStates/EmptyStateViewModel.swift
PocketKit/Sources/PocketKit/MyList/EmptyStates/FavoritesEmptyStateViewModel.swift
PocketKit/Sources/PocketKit/MyList/EmptyStates/SavesEmptyStateViewModel.swift
PocketKit/Sources/PocketKit/MyList/EmptyStates/Search/GetPremiumEmptyState.swift
PocketKit/Sources/PocketKit/MyList/EmptyStates/Search/NoResultsEmptyState.swift
PocketKit/Sources/PocketKit/MyList/EmptyStates/Search/OfflineEmptyState.swift
PocketKit/Sources/PocketKit/MyList/EmptyStates/Search/RecentSearchEmptyState.swift
PocketKit/Sources/PocketKit/MyList/EmptyStates/Search/SearchEmptyState.swift
PocketKit/Sources/PocketKit/MyList/EmptyStates/TagsEmptyStateViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/SharedPocketKit/SearchScope.swift
PocketKit/Sources/Sync/Operations/SearchService.swift
PocketKit/Tests/SyncTests/Fixtures/search-list-page-1.json
PocketKit/Tests/SyncTests/Fixtures/search-list-page-2.json
PocketKit/Tests/SyncTests/Fixtures/search-list-page-3.json
PocketKit/Tests/SyncTests/Support/PocketSearchServiceTests.swift
Tests iOS/MyList/SearchTests.swift

This PR consist of work related to 3 tickets:
* Support pagination for online search results
* Copy updates for Search Flow
* User can cancel searching
IN-993, IN-1089, IN-968
Small changes in terms of updating string values for the various empty states, modify pagesize constant to use `30` or `50` depending on device size and clear search field when user cancels search.
[ ] For small devices, like phone, this should be 30 items per page. 
[ ] For large devices, like iPads, this should be 50 items per page. 
AND the user taps the cancel button
THEN the search experience is closed
AND the user is returned to where they were before activating search (e.g., saved or archived)
AND any active searches are cancelled

feat(search): support pagination, copy updates, cancel search

---

PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/LocalSavesSearch.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/OnlineSearch.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/Sync/Operations/SearchService.swift
PocketKit/Tests/PocketKitTests/Search/OnlineSearchTests.swift
PocketKit/Tests/PocketKitTests/Search/SavesLocalSearchTests.swift
PocketKit/Tests/PocketKitTests/Search/SearchViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockSearchService.swift
PocketKit/Tests/SyncTests/PocketSourceTests.swift
Tests iOS/MyList/SearchTests.swift

Fix issue where switching search scopes too quickly causes wrong results due to caching the results for the wrong scope
IN-1127
Previously, we were using two types of search (online, local) with one cache. We learned that this was a data issue in terms of how we were setting cached results and updating search results. From the meeting, we decided it was best to follow the [SOLID principles](https://www.freecodecamp.org/news/solid-principles-explained-in-plain-english/) and create four different instances that act as containers for the 4 search types (local saves, online saves, online archive, online all items). Each container will have its own cache and this will avoid the issue of having results from one scope appear in another. Overall, this decouples each scope from one another.
1. Go …

fix(search): fix caching issues with switching scopes

---

PocketKit/Sources/Sync/Operations/FetchList.swift

Add more breadcrumbs to gain better insight on the following issue: 
Sentry Issue: [IOS-NEXT-9C](https://sentry.io/organizations/pocket/issues/3702278188/?referrer=jira_integration)
`Retriable operation "Sync.FetchList" exceeded maximum number of retries`
IN-988
Added breadcrumbs with details after checking where `retry` is being called and what error cases can trigger it
N / A. I don't know how to test these errors, but seems we'll rely on verifying that we receive more Information in Sentry.

fix(sentry): add breadcrumbs for FetchList errors

---

PocketKit/Sources/PocketKit/Banner/BottomNotification.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift

show banner for offline notification on saves
* when the user is offline during a saves search, a banner will show if the user is premium and offline
*  [IN-1067](https://getpocket.atlassian.net/jira/software/projects/IN/boards/80?selectedIssue=IN-1067)
* added new notification banner in swift UI
* if the user is offline and premium, a banner show show
[IN-1067]: https://getpocket.atlassian.net/browse/IN-1067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(search): saved search offline notification

---

PocketKit/Sources/PocketKit/Banner/BottomNotification.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/OnlineSearch.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/Sync/Operations/SearchService.swift
PocketKit/Tests/PocketKitTests/Search/OnlineSearchTests.swift
PocketKit/Tests/PocketKitTests/Search/SearchViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockSearchService.swift
PocketKit/Tests/PocketKitTests/Support/TestError.swift
PocketKit/Tests/SyncTests/Support/PocketSearchServiceTests.swift

An online search of saves that fails because for network reasons or other errors is resubmitted as an offline search
IN-971
Converted the `search` function to throw an error if it encounters one in `PocketSearchService` . We pass this error on in our OnlineSearch class and we use the `Result` type to return whether the search failed or succeeded. If there is a failure, then run local search for saves only in our `SearchViewModel`. Updated UI banner with some refinements to match Figma and figured out bug with animation in SwiftUI as we needed to specific zIndex(-1).
AND the network connection is active
AND the connection fails
THEN re-submit the search query as a search of local data
AND display the offline search message (banner)

feat(search): search locally for saves if online fails

---

Tests iOS/AddTagsItemTests.swift
Tests iOS/MyList/SavesTests.swift
Tests iOS/SaveToPocketTests.swift
Tests iOS/Support/Elements/AddTagsViewElement.swift

Tracking these 3 flakey tests and attempting to fix:
test_navigatingToHomeTab_withClipboardURL_showsBannerAndSavedItem()
test_addTagsToItemFromSaves_savesNewTags()
test_userAddTags_showsConfirmationView
test_addTagsToItemFromSaves_savesNewTags()
--> I changed the way this test is written, it was performing an unnecessary check of the tag name directly after entry, which was the failing line, the tag name is rechecked later in the test so it's not removing any coverage
test_userAddTags_showsConfirmationView
The original author of this test put in a comment that this would be brittle and flakey.
--> I tried a few different approaches to try and avoid the error message causing the test to break, it's just an Xcode thing as far as I can tell... for this fix I removed the portion of the test …

ci(tests): fixes for flakey tags tests

---

Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/PocketKit/Resources/en.lproj/Localizable.strings
PocketKit/Tests/PocketKitTests/Search/SearchViewModelTests.swift
Tests iOS/MyList/SavesTests.swift
Tests iOS/SaveToPocketTests.swift
Tests iOS/Support/Elements/AddTagsViewElement.swift

* Handles offline user scenario when the user navigates to the search experience before submitting search
* Also refactors how we were managing state for our `SearchView`
IN-962
Refactor how we were presenting the different states of the `SearchView`. Instead of managing three separate objects, I decided to create a single enum object called `SearchViewState` that can set which view should be shown and the associated values that will be used in presenting the details of the view. Added some logic of checking if the user is offline + show the offline view when they enter the search experience in `freeEmptyState` and `premiumEmptyState ` 
**For premium user:**
AND the device is offline
THEN show the recent searches view
**For premium and free user:**
AND the device is offline
THEN show a …

feat(search): offline users cannot search archive

---

Tests iOS/HomeTests.swift
Tests iOS/ReportARecommendationTests.swift
Tests iOS/Support/Elements/HomeViewElement.swift
Tests iOS/Support/Elements/ReaderElement.swift

I'm going to add a few more Home tests to the existing set.
Review of the Android Home regression tests, and bringing in missing tests on the iOS side.
Adding:
test_returningFromSaves_maintainsHomePosition
test_returningFromSettings_maintainsHomePosition
test_returningFromReader_maintainsHomePosition
test_returningFromSeeAll_maintainsHomePosition

ci(tests):a few more home tests

---

PocketKit/Sources/PocketKit/MyList/SearchItemsList/OnlineSearch.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/Sync/Operations/SearchService.swift
PocketKit/Tests/PocketKitTests/Search/SearchViewModelTests.swift
Tests iOS/HomeTests.swift
Tests iOS/Support/Elements/AddTagsViewElement.swift
Tests iOS/Support/Elements/HomeViewElement.swift
Tests iOS/Support/Elements/ReaderElement.swift

An online search of Archive or All Items that fails because of network connection problems presents a message
IN-974
Separated our logic for receiving results from the `OnlineSearch` into their own private functions for `saves`, `archive` and `all items`. Added error type `SearchServiceError` to specify when there was an internet connection issue. This error gets passed on from `SearchService` to `OnlineSearch` to `SearchViewModel` and we set the view to the offline empty state when this error is received. The error is determined to be `noInternet` if Apollo returns an error of `URLSessionClient.URLSessionClientError.networkError` with code `-1009`. Also, fixed a couple of bugs found when trigger a new search or switching scopes by making modifications to `clear` and `resetSearch`
AND the …

feat(search): online search that fails on network presents offline view

---

PocketKit/Sources/PocketKit/MyList/ItemsList/ItemSkeletonCell.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewController.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/OnlineSearch.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SkeletonView.swift
PocketKit/Tests/PocketKitTests/Search/OnlineSearchTests.swift
PocketKit/Tests/PocketKitTests/Search/SearchViewModelTests.swift
Tests iOS/MyList/SearchTests.swift
Tests iOS/Support/Elements/SearchViewElement.swift

Present loading state while (online) search is in-progress
IN-992
Created a SwiftUI view called `SkeletonView`. This view uses our already existing image assets that we are using in our other skeleton cells (`ItemPlaceholderCell` and `ReaderSkeletonCell`). There is another view called `SkeletonListView`, which uses SwiftUI’s redacted modifier on dummy data, which can act as a loading screen. Although I prefer the `SkeletonListView` as it is a more accurate representation of the data, to maintain consistency, we are using `Skeleton View`. Also, created another `searchState` called `.loading` that shows us the SkeletonView . Had to also add `hasCache` to make sure that we are resetting the search and show loading screen for a new search.
AND the user submits a search query
AND it is …

feat(search): search loading state

---

Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PocketKit/Sources/PocketKit/Premium/PremiumUpgradeView.swift

* Adding Privacy Policy and ToS links
* [IN-1051](https://getpocket.atlassian.net/browse/IN-1051)
* added Safari View to allow users to stay on current stack of screens
* As a free user, go to settings
* select "Go Premium"
* Click on "Privacy Policy" and/or "Terms of Services"
[IN-1051]: https://getpocket.atlassian.net/browse/IN-1051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(premium): tos and privacy links

---

Info.plist
Pocket.xcodeproj/project.pbxproj
PocketKit/Sources/PocketKit/Keys.swift
PocketKit/Sources/PocketKit/Premium/Model/PremiumSubscription.swift
PocketKit/Sources/PocketKit/Premium/Model/PremiumSubscriptionStore.swift
PocketKit/Sources/PocketKit/Premium/View/PremiumUpgradeView.swift
PocketKit/Sources/PocketKit/Premium/ViewModel/PremiumUpgradeViewModel.swift
PocketKit/Sources/PocketKit/Settings/AccountViewModel.swift
PocketKit/Sources/PocketKit/Settings/SettingsView.swift
PocketKit/Sources/SharedPocketKit/User.swift
PocketKit/Tests/SyncTests/Support/MockUser.swift

* This PR adds the capability of reading subscription prices from the App Store
* Update `Info.plist` and `Keys.swift` with subscription Id keys
* Add `PremiumSubscription`, `PremiumSubscriptionStore` and `PremiumUpgradeViewModel` types
* Update `AccountViewModel` and `SettingsView` to inject the view model (and the store) into `PremiumUpgradeViewModel`
* Update `PremiumUpgradeView` to use the view model 
> **Note**
- `StoreKit` will cache the products for short periods of time. So, if you dismiss the Premium Membership screen and then re-open it, you might see names and prices right away instead of the skeletons. This is normal
- This PR only deals with fetching subscriptions from the App Store. Purchasing and cancellation flows will be handled in future PRs
* checkout, build and run …

Premium Subscriptions: read subscriptions from the App Store

---

PocketKit/Sources/PocketKit/Notifications/InstantSync.swift

* include breadcrumbs for sentry review to understand why its crashing
* Added two new breadcrumb trackers around Instant Sync
*N/A

feat(sentry): breadcrumbs for sync registration

---

Tests iOS/AddTagsItemTests.swift
Tests iOS/Fixtures/hello2.html
Tests iOS/ReaderTests.swift

Fixes for a number of small-fail flaky tests.
I've made two attempts at changing the tests so that they don't flaky fail (time will tell if these changes are effective at preventing the flaky fails):
**Tags**: I changed this test so it opens the All Tags view instead of the item tag, to check that the save function worked
**Hyperlink**: I changed this test to long press a different hyperlink in a different item
Tracking the fail rate via Bitise graph tracking.

ci(tests): hyperlink+tags tests flaky fix

---

.gitignore
Info.plist
Pocket.xcodeproj/project.pbxproj
PocketKit/Sources/PocketKit/Keys.swift
PocketKit/Sources/PocketKit/Premium/Model/PremiumSubscription.swift
PocketKit/Sources/PocketKit/Premium/View/PremiumUpgradeView.swift
PocketKit/Sources/PocketKit/Premium/ViewModel/PremiumUpgradeViewModel.swift
PocketKit/Sources/PocketKit/Resources/en.lproj/Localizable.strings
PocketKit/Sources/PocketKit/Strings.swift

* This pull request replaces the placeholder TBD prices in the description at the bottom of the Premium Upgrade view with the actual subscription prices.
* Adds the description at the bottom of `PremiumUpgradeView` to `Localizable.strings` and, by means of `SwiftGen`, to `Strings.swift`
* Uses localized names and descriptions for the upgrade buttons in `PremiumUpgradeView`
* Updates `.gitignore` to allow usage of separate `.xcconfig` files for separate configuration (will be useful for StoreKit tests)
* Shorten key names for subscriptions in `Keys` and `Info.plist`
* Checkout, build and run this branch
* Log in with a free account
* Tap Settings, then Go Premium
* Make sure that the description at the bottom reflect the same subscription …

Premium Subscriptions - minor tweaks to Premium Upgrade Screen

---

Tests iOS/HomeTests.swift

A recent saves test was not validating the test expectation correctly, this PR will fix it.
I'm scrolling past an actual item in the recent saves list with this change, if it causes flaky fails I'll revert the changes or make the test more robust.

ci(tests): small fix for a recent saves test

---

PocketKit/Sources/PocketKit/Resources/en.lproj/Localizable.strings
PocketKit/Sources/PocketKit/Settings/Components/SettingsRowButton.swift
PocketKit/Sources/PocketKit/Settings/SettingsView.swift
PocketKit/Sources/PocketKit/Strings.swift

* This PR fixes the divider alignment and the image color in dark mode of the "Go Premium" row in the Settings screen
* Applies `.listRowSeparatorLeading` for the premium row for iOS 16
* Minor changes to `SettingsButton` so that it can use a `SettingsButtonImage`,  formatted with passed asset and color
* Uses `black1` for the premium row icons
* Localizes "Go Premium"
* Checkout, build and run this branch
* Tap Settings
* Make sure the divider between Go Premium and Sign Out looks consistent with all the others in that same screen
* Switch to dark mode, and make sure the icons (diamond and chevron right) look right
See screenshots for more details
before | after
-- | --
before | after
-- | --

Settings Premium Row - Fix divider alignment and Image colors in dark mode

---

Tests iOS/AddTagsItemTests.swift

test_addTagsToItemFromSaves_savesNewTags is still exhibiting some flaky fail issues. This PR is the next iteration of an attempt to fix these fails.
I'm changing the way a new tag is validated after being saved. Previously we were checking for the tag name, I'm changing it to a simple index count check in the edit tags list for verification.

ci(tests): next iteration of tags test fix

---

PocketKit/Sources/PocketKit/Services.swift
PocketKit/Sources/SaveToPocketKit/Services.swift
PocketKit/Sources/Sync/PersistentContainer.swift
PocketKit/Tests/SyncTests/Support/Space+factories.swift
Tests iOS/HomeTests.swift
Tests iOS/ReportARecommendationTests.swift
Tests iOS/Support/LaunchArguments.swift

Ensure that the tests do not try and wipe the core data db after it has been seeded already. Introduced in https://github.com/Pocket/pocket-ios/pull/414
* Also fixed some swiftlint issues..

fix(user-defaults): setting user defaults to not wipe db

---

PocketKit/Sources/Analytics/AppEvents/Search.swift
PocketKit/Sources/Analytics/Entities/UserEntity.swift
PocketKit/Sources/Analytics/Tracker/LinkedTracker.swift
PocketKit/Sources/Analytics/Tracker/NoopTracker.swift
PocketKit/Sources/Analytics/Tracker/PocketTracker.swift
PocketKit/Sources/Analytics/Tracker/Tracker.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/PocketItem.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/PocketItemViewModel.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SwiftUI/Components/ActionButton.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SwiftUI/ListItem.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SwiftUI/Styles/ActionButtonStyles.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/LocalSavesSearch.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/OnlineSearch.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/PocketKit/Root/RootViewModel.swift
PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewModel.swift
PocketKit/Sources/Sync/PersistentContainer.swift
PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Tests/AnalyticsTests/LinkedTrackerTests.swift
PocketKit/Tests/AnalyticsTests/Support/Mocks.swift
PocketKit/Tests/PocketKitTests/Search/PocketItemViewModel.swift
PocketKit/Tests/PocketKitTests/Search/SavesLocalSearchTests.swift
PocketKit/Tests/PocketKitTests/Support/MockTracker.swift
PocketKit/Tests/SaveToPocketKitTests/Support/MockTracker.swift
PocketKit/Tests/SyncTests/Support/Space+factories.swift
Tests iOS/HomeTests.swift
Tests iOS/MyList/SearchTests.swift
Tests iOS/Support/Elements/SearchViewElement.swift

PR adds functionality to favorite search result items
IN-1121
* Create `PocketItemViewModel` to hold the logic of favoriting items. Similar to existing logic except we have to create a savedItem from remote data. 
* Rename `SearchItem` to `PocketItem` to be more reusuable
* Fixed bug related to new use of entities for analytics. We were using old context from APIUser and User, so created new `persistentEntities` object.
AND a search has been performed
AND there are 1+ results
AND search results are visible
THEN every search result includes a favorite button
THEN the search result favorite button is filled
THEN the search result favorite button is not filled
AND the search result has already been favorited
THEN the search result will be unfavorited
AND the search result button will not be …

feat(search): favorite search results

---

PocketKit/Sources/PocketGraph/Fragments/ItemSummary.graphql.swift
PocketKit/Sources/PocketGraph/Operations/Queries/SearchSavedItemsQuery.graphql.swift
PocketKit/Sources/PocketGraph/Schema/Enums/SearchItemsSortBy.graphql.swift
PocketKit/Sources/PocketGraph/Schema/Enums/SearchItemsSortOrder.graphql.swift
PocketKit/Sources/PocketGraph/Schema/InputObjects/SearchSortInput.graphql.swift
PocketKit/Sources/PocketGraph/Schema/Objects/Tag.graphql.swift
PocketKit/Sources/PocketGraph/user-defined-operations/list.graphql
PocketKit/Sources/Sync/Operations/SearchService.swift

When validating the Search work I noticed that my results were not matching Web no matter what I did. It turns out that after talking to @collectedmind, Web utilizes a sort order which changes your default result set. 
This brings us in line with them.
Long term we should align with @collectedmind and a search product partner to align all clients.

feat(search): matching web default sort order

---

bitrise.yml

We are facing inconsistencies with our tests failing in CI intermittently and between our local machines. This level sets us by making our CI use M1 Max instead of intel to ensure that we are running on the same machine instruction sets.

fix(m1): moving ci to M1 Max

---

Tests iOS/MyList/EmptyStateTests.swift

This is a small fix for a flaky fail of an empty state test for Favorites, we were doing an extra check on 0 items being present however this is unnecessary because there is already a check for the empty state message.

ci(tests): small fix for empty state favorites test

---

PocketKit/Sources/Textile/Style/Style.swift
PocketKit/Tests/PocketKitTests/Search/SearchViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockUser.swift
PocketKit/Tests/SyncTests/PocketSourceTests.swift
PocketKit/Tests/SyncTests/Support/MockUser.swift

* This PR fixes a few unit test that were failing after refactoring `User`
* Update `MockUser`, both locations, add a method that stubs the "standard" setStatus, and use that method to allow setting the premium status calling `setPremiumStatus( _:), since it's not possible to change `status` directly.
* Run all unit tests and make sure they pass

Fix unit tests that failed after refactoring User

---

PocketKit/Sources/Analytics/AppEvents/Search.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/PocketItemViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
Tests iOS/MyList/SearchTests.swift
Tests iOS/Support/SnowplowMicro.swift

PR to add tracking for search: 
**Three engagement events:**
- Opening Search View
- Performing a Search 
- Changing the scope
**One impression event:**
- Viewing Search Results
**One content_open event:**
- Opening a Search Result
IN-1106
* Added comments to Search tracking events (pulled from Analytics spreadsheet)
* Added 5 events described above in `Search` and created tracking methods in `SearchViewModel` to trigger those events
* Used snowplow micro ui testing
* Run through the UI tests as well as verified the calls are being triggered appropriately for each event

feat(search): analytics

---

PocketKit/Sources/PocketKit/MyList/EmptyStates/EmptyStateView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/PocketKit/PocketSceneDelegate.swift
PocketKit/Sources/PocketKit/Style/GetPocketPremiumButtonStyle.swift

* This PR adds logic to update the app UI when the user successfully purchases a premium subscription
* Inject `PremiumViewModel` factory into `SarchViewModel`, so we can instantiate `PremiumUpgradeView` when needed
* `SearchViewModel` now listens to user status changes, to update the UI accordingly
* `EmptyStateView` now accepts an alternate external view that can be used in place of the standard button, so that we are not limited to a button that calls a web view anymore
* `GetPocketPremiumButton` is a button that presents `PocketPremiumView`, used in `EmptyStateView`, online search, free users
Pre-requisite:
- configure the `StoreKit` testing environment using the steps described in #421 on this branch
Testing steps (see animation below):
- Once the prerequisites are implemented, build …

Premium Subscriptions: Update UI after user purchases a subscription

---

PocketKit/Sources/PocketKit/Resources/en.lproj/Localizable.strings
PocketKit/Sources/PocketKit/Settings/AccountViewModel.swift
PocketKit/Sources/PocketKit/Settings/Components/SettingsRowButton.swift
PocketKit/Sources/PocketKit/Settings/SettingsView.swift
PocketKit/Sources/PocketKit/Strings.swift

*This PR changes the premium row in "Settings" after a user has successfully purchased a premium subscription. The description will change from Go Premium to Premium Subscription, and the tint color from `black1` to `teal2`
* Update `SettingsRowButton` to allow color configuration of title and icons
* Update `AccountViewModel` to listen to `User.status` changes as they happen
* Update `Localizable.strings`, add `settings.premiumSubscriptionRow` string
Pre-requisite:
- checkout this branch and setup `StoreKit` testing as described in #421 
Testing steps (see animation below):
- build/run
- login with a free account
- go to the "Settings" tab
-  tap "Go Premium"
- Make sure the premium upgrade screen appears
- Purchase a subscription
- Tap "OK" in the "You're all set" alert
- Make sure the …

Premium Subscriptions: Premium Subscription Row

---

PocketKit/Sources/PocketKit/Main/RegularMainCoordinator.swift

Fix Archive button (and Delete) in Reader as it was not popping to home view controller
IN-949
Similar to how we handle clicking "Done" on Web View, we want to dismiss the article and bring the user back to Home. Archive and Delete both utilize this presentation logic, so applied it to both.
1. Nav to Saves > Reader on iPad
2. Click Archive 
3. Verify that the item goes away and the user is brought to home view
https://user-images.githubusercontent.com/6743397/222240914-7f37e504-4991-4857-af3a-567a4ee93df3.mp4

fix(reader): trigger pop to root after archiving or deleting from reader

---

Pocket.xcodeproj/project.pbxproj
Pocket.xcodeproj/xcshareddata/xcschemes/Pocket (iOS).xcscheme
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/PocketKit/Premium/Model/PremiumSubscription.swift
PocketKit/Sources/PocketKit/Premium/Model/PremiumSubscriptionStore.swift
PocketKit/Sources/PocketKit/Premium/Model/SubscriptionStore.swift
PocketKit/Sources/PocketKit/Premium/View/PremiumUpgradeView.swift
PocketKit/Sources/PocketKit/Premium/ViewModel/PremiumUpgradeViewModel.swift
PocketKit/Sources/PocketKit/Services.swift
PocketKit/Sources/SharedPocketKit/User.swift
PocketKit/Tests/PocketKitTests/Search/SearchViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockUser.swift
PocketKit/Tests/SyncTests/Support/MockUser.swift

* This PR fixes some unit tests and improves general testability by adding a `SubscriptionStore` protocol
* Add `protocol SubscriptionStore`, a generic subscription store. `PocketSubscriptionStore` is the concrete implementation that handles subscription purchase and retrieval from the App Store.
* Refactor `SearchViewModelTests`
* Checkout this branch
* Run all unit tests and make sure they pass
* Build and run the app and make sure the purchase flow described in #437 and #421 works as expected
> **Warning**
The same limitations to the purchase flow, as in #421 apply here: testing between launches won't provide reliable results as of now, because we are not syncing the purchase with the backend. If you want to re-test after relaunching, you should delete existing transactions from the …

Fix test build failing

---

PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/PocketKit/Settings/SettingsView.swift

This PR fixes some UI tests that broke in develop.
Related to: https://github.com/Pocket/pocket-ios/pull/446
* Update accessibility identifier for `SignOutTests`
* Add back analytics call for `SearchTests`
* Checkout this branch
* Run all UI tests and make sure they pass in test suite 3

fix(tests): fix ui test suite 3

---

PocketKit/Sources/Analytics/AppEvents/Premium.swift
PocketKit/Sources/Analytics/AppEvents/Search.swift
PocketKit/Sources/Analytics/AppEvents/Settings.swift
PocketKit/Sources/Analytics/Events/Impression.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/PocketKit/PocketSceneDelegate.swift
PocketKit/Sources/PocketKit/Premium/Model/PocketSubscriptionStore.swift
PocketKit/Sources/PocketKit/Premium/Model/PremiumSubscription.swift
PocketKit/Sources/PocketKit/Premium/Model/SubscriptionStore.swift
PocketKit/Sources/PocketKit/Premium/View/PremiumUpgradeView.swift
PocketKit/Sources/PocketKit/Premium/ViewModel/PremiumUpgradeViewModel.swift
PocketKit/Sources/PocketKit/Settings/AccountViewModel.swift
PocketKit/Sources/PocketKit/Settings/SettingsView.swift
PocketKit/Sources/SharedPocketKit/DismissReason.swift
PocketKit/Sources/SharedPocketKit/PremiumSubscriptionType.swift
PocketKit/Sources/SharedPocketKit/PremiumUpgradeSource.swift
PocketKit/Tests/PocketKitTests/Search/SearchViewModelTests.swift

* This PR adds the analytics events associated with premium upsell and premium purchases.
* Add `Events.Premium` type, with a variety of premium purchases events
* Add `premiumUpsellViewed` event in `Events.Search`
* Add `Events.Settings` type with a `premiumUpsellViewed` event
* Refactor `SubscriptionStore`, `PocketSubscriptionStore`, add a `state` property to publish `PurchaseState`
* Update views and view models to track the added events
* Checkout this branch
* To test subscription purchase events, setup the environment as indicated in #421 
* Build/run
* Login with a free account
* Execute the following actions, and make sure the related events show up in the console
* Go to Saves > Search
* Go to All Items - Event `global-nav.search.premium.upsell`
* Go to Settings - Event …

Premium - Analytics

---

PocketKit/Sources/Analytics/AppEvents/Search.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/PocketItem.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/PocketItemViewModel.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SwiftUI/Components/OverflowMenu.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SwiftUI/ListItem.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/ItemsListItem.swift
PocketKit/Sources/PocketKit/MyList/SavedItemsList/SavedItem+ItemsListItem.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchSavedItem+ItemsListItem.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/Sync/Requests.swift
PocketKit/Tests/PocketKitTests/Search/PocketItemViewModel.swift
PocketKit/Tests/PocketKitTests/Search/SearchViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockItemsListItem.swift
Tests iOS/MyList/SearchTests.swift
Tests iOS/Support/Elements/ItemRowElement.swift

User can activate result overflow button
IN-1123
* Create new `OverflowMenu` view for overflow actions (add tags, archive/unarchive and delete). 
* Added `SavedItemsController` so that `SearchViewModel` can observe changes from core data
* Added 5 new search analytic actions
Note: Some issues may still exist and will be done in future tickets
* All Items have both Saves and Archive (archive and deleting is weird for this case) - I would like to discuss with the team on how to handle this and vote a new ticket to be created.
* Resubmitting search after performing an action will cause some inconsistencies in the search result view - ticket for edge case
AND a search has been performed
AND there are 1+ results
AND search results are visible
THEN every search result includes an overflow …

feat(search): add overflow menu

---

Tests iOS/ReaderTests.swift

This PR adds a .wait() to a safari opening method, which is an attempt to fix a flaky fail rate of about 1% for test_tappingWebViewButton_showsSafari

ci(tests): Safari open flaky fix

---

PocketKit/Sources/PocketKit/Premium/Model/PocketSubscriptionStore.swift
PocketKit/Sources/PocketKit/Premium/Model/PremiumSubscription.swift
PocketKit/Sources/PocketKit/Premium/Model/SubscriptionStore.swift
PocketKit/Tests/PocketKitTests/Search/SearchViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockSubscriptionStore.swift

* This PR adds a direct call to purchase sync to `SubscriptionStore`, for those rare cases where the automatic sync does not happen
* Add a `restoreSubscription` call to `SubscriptionStore`, which corresponds to an `Appstore.sync()` call in the concrete implementation `PocketSubscriptionStore`
* There's not much to test at the moment; here is the [documentation](https://developer.apple.com/documentation/storekit/appstore/3791906-sync) related to that call which, according to Apple, will only be needed in rare cases. When the call happens, the listener in place should receive existing transactions and entitlements.

Add manual purchase sync to SubscriptionStore

---

Pocket.xcodeproj/project.pbxproj
Pocket.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
PocketKit/Sources/Analytics/AppEvents/Premium.swift
PocketKit/Sources/Analytics/Events/Impression.swift
PocketKit/Sources/PocketKit/MyList/EmptyStates/EmptyStateView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/Premium/View/PremiumUpgradeView.swift
PocketKit/Sources/PocketKit/Settings/SettingsView.swift
Tests iOS/PremiumTests.swift
Tests iOS/Support/Elements/PocketAppElement.swift
Tests iOS/Support/Elements/PremiumUpgradeViewElement.swift
Tests iOS/Support/Elements/SearchGetPremiumEmptyViewElement.swift
Tests iOS/Support/Elements/SettingsViewElement.swift
UITests-3.xctestplan
UITests.xctestplan

* This PR adds UI tests for Premium Upgrade
> **Note**
There are no failing tests at this moment because setting `failTransactionsEnabled` in `SKTestSession` did not seem to produce the effect of a failed transaction in the store, more investigation to come.
* Add accessibility identifiers to `PremiumUpgradeView` and subviews
* Add `PremiumTests` to UI test suite
* Checkout this branch
* Run snowplow micro locally
* Run the UI tests and make sure they succeed
NA

Premium Upgrade View - UI Tests

---

PocketKit/Sources/PocketKit/PocketSceneDelegate.swift
PocketKit/Sources/PocketKit/Premium/Model/PocketSubscriptionStore.swift
PocketKit/Sources/PocketKit/Resources/en.lproj/Localizable.strings
PocketKit/Sources/PocketKit/Settings/AccountManagementView.swift
PocketKit/Sources/PocketKit/Settings/AccountViewModel.swift
PocketKit/Sources/PocketKit/Strings.swift

* This PR adds the option to manually restore a subscription in those "rare" (according to Apple) cases where the automatic restore won't work
* Update `PocketSubscriptionStore`, add explicit entitlements resync after `Appstore.sync()`
* Update `AccountViewModel`, add logic to request a restore and handle its result
* Update `AccountManagementView`, add "Restore Existing Subscription" button and alerts for success and failure
- checkout this branch and configure your environment to use the `StoreKit` configuration file, as described in #421 
* Build/run and login with a free account
* Tap Settings > Go Premium, then purchase a subscription
* Stop the execution
* Comment out [this line](https://github.com/Pocket/pocket-ios/blob/b20497956cf16a4d7ede122a5adc0229c4581bd6/PocketKit/Sources/Pock …

Premium - Restore Subscription Manually

---

PocketKit/Sources/PocketKit/Settings/AccountManagementView.swift
PocketKit/Sources/PocketKit/Settings/AccountViewModel.swift
PocketKit/Sources/PocketKit/Settings/DeleteAccountView.swift
PocketKit/Sources/PocketKit/Settings/DeleteAccountViewModel.swift
PocketKit/Sources/PocketKit/SwiftUIPreviewSupport/PreviewTypes.swift

* This PR does a small refactor to extract view model logic related to account deletion from `AccountViewModel` to `DeleteAccountViewModel`
* Add `DeleteAccountViewModel`
* Add `PreviewTypes`, a collection of types to be used in static SwiftUI previews instead of the production types
* Build/run, go through the account deletion flow and make sure it works as expected

Add DeleteAccountViewModel

---

PocketKit/Sources/Analytics/AppEvents/Search.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/PocketItem.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/ItemsListItem.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItem+ItemsListItem.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/OnlineSearch.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/Sync/Operations/SearchService.swift
PocketKit/Tests/PocketKitTests/Search/OnlineSearchTests.swift
PocketKit/Tests/PocketKitTests/Search/SearchViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockItemsListItem.swift
PocketKit/Tests/PocketKitTests/Support/MockSearchService.swift
PocketKit/Tests/SyncTests/Support/PocketSearchServiceTests.swift
Tests iOS/Fixtures/search-list-page-1.json
Tests iOS/Fixtures/search-list-page-2.json
Tests iOS/MyList/SearchTests.swift
Tests iOS/Support/Elements/SearchViewElement.swift
Tests iOS/Support/Response+factories.swift

PR to fix issues where share sheet was dismissing due to triggering pagination for search results when not needed.
IN-1187
* Modified `SearchService` to only call once unless the user scrolls down the list. After the initial search call and the user scrolls down the list, I will check if the `pageInfo` from GraphQL response has `hasNextPage == true` and also create a variable `lastEndCursor` that gets hold by the service until the user submits another search or cancels search. 
* Created function `loadMoreResults` to trigger the next page call after a certain index has been reached in the list. This is an arbitrary constant that fits for both iPad and iPhone.
Verify that all search functionality exists and works properly
**Confirm Bug Fix**
1. Navigate to Search and submit a search for a …

fix(search): refactor search pagination

---

PocketKit/Sources/Textile/Views/Tags/AddTagsView.swift

Force lowercase on tag text input field for tags creation / add tags screen.
IN-1135
Added `autocapitalization` and set it to `none` to avoid capitalizing the first letter. Modified binding to force lowercase no matter what the user inputs. This accounts for cases if the user uses CapLocks or Shift.
AND I select the text field to input text
AND I type
THEN all text should be forced lowercase
Although you may not see it, I am attempting to enter capitalized characters.
https://user-images.githubusercontent.com/6743397/224404186-a49b7318-10b5-46e6-90f5-498c53b744ae.mp4

feat(tags): force lowercase on tag text input field

---

PocketKit/Sources/PocketKit/PremiumUpgrade/Model/PocketSubscriptionStore.swift
PocketKit/Sources/PocketKit/PremiumUpgrade/Model/ReceiptService.swift
PocketKit/Sources/PocketKit/PremiumUpgrade/View/PremiumUpgradeView.swift
PocketKit/Sources/PocketKit/Services.swift
PocketKit/Sources/Sync/V3/V3Client.swift
PocketKit/Sources/Sync/V3/V3ClientProtocol.swift
PocketKit/Sources/Sync/V3/V3RequestTypes.swift
PocketKit/Tests/PocketKitTests/Support/MockV3Client.swift

* This PR adds code to send the App Store receipt to the backend. The receipt is sent in two occasions:
- at app launch, as a fail-safe in case the local listener does not receive existing entitlements
- at every successful transaction
> **Note**
at this moment, the receipt is not sent when building for debug.
- This PR also does some small refactor to the existing V3 client and enables the premium purchases flag
* Add `ReceiptService` and concrete implementation `AppStoreReceiptService`
* Update `PocketSubscriptionStore`, send the receipt when needed (see above)
* Update `V3Client`, add calls to send the App Store receipt, some minor refactor
* This code is not really testable at the moment from Xcode. You can still run the tests to make sure nothing broke.

Premium Purchases - Send App Store receipt to the backend

---

PocketKit/Sources/PocketKit/PremiumUpgrade/Model/PocketSubscriptionStore.swift
PocketKit/Sources/PocketKit/PremiumUpgrade/Model/ReceiptService.swift
PocketKit/Sources/PocketKit/Services.swift

* This PR does a little bit of refactor to `PocketSubscriptionStore`, optimizing code and logging.
* Changes to `PocketSubscriptionStore`
* Checkout this brand
* Configure `StoreKit` testing as described in #421, alternatively, use an Appstore sandbox user (contact me if you don't have one)
* Login with a free account
* tap Go Premium and make sure that the purchase flow completes successfully

Premium purchases - Subscription store refactor

---

bitrise.yml

Our UI tests seem to hang at times, or fail on on the lower end machines. Particularly with tests that interact with the System (Safari, Custom Actions). This bumps the machine size for the UI tests and adds a timeout.

fix(bitrise): build stack changes

---

PocketKit/Sources/PocketKit/PremiumUpgrade/Model/PocketSubscriptionStore.swift
PocketKit/Sources/PocketKit/PremiumUpgrade/Model/ReceiptService.swift

* This PR removes the url encoding from the App Store receipt. It also optimizes the code that sends the receipt out, only sending a "restore" receipt type to the backend if no purchased product was found (in which case a "purchase" type will be sent)
* Update `AppStoreReceiptService`, remove url encoding from the receipt
* Update `PocketSubscriptionService`, send the restore request to the backend only if no active product was found.
* There's not much manual testing here.

feat(premium): update receipt encoding

---

PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewController.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/Sync/SavedItemsController.swift
PocketKit/Tests/PocketKitTests/SavedItemsListViewModelTests.swift
PocketKit/Tests/PocketKitTests/Search/SearchViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockSource.swift
PocketKit/Tests/PocketKitTests/Support/PersistentContainer+testContainer.swift
PocketKit/Tests/SyncTests/PocketSourceTests.swift
PocketKit/Tests/SyncTests/Support/TestSavedItemsControllerDelegate.swift

Attempt to solve our biggest crash in testflight by ensuring that our SavedItemsListModel only updates its data via the DiffableDataSource delegate callback from NSFetchedResultsController. 
Before we were updating our snapshot in various places within the SavedItemsViewModel and sometimes before data was fully available for our View. This ensures that when we add/update/remove a save from our Snapshot, that request to do so came straight from our NSFetchedResultsController. Because it comes straight from NSFetchedResultsController we can expect the data to exist and not cause a crash down the line.
* Ensure saves load normally.
I was able to reproduce the Crash pictured above by logging into my account and then scrolling very quickly down my saves lists.

feat(saves): update saves use NSFetchedResults diffable datasource delegate

---

PocketKit/Sources/PocketKit/Home/SlateDetailViewController.swift
PocketKit/Sources/Sync/SyncConstants.swift
PocketKit/Tests/SyncTests/APISlateServiceTests.swift
Tests iOS/Fixtures/slates.json
Tests iOS/HomeTests.swift
Tests iOS/ReportARecommendationTests.swift

Ensure that recommendations do not reload when a user clicks into a slate detail.
* IN-1230
Per conversation with @nzeltzer we are fetching more recs on initial load of home to make it so slate details does not reorder the results.
* Load home
* Go into a slate detail, you should not see them re-order.

fix(slate-detail): removing extra slate detail refresh

---

PocketKit/Sources/Sync/SyncConstants.swift

In talking with @nzeltzer we have decided that the intial list size we load will be 1000 items which covers most pocket users based on analytics.
We will raise this once we have intelligent downloading.
* Load list with > 1000 items and ensure they are all visible

feat(saves): increase the default list size

---

PocketKit/Sources/PocketKit/ImageManager.swift
PocketKit/Sources/PocketKit/Services.swift
PocketKit/Sources/Sync/ImagesController.swift
PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Sources/Sync/Requests.swift
PocketKit/Sources/Sync/Source.swift
PocketKit/Sources/Sync/Space.swift
PocketKit/Tests/PocketKitTests/ImageManagerTests.swift
PocketKit/Tests/PocketKitTests/Support/MockImageDownloader.swift
PocketKit/Tests/PocketKitTests/Support/MockSource.swift
PocketKit/Tests/PocketKitTests/Support/Space+factories.swift
PocketKit/Tests/SyncTests/PocketSourceTests.swift

Improve how images are (un)cached when there are Image changes in Source.
IN-1222
The usage of `ImagesController` is now simplified - we will handle Image changes when all changes have been saved, rather than on each insert / delete / etc. There is now some additional logic for when images should be downloaded:
1. Checked for any orphaned Images (Images that have no `.item`)
2. Generate a set of all URLs for the latest Images
3. Generate a set of all URLs for orphaned Images
4. Create sets of URLs that should be downloaded, skipped, and deleted
5. Delete the appropriate cached Images, download the appropriate uncached Images, and delete all orphan Images from source
- A spinner should appear while a thumbnail is downloading

fix(cache): improve caching and deletion of images

---

README.md

Add instructions on how to generate a license acknowledgement file.
* IN-772
Generating via Markdown for now. We could also include this in a iOS Settings bundle if we want.

chore(license): adding in instructions for acknowledgement generation

---

PocketKit/Sources/PocketKit/Extensions/UIViewControllerExtension.swift
PocketKit/Sources/PocketKit/Item/ReadableHostViewController.swift
PocketKit/Sources/PocketKit/PocketAppDelegate.swift

Fix rotation on iPhone and only allow Reader to be rotated.
IN-1134
Created static var `phoneOrientationLock` that is set to `portrait` by default for phone devices. Only case we want to be able to rotate the view is for our reader and added `lockOrientation` to be able to make the change for this view when it appears. 
As a phone user, when I rotate my device to landscape orientation, the screen should not rotate, unless I am reading an article. 
1. Navigate to Premium Purchase Screen or any other screen that is not Reader
2. Attempt to rotate the screen and confirm view does not change
1. Navigate to Reader
2. Attempt to rotate the screen and confirm view does indeed change
- [N/A] Added Unit / UI tests

fix(orientation): allow only reader to rotate

---

Pocket.xcodeproj/xcshareddata/xcschemes/Pocket (iOS).xcscheme

Added an environment variable to our Scheme in order to remove some Xcode logs that was bloating up our console. 
Slack Convo: https://pocket.slack.com/archives/C01UH57EJKD/p1679931937517129
Stack-overflow Post: https://stackoverflow.com/questions/37800790/hide-strange-unwanted-xcode-logs
Add environment variable `OS_ACTIVITY_MODE` and set value to `disable`
Check and uncheck this environment variable and confirm whether additional logs appear or disappear. We should see less noisy logs in the console.

fix(scheme): set OS_ACTIVITY_MODE to disable

---

PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/ImageManager.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewController.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/PocketKit/PocketAppDelegate.swift
PocketKit/Sources/Sync/CoreData+Relationships/README.md
PocketKit/Sources/Sync/CoreData+Relationships/RelationshipExtensions.swift
PocketKit/Sources/Sync/CoreData+Relationships/RelationshipKeyPath.swift
PocketKit/Sources/Sync/CoreData+Relationships/RelationshipKeyPathObserver.swift
PocketKit/Sources/Sync/CoreData+Relationships/RichFetchRequest.swift
PocketKit/Sources/Sync/CoreData+Relationships/RichNSFetchedResultsController.swift
PocketKit/Sources/Sync/CoreDataInitializers/Recommendation+CoreDataProperties.swift
PocketKit/Sources/Sync/Operations/FetchArchive.swift
PocketKit/Sources/Sync/Operations/FetchSaves.swift
PocketKit/Sources/Sync/PersistentContainer.swift
PocketKit/Sources/Sync/PocketModel.xcdatamodeld/PocketModel.xcdatamodel/contents
PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Sources/Sync/RemoteMapping/Image+remoteMapping.swift
PocketKit/Sources/Sync/RemoteMapping/Item+remoteMapping.swift
PocketKit/Sources/Sync/RemoteMapping/SlateLineup+remoteMapping.swift
PocketKit/Sources/Sync/Requests.swift
PocketKit/Sources/Sync/Source.swift
PocketKit/Sources/Sync/Space.swift
PocketKit/Sources/Sync/SyncConstants.swift
PocketKit/Tests/PocketKitTests/HomeViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockSource.swift
PocketKit/Tests/SyncTests/PocketSourceTests+networkMonitoring.swift
PocketKit/Tests/SyncTests/PocketSourceTests+restoringOperations.swift
Tests iOS/HomeTests.swift
Tests iOS/PullToRefreshTests.swift

The UI was constantly hanging for me when logging out and in during testing. I believe this came down to how we were using threads, saving data and making network calls.
In this PR i fixed a few things:
* Ensure that we do not bombard our poor server, by:
* Allowing a refresh of data only after 5 seconds from the last refresh has passed
* Ensure that if we are restoring a failed FetchSaves/Archive operation we do not start another one.
* Ensure Home monitors relationship changes in [NSFetchedResults Controller](https://www.avanderlee.com/swift/nsfetchedresultscontroller-observe-relationship-changes/)
* Ensure that all images we cache are saved to device, and the respective models listen for the image being downloaded.
* Speed up initial sync by giving FetchSaves & FetchArchive their own …

fix(concurrency): clean up some of our threading and calls

---

Pocket.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PocketKit/Package.swift
PocketKit/Sources/PocketKit/PocketAppDelegate.swift
PocketKit/Sources/SaveToPocketKit/MainViewController.swift
PocketKit/Sources/SaveToPocketKit/Services.swift
PocketKit/Sources/SharedPocketKit/Migrations/LegacyEncryptedStore.swift
PocketKit/Sources/SharedPocketKit/Migrations/LegacyUserMigration.swift
PocketKit/Tests/SharedPocketKitTests/LegacyUserMigrationTests.swift

As required, performs a migration of a legacy user session (guid, access token, and user identifier) from the legacy session store to the new keychain-based store.
IN-845
There are two main portions to this implementation:
1. Verify that the application _needs_ to run the migration
- If the user's last known application version was < 8.x.x, and the migration had not yet been run
2. Perform the migration, either in the main app or the save extension.
For obtaining the previous version _as well as_ the legacy session information, we have to dig into an encrypted JSON file, stored in a shared directory (so that both the extension and application can read from it). We use `RNCryptor` to decrypt the data (from the JSON file), using a password stored in `UserDefaults`. To simplify …

feat(migration): migrate legacy user sessions to new session type

---

PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/Sync/PocketSource.swift

It was reported that Home was constantly refreshing for @mkoidin. Upon 👁️ I noticed that the Network code was calling the updateHandler multiple times and we were always having home force refresh every time.
Instead forceRefresh should only be reserved for a user pulling to refresh. 
We should also always observe network status on a background queue.
* Change network status and ensure that home does not do a hard refresh (where items change) when toggling network status.

fix(home): ensuring home does not always refresh

---

Tests iOS/MyList/SearchTests.swift

Fix tests that were broken in develop. Alongside this commit:
[fix(tests): add premium call to searchtests](https://github.com/Pocket/pocket-ios/commit/95144eea214d3c151662dcabaf66745678ca222a)
N/A
Fix tests by adding proper Fixtures for returning if a user is premium or not
Run `SearchTests` to confirm does not fail.
Run `HomeTests` to confirm does not fail.

fix(tests): fix broken tests

---

PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/PremiumUpgrade/Model/ReceiptService.swift
PocketKit/Tests/PocketKitTests/ImageManagerTests.swift

Pocket's backend only knows about StoreKit 1 for the time being. It seems the receipt that gets saved in the receipt URL area is a storeKit 2 receipt and is not compatible with our backend.
So we need to explcitly create a StoreKit 1 receipt request and send that to our backend.
* Checked continuations are so cool.
* Test out purchasing and it should succeed.

fix(storekit1): add storekit 1 methods

---

PocketKit/Sources/PocketKit/PremiumUpgrade/Model/ReceiptService.swift

On iOS simulators when you are logged out of Apple, a system prompt will show if you request a receipt. Instead we should see if a recept exists first

fix(receipts): ensuring there is a receipt

---

PocketKit/Sources/PocketKit/Article/ReadableViewController.swift

* This PR fixes a leak happening when opening an item in the reader
For reference, here's what was happening before
<p align=center>
</p>
* Update `ReadableViewModel`, add an `unowned` reference to `self` in the closure that defines the `layout` property to avoid the cycle
* If you're curious about testing, you can open an item in the reader a few times and check the memory graph making sure there's no more than one instance of `ReadableViewModel` (zero if you're not in the reader anymore)
* If you wanna see the behavior in the picture, just remove unowned and repeat the test.

Fix a memory leak when opening the Reader

---

PocketKit/Sources/Analytics/AppEvents/Reader.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/ReadableViewModel.swift
PocketKit/Sources/PocketKit/Item/ReadableHostViewController.swift
Tests iOS/ReaderTests.swift

Add tracking for when user opens article in web from reader 
IN-491
Create `reader.view_original` analytics call in `Reader.swift` and add call to `openExternally`
Confirm if call is being triggered when user opens article in web view.

feat(analytics): track open in web from reader

---

PocketKit/Sources/Sync/Log.swift
PocketKit/Sources/Sync/Operations/AsyncOperation.swift
PocketKit/Sources/Sync/Operations/FetchArchive.swift
PocketKit/Sources/Sync/Operations/FetchSaves.swift
PocketKit/Sources/Sync/Operations/RetriableOperation.swift
PocketKit/Sources/Sync/Operations/SaveItemOperation.swift
PocketKit/Sources/Sync/Operations/SavedItemMutationOperation.swift
PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Sources/Sync/Space.swift
PocketKit/Tests/SyncTests/Operations/RetriableOperationTests.swift
PocketKit/Tests/SyncTests/PocketSourceTests+networkMonitoring.swift
Tests iOS/Support/Elements/XCUIElement+wait.swift

Ensure that Operations have time to delete their Operations from CoreData by moving the PersistentTaskCleanup logic into RetriableOperation.
* I want to move the operation queuing logic out of PocketSource into it's own isolated class but will do that in a followup pr to keep changes small.
* This is a hard one to test unfortunately, so im gonna go tried and true and rely on our test suite.

fix(background): ensuring all background tasks have time to end

---

PocketKit/Sources/PocketGraph/Fragments/SlateParts.graphql.swift
PocketKit/Sources/Sync/RemoteMapping/SlateLineup+remoteMapping.swift

Updates GraphQL schemas to use a non-optional ID.
- There was a backend change made and merged that made IDs non-optional. Our code was relying on optional IDs (see: remoteID). This is a simple update to handle remote IDs as non-optional, removing them from guards.

fix(schema): updating schema with new changes

---

Pocket.xcodeproj/project.pbxproj

Runs swiftlint under strict mode to treat warnings as errors.

build: run swiftlint as strict

---

PocketKit/Sources/PocketKit/Refresh/ArchiveRefreshCoordinator.swift
PocketKit/Sources/PocketKit/Refresh/HomeRefreshCoordinator.swift
PocketKit/Sources/PocketKit/Refresh/RefreshCoordinator.swift
PocketKit/Sources/PocketKit/Refresh/SavesRefreshCoordinator.swift
PocketKit/Sources/PocketKit/Refresh/TagsRefreshCoordinator.swift
PocketKit/Sources/PocketKit/Refresh/UnresolvedSavesRefreshCoordinator.swift

Found a bug where the coordinators lost their subscribers for log out and login.
* Ensure on log out and login your list downloads.

fix(refreshing): ensuring logout/login subscribers are retained

---

Info.plist
Pocket.xcodeproj/xcshareddata/xcschemes/Pocket (iOS) Alpha Neue.xcscheme
PocketKit/Sources/PocketKit/Main/RootViewModel.swift
PocketKit/Sources/PocketKit/Refresh/UserRefreshCoordinator.swift
PocketKit/Sources/PocketKit/Services.swift

Ensure that user data only refreshes when there is an active session.
* IN-1238
* Switched user data to the refresh coordinator pattern
* Ensure there are no FetchUser errors in the console on logout and login.

fix(user): ensuring we only refresh the user when we have a session

---

PocketKit/Sources/Sync/RemoteMapping/Item+remoteMapping.swift

* This PR fixes a crash due to wrong context being used
* Update `Item+RemoteMapping`, add missing context injection in fetchSyndicatedArticle call

Fix - Add missing context injection

---

PocketKit/Sources/PocketKit/Tags/TagsFilterViewModel.swift
PocketKit/Sources/Sync/Requests.swift
PocketKit/Sources/Textile/Views/Tags/TagType.swift
PocketKit/Tests/PocketKitTests/PocketAddTagsViewModelTests.swift
PocketKit/Tests/PocketKitTests/TagsFilterViewModelTests.swift
PocketKit/Tests/SaveToPocketKitTests/SaveToAddTagsViewModelTests.swift
Tests iOS/AddTagsItemTests.swift
Tests iOS/MyList/SavesFiltersTests.swift
Tests iOS/SettingsTests.swift
Tests iOS/Support/XCTestCase+extensions.swift
bitrise.yml

@timc-mozilla discovered that our test was not battle hardended against small device sizes. This makes use of a scrollTo function to ensure that we scroll to a specific element instead of unless scrolling or assuming something is on screen.
This will also fixes flakyness I discovered around tags where tags were always appearing in a different order. This should be fully fixed in https://github.com/Pocket/pocket-ios/pull/568 and any work here is a stop gap for tests and sanity.
There are a few helper [libraries](https://github.com/PGSSoft/AutoMate) we could import that would help with our tests, but I chose to use a very basic scrollTo function instead since the one I found had not been updated in a while.
* Try the add tags tests on a iphone mini

fix(tests): battle hardened tests against multiple device sizes

---

PocketKit/Sources/Sync/CoreDataSpotlightDelegate.swift
PocketKit/Sources/Sync/PersistentContainer.swift
PocketKit/Sources/Sync/PocketModel.xcdatamodeld/PocketModel.xcdatamodel/contents

I was playing with apple apis and discovered its very easy to add in core spotlight! So why not! 
* https://developer.apple.com/videos/play/wwdc2021/10098/
* Picked out basic fields for the search attributes, we can iterate on these in the future. 
* For now this only indexes spotlight, but in the future we could use CoreSpotlight for our free search instead of our wild card core data search. (see last 5 minutes of wwdc video)
* I did not write tests, because this is a system delegate callback.
* Log in on a fresh user, wait for the list to load. Try searching for the item using the title in the pull down search in iOS system. (may take a bit for indexed results to appear)

feat(spotlight): adding in spotlight indexing.

---

PocketKit/Sources/Sync/Operations/FetchArchive.swift
PocketKit/Sources/Sync/Operations/FetchSaves.swift
PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Tests/SyncTests/Support/FetchSavesTests.swift

Moves the sending the `.start` state within our operation queue, where it is guarded from being called multiple times before it is finished loading.
* IN-1311
* we need to think about a better way to do placeholders and pagination, but not atm
* Try and perform the replication as done by Matt here: https://pocket.slack.com/archives/C4DL4QSU8/p1681169244912969?thread_ts=1680970901.903769&cid=C4DL4QSU8
* Note you must pull to refresh again, as soon as you see your first set of list results.

fix(saves): ensure that dual refreshing saves does not reset the loading state

---

PocketKit/Sources/PocketKit/MyList/EmptyStates/SFSafariView.swift
PocketKit/Sources/PocketKit/Settings/SettingsView.swift

I noticed our licenses look better in reader mode. This enables that by default.
cc @nzeltzer thoughts ?

fix(license): opening licesnes in reader mode

---

PocketKit/Sources/PocketKit/NotificationCenter+EventNames.swift
PocketKit/Sources/SharedPocketKit/Migrations/LegacyUserMigration.swift
PocketKit/Sources/SharedPocketKit/NotificationCenter+EventNames.swift

Post a notification to the system that we logged in when we migrated a user. 
This will:
* Tell Braze/Instant Sync we have a user
* Kick off all the refresh data tasks

fix(migration): ensure that a migration posts a logged in message

---

PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Sources/Sync/Source.swift

* Cleaning up `Source` and `PocketSource` a bit
* Update `Source`, `PocketSource`, remove unused methods `backgroundObject` and `backgroundRefresh`
* Make sure this branch builds properly

Core Data - Cleanup Source, PocketSource

---

PocketKit/Package.swift
PocketKit/Sources/Analytics/AppEvents/Tags.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/PocketKit/Tags/PocketAddTagsViewModel.swift
PocketKit/Sources/PocketKit/Tags/TagsFilterViewModel.swift
PocketKit/Sources/SaveToPocketKit/MainViewController.swift
PocketKit/Sources/SaveToPocketKit/SaveToAddTagsViewModel.swift
PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewModel.swift
PocketKit/Sources/SaveToPocketKit/Services.swift
PocketKit/Sources/SharedPocketKit/Tags/AddTagsViewModel.swift
PocketKit/Sources/SharedPocketKit/Tags/RecentTagsProvider.swift
PocketKit/Sources/Textile/Tags/Components/RecentTag.swift
PocketKit/Sources/Textile/Tags/Components/TagsCell.swift
PocketKit/Sources/Textile/Tags/Components/TagsSectionView.swift
PocketKit/Tests/PocketKitTests/PocketAddTagsViewModelTests.swift
PocketKit/Tests/PocketKitTests/SavedItemViewModelTests.swift
PocketKit/Tests/PocketKitTests/SavedItemsListViewModelTests.swift
PocketKit/Tests/PocketKitTests/Search/PocketItemViewModel.swift
PocketKit/Tests/PocketKitTests/TagsFilterViewModelTests.swift
PocketKit/Tests/SaveToPocketKitTests/SaveToAddTagsViewModelTests.swift
PocketKit/Tests/SaveToPocketKitTests/SavedItemViewModelTests.swift
PocketKit/Tests/SaveToPocketKitTests/Support/MockUser.swift
Tests iOS/AddTagsItemTests.swift
Tests iOS/EditTagsTests.swift
Tests iOS/MyList/ArchiveFiltersTests.swift
Tests iOS/MyList/SavesFiltersTests.swift
Tests iOS/Support/Elements/AddTagsViewElement.swift
UITests-2.xctestplan

Refining recent tags experience: 
* Allow only Premium users to view the recent tags and if their tags are greater than 3
* Updating UI and Unit Tests
* Adding Analytics for tapping on recent tags
IN-1268
* Added a check to `recentTags` to be displayed if user is Premium and if the number of all their tags is greater than 3.
* Added two tracking called `addTagsRecentTagTapped` and `filterTagsRecentTagTapped`
* Added `user` in `Services` for shared extension
* Moved `RecentTag` to its own file
* Created test for recent tags
Please 
There should be two sections: (1) Recent Tags, which shows the three most-recently used tags, and (2) All Tags, which shows all of a user’s tags (including the three most-recently used). Both sections should be sorted alphabetically. 
1. Recent Tags and Add Tags …

feat(tags): refine recent tags experience

---

PocketKit/Sources/PocketKit/PremiumUpgrade/Model/PocketSubscriptionStore.swift
PocketKit/Sources/PocketKit/PremiumUpgrade/Model/SubscriptionStore.swift
PocketKit/Sources/PocketKit/Services.swift
PocketKit/Sources/SharedPocketKit/User.swift

* This Pr refactors the subscription store to avoid listening for transactions, existing subscriptions or sending receipts when logged out
* Issue number in branch name
* Update `PocketSubscriptionStore`
- Subscribe to login and logout notifications
- Start App Store services at launch only if user is logged in
- Start the above service when user logs in
- Stop the above services when user logs out
* Put breakpoints in the `start()` and `stop()` methods in `PocketSubscriptionStore` and make sure they're called at login (`start()`) and logout (`stop()`)
* Log in with a free user and make sure you can still see the available subscriptions in the premium upgrade screen

Premium subscriptions: avoid checking subscriptions and sending receipts when logged out

---

Info.plist
PocketKit/Sources/PocketKit/Keys.swift
PocketKit/Sources/SaveToPocketKit/Keys.swift
SaveToPocket/Info.plist

Use the "legacy" consumer key for "pad" idioms. This should *_not_* be merged until all the appropriate bitrise config files have been updated as well.
- IN-872
Note: the key contains the word "pad" vs "iPad" because the idiom is "pad", and I wanted the two to match.

Use correct consumer key on iPad

---

PocketKit/Sources/PocketKit/Listen/Listen.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItemsListViewModel.swift

Quick fix to ensure listen has a default set of `en` for UI tests

fix(listen): update listen to have a default language set

---

PocketKit/Sources/SaveToPocketKit/InfoView.swift
PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewModel.swift
PocketKit/Tests/SaveToPocketKitTests/SavedItemViewModelTests.swift
Tests iOS/SaveToPocketTests.swift

Fix bug where we cannot save from Feedly due to URL initialization returning nil
* IN-1254
Create a helper function to parse a URL from a string. Modified from https://www.hackingwithswift.com/example-code/strings/how-to-detect-a-url-in-a-string-using-nsdatadetector
This only applied to the items that are of the type `public.plain-text`
Nav to the Feedly app
Share any item to Pocket
Verify that error no longer appears and you are able to save the item

fix(extension): address feedly bug

---

PocketKit/Sources/SaveToPocketKit/MainViewController.swift
PocketKit/Sources/SharedPocketKit/SignOutOnFirstLaunch.swift

Fixes an issue where a login could persist between app installs if first using the share extension, and where a migrated user who launched the share extension first would not be logged in after opening the app for the first time.
IN-1329
_Important note: the keychain is not deleted on app uninstall; we have to manually clear it on first launch._
Since the keychain is not deleted, in order to ensure a clean slate on first install, the main app target would attempt to run a cleanup operation on first launch (i.e after installing). The completion of this operation is then noted in `UserDefaults` (on first launch, if this value is not found, perform the operation).
If the share extension is launched first, the user's session is migrated to the keychain. If the app is subsequently launched for …

fix: sign out on first launch of share extension if needed

---

PocketKit/Sources/PocketKit/Refresh/RefreshCoordinator.swift
PocketKit/Sources/Sync/PocketSource.swift

While this doesn't solve the root cause on IN-1306. It does start capturing more specific data for us. With the logging added the root problem appears to be the CoreData store SavedItem object somehow becoming invalid and causing the store save method to rollback which in turn does not update the UI. 
However when you are online the problem does not appear, because the server will do a full object refresh with the SavedItem in our store. 
--
I am also proposing that we implement the ability to post an error from Sync or similar to NotificationCenter that will trigger a banner or something to indicate there is an error like this.
* IN-1306
* Manipulate items and see breadcrumbs in the logs.

fix(logs): adding explict logging and error handling to mutations

---

PocketKit/Tests/PocketKitTests/Notifications/PushNotificationServiceTests.swift
Tests iOS/Support/Elements/PocketUIElement.swift
Tests iOS/Support/Elements/XCUIElement+wait.swift
Tests iOS/Support/XCTestCase+extensions.swift

Sometimes some screens take a bit to load on the CI hardware. Bumping timeout to 20 to account for this.
Ideally we should move all the timeouts to a helper method, we can do that after this is successful and we do a audit of tests.

fix(timeout): bumping wait timeout for test

---

Pocket.xcodeproj/project.pbxproj
PocketKit/Sources/Sync/ApolloClient+Extensions.swift
Tests iOS/MyList/CoreSpotlightTests.swift

In order to seperate traffic on the backend, we need to move clients to api.getpocket.com. Our android app has already been on this domain for a few years, and we should ensure iOS is on it before launch.

feat(api): moving to api domain

---

PocketKit/Sources/PocketKit/Home/HomeCarouselItemCell.swift
PocketKit/Sources/PocketKit/Home/RecommendationButton.swift
PocketKit/Sources/PocketKit/Home/RecommendationCell.swift
PocketKit/Sources/PocketKit/Home/RecommendationCellHeroWide.swift

Maintain consistent spacing between the actions and thumbnails by pinning the action buttons to the bottom
IN-1229
Change favorite button to use same configuration as overflow to maintain consistent padding. Align stacks to the bottom and created custom spacing so that the subtitle stack is aligned with the button stacks. They should be 16.0 from the bottom.
1. Nav to Recent Saves
2. Scroll the Recent Saves
3. Notice not all of the space between the secondary actions and the images is consistent

fix(home): spacing between actions and thumbnails

---

PocketKit/Sources/PocketKit/PremiumUpgrade/Model/PocketSubscriptionStore.swift

* This PR reverts to free/unsubscribed status if the subscription that comes back from the App Store has expired
* IN- 1137
* Update `PocketSubscriptionStore`, add logic in `fetchActiveSubscription()` that reverts the app to free when a subscription is expired.
* Build run this branch and login with a free sandbox account
- Purchase a monthly premium subscription
- Wait 3 minutes or more (this will allow the subscription to expire)
- Restart the app and make sure you can access the premium upgrade and re-subscribe
- Make any additional tests to make sure the premium upgrade screen is accessible for free users

Premium subscriptions - revert to free if subscription expired

---

PocketKit/Sources/Analytics/AppEvents/Home.swift
Tests iOS/HomeTests.swift
Tests iOS/ReportARecommendationTests.swift

Update identifiers from using discover to home
Slack convo: https://pocket.slack.com/archives/C01UH57EJKD/p1681756969627059
IN-1344
Update identifiers in `Home.swift` from using discover terminology to home. Also noticed that we were using card instead of buttons in some cases which did not match the spreadsheet.
Verify that calls are using `home.slate.article` instead of `discover`

refactor(analytics): change identifiers from using discover to home

---

PocketKit/Package.swift
PocketKit/Sources/Analytics/Tracker/PocketTracker.swift
PocketKit/Sources/PocketKit/AppBadgeTracker.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/ReadableViewModel.swift
PocketKit/Sources/PocketKit/Listen/ListenRuntime.swift
PocketKit/Sources/PocketKit/Listen/ListenViewModel.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchSavedItem+ItemsListItem.swift
PocketKit/Sources/PocketKit/Notifications/PocketAppDelegate+PocketNotificationService.swift
PocketKit/Sources/PocketKit/Report/ReportRecommendationView.swift
PocketKit/Sources/SharedPocketKit/Log.swift
PocketKit/Sources/Sync/ApolloClient+Extensions.swift
PocketKit/Sources/Sync/ApolloClientProtocol+Extensions.swift
PocketKit/Sources/Sync/CoreData+Relationships/RelationshipExtensions.swift
PocketKit/Sources/Sync/Operations/RetriableOperation.swift
PocketKit/Sources/Sync/Operations/SavedItemMutationOperation.swift
PocketKit/Sources/Sync/PersistentContainer.swift
PocketKit/Sources/Sync/PocketSaveService.swift
PocketKit/Sources/Sync/RemoteMapping/Item+remoteMapping.swift
PocketKit/Sources/Sync/RemoteMapping/SavedItem+RemoteMapping.swift
PocketKit/Sources/Sync/RemoteMapping/SlateLineup+remoteMapping.swift
PocketKit/Sources/Sync/Slates/SlateService.swift
PocketKit/Sources/Sync/Space/DerivedSpace.swift

Moves `Log` out of the `Sync` package and into `SharedPocketKit`

project(log): move Log to SharedPocketKit

---

PocketKit/Sources/Analytics/AppEvents/Tags.swift
PocketKit/Sources/PocketKit/Tags/PocketAddTagsViewModel.swift
PocketKit/Sources/PocketKit/Tags/TagsFilterViewModel.swift
PocketKit/Sources/SaveToPocketKit/SaveToAddTagsViewModel.swift
PocketKit/Sources/SharedPocketKit/Tags/AddTagsViewModel.swift
Tests iOS/AddTagsItemTests.swift
Tests iOS/MyList/ArchiveFiltersTests.swift
Tests iOS/MyList/SavesFiltersTests.swift

Update and add new calls to track a user selecting tags from `Add Tags` screen and filter `Tags` screen
IN-1268
Added following tracking calls: 
```
global-nav.filterTags.selectTag
global-nav.filterTags.selectRecentTag
global-nav.filterTags.selectNotTagged
global-nav.addTags.selectTag
global-nav.addTags.selectRecentTag
```
See Analytics Actions spreadsheet for confirmation
Verify that the tracking calls are being triggered from the right actions

fix(analytics): update selected tags tracking calls

---

PocketKit/Sources/PocketKit/Main/MainView.swift

Fixes an issue where dark mode users would have the incorrect background color under the status bar.

fix(dark-mode): use correct background colors for home / saves

---

PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Sources/Sync/Space/Space.swift
PocketKit/Tests/PocketKitTests/AppBadgeTrackerTests.swift
PocketKit/Tests/PocketKitTests/HomeViewModelTests.swift
PocketKit/Tests/PocketKitTests/RecommendationViewModelTests.swift
PocketKit/Tests/PocketKitTests/SavedItemsListViewModelTests.swift
PocketKit/Tests/PocketKitTests/SlateDetailViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/Space+factories.swift
PocketKit/Tests/SyncTests/APISlateServiceTests.swift
PocketKit/Tests/SyncTests/Fixtures/list.json
PocketKit/Tests/SyncTests/Fixtures/slates.json
PocketKit/Tests/SyncTests/PocketSourceTests.swift
PocketKit/Tests/SyncTests/SpaceTests.swift
PocketKit/Tests/SyncTests/Support/Space+factories.swift

Fix tests, see original PR for context
https://github.com/Pocket/pocket-ios/pull/605
N/A
* We updated SavedItem and Item to have unique properties (i.e. given_url and url and remoteID), but the items to set up these tests were using the same values for the saved Items causing errors. Setting up the items to have unique values, causes the tests pass.
* Need to create `remoteID` with tag creation in `fetchOrCreateTag` (needs to be revisited)
* Added `createdAt` when building pending saved item
Make sure tests are passing.

ci(tests): fix unit tests after core data changes

---

PocketKit/Sources/Sync/Space/Space.swift

* This PR adds a merge policy to the child contexts to avoid erroring when an existing object gets updated
* Update `Space`, add `mergeByPropertyObjectTrump` merge policy in `makeChildBackgroundContext()`
* Make sure no crashes are observed while using the app, particularly Home, Saves/archive, and tags

Core Data - Add `mergeByPropertyObjectTrump` to child contexts

---

PocketKit/Sources/Localization/Resources/en.lproj/Localizable.strings
PocketKit/Sources/Localization/Strings.swift
PocketKit/Sources/PocketKit/Article/ReadableView.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/ReadableViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/RecommendationViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift
PocketKit/Sources/PocketKit/BannerPresenter.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Main/MainView.swift
PocketKit/Sources/PocketKit/Main/MainViewModel.swift
PocketKit/Sources/PocketKit/Main/RootView.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewController.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/PocketKit/Services.swift
PocketKit/Sources/SharedPocketKit/NotificationCenter+EventNames.swift
PocketKit/Sources/Textile/Views/Banner/BottomNotification.swift
PocketKit/Tests/PocketKitTests/HomeViewModelTests.swift
PocketKit/Tests/PocketKitTests/SavedItemViewModelTests.swift
PocketKit/Tests/PocketKitTests/Search/SearchViewModelTests.swift

Adds peek n' pop to both Saves and Search, appropriately previewing via web view or the reader. An "Edit" option is included under the preview, which will present a banner saying that editing will come in a later release.
IN-1247
The main change here is the addition of a `BannerPresenter`, which maintains the state of whether an app-wide banner should be presented, and with what data. This type listens to a `.bannerRequested` notification, which when posted, should also include the banner data to present. The pre-existing `.banner` modifier is used to show / dismiss the banner as appropriate, which is presented within `MainView`, as to maintain visibility across all views. When `Edit` is tapped both within the context of Saves and Search, the correct notification is posted with the banner …

feat: add peek n' pop, bulk edit fake door

---

PocketKit/Sources/PocketGraph/Fragments/ItemParts.graphql.swift
PocketKit/Sources/PocketGraph/Fragments/PendingItemParts.graphql.swift
PocketKit/Sources/PocketGraph/Fragments/SavedItemParts.graphql.swift
PocketKit/Sources/PocketGraph/Fragments/SavedItemSummary.graphql.swift
PocketKit/Sources/PocketGraph/Fragments/SlateParts.graphql.swift
PocketKit/Sources/PocketGraph/Operations/Mutations/ReplaceSavedItemTagsMutation.graphql.swift
PocketKit/Sources/PocketGraph/Operations/Mutations/SaveItemMutation.graphql.swift
PocketKit/Sources/PocketGraph/Operations/Mutations/UpdateSavedItemRemoveTagsMutation.graphql.swift
PocketKit/Sources/PocketGraph/Operations/Queries/FetchArchiveQuery.graphql.swift
PocketKit/Sources/PocketGraph/Operations/Queries/FetchSavesQuery.graphql.swift
PocketKit/Sources/PocketGraph/Operations/Queries/ItemByIDQuery.graphql.swift
PocketKit/Sources/PocketGraph/Operations/Queries/SavedItemByIDQuery.graphql.swift
PocketKit/Sources/PocketGraph/Operations/Queries/SearchSavedItemsQuery.graphql.swift
PocketKit/Sources/PocketGraph/user-defined-operations/archive.graphql
PocketKit/Sources/PocketGraph/user-defined-operations/itemFragments.graphql
PocketKit/Sources/Sync/RemoteMapping/Item+remoteMapping.swift
PocketKit/Sources/Sync/RemoteMapping/SavedItem+RemoteMapping.swift
PocketKit/Sources/Sync/Space/DerivedSpace.swift

Item is not null in the Graph, but only if you adhere to it's interface and check for Pending Item. 
This updates the code to create an item from pending item.
In the future I think we will want to update some field names to be more clear, and drop things we don't need (we dont need givenURL and resolvedURL from the graph on Item).
* Save something that the parser can not reach on the internet (like a local ip url)
* Without this change the app will crash if you scroll to the item in your list
* With this change the app will not crash and fallback to showing URL instead of a fancy title in the list, and treat the item as non article.

fix(item): ensuring that an item always exists, using PendingItem

---

PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/Sync/CoreDataInitializers/Recommendation+CoreDataClass.swift
PocketKit/Sources/Sync/CoreDataInitializers/Recommendation+CoreDataProperties.swift
PocketKit/Sources/Sync/PocketModel.xcdatamodeld/PocketModel.xcdatamodel/contents
PocketKit/Sources/Sync/RemoteMapping/SlateLineup+remoteMapping.swift
PocketKit/Tests/PocketKitTests/Support/Space+factories.swift
PocketKit/Tests/SaveToPocketKitTests/Support/Space+factories.swift
PocketKit/Tests/SyncTests/APISlateServiceTests.swift
PocketKit/Tests/SyncTests/Support/Space+factories.swift

* This PR improves the recommendations fetching logic to prevent a crash
* Update `Recommendation`, add `analyticsID` property
* Update `SlateLineup+RemoteMapping`, concatenate recommendation id and slate id, and use it as a `Recommendation` unique ID, to account for recommendations that could be present in more than one slate
* Update `HomeViewModel`, use the newly added `analyticsID` field to identify a recommendation in analytics tracks
>**Note**
This PR changes the data model, it is recommended to delete previous builds before installing and testing this one
* Build/run this branch
* Refresh Home repeatedly
* Make sure there are no crashes

Home - Fix a crash when loading remote lineup

---

PocketKit/Package.swift

Adds missing `ApolloTestSupport` package dependency that would cause build errors when attempting to run UI tests.

fix(ci): add missing test support dependency

---

PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift

* Fixes a crash occurring while scrolling online search results
* Update `SavedItemsListViewModel`, ensure reloaded items are present in the snapshot
* Update `SearchViewModel`, `SearchView`: (temporarily) remove peek 'n' pop from search results
* Login with a premium account
* Search something that produces a long list
* Scroll through and make sure that:
- The UI does not freeze
- There are no crashes

Fix Core Data crash on search results

---

PocketKit/Sources/PocketKit/Item/ReadableHostViewController.swift
PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift

Ensure that reader full screen pushes, and that saved items deselect when returning to saves view.
https://user-images.githubusercontent.com/1010384/234144522-080b58c0-2c13-4fa2-9c77-b1794d9c4007.mp4
*[IN-1334](https://getpocket.atlassian.net/browse/IN-1334)
* `hidesBottomBarWhenPushed` did not work. Likely because the view is hosted in a UI Nav view, hosted in a SwiftUI Tab View
[IN-1334]: https://getpocket.atlassian.net/browse/IN-1334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ui): making saves deselect and reader full screen push

---

PocketKit/Sources/PocketKit/Main/MainView.swift
PocketKit/Sources/PocketKit/Main/RootView.swift

* Bring back the tab bar appearance that we lost with the coordinators https://github.com/Pocket/pocket-ios/pull/473/files#diff-bf02518d373044a10a8e8299a3d13ce19bc283ed4baa898598e6feeb681b25f2L51-L63

fix(tabBar): brining back the tab bar appearance

---

PocketKit/Sources/PocketKit/PocketAppDelegate.swift
PocketKit/Sources/PocketKit/Services.swift
PocketKit/Sources/SaveToPocketKit/MainViewController.swift
PocketKit/Sources/SaveToPocketKit/Services.swift
PocketKit/Sources/SharedPocketKit/Migrations/LegacyEncryptedStore.swift
PocketKit/Sources/SharedPocketKit/Migrations/LegacyUserMigration.swift
PocketKit/Sources/SharedPocketKit/Session/SessionBackupUtility.swift
PocketKit/Sources/SharedPocketKit/UserDefaultsKey.swift
PocketKit/Tests/SharedPocketKitTests/LegacyUserMigrationTests.swift
PocketKit/Tests/SharedPocketKitTests/SessionBackupUtilityTests.swift
PocketKit/Tests/SharedPocketKitTests/Support/BlankKeychain.swift
PocketKit/Tests/SharedPocketKitTests/Support/MockEncryptedStore.swift

- On user log in / out, the session is saved to an encrypted store, which can later be reused by the legacy migration. This is required for re-authenticating a user after org transfer, where we can force re-run the legacy user migration for re-authentication.
- Fixes an issue where analytic events and migration errors were being captured for scenarios that were not true "errors", but special cases that had to be handled.
IN-1182
In order to save session data to a file, `SessionBackupUtility` was used. This listens to both `.userLoggedIn` and `.userLoggedOut` notifications, and appropriately adding / updating the required keys within an encrypted store. Upon requesting file access, this store will be created on-disk if it did not previously exist. Otherwise, this file will be updated as …

feat(session): write session data to encrypted store on log in / out

---

PocketKit/Sources/Analytics/AppEvents/SaveTo.swift
PocketKit/Sources/SaveToPocketKit/SaveToAddTagsViewModel.swift
PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewModel.swift

Fixes an issue where a `Content` entity would be attached to all analytic events from the Save extension, e.g migration, unnecessarily.
Updates the event identifiers used for all tag-related events tracked within the Save extension.
https://getpocket.atlassian.net/browse/IN-1356
- Updated the Analytics spreadsheet after discussing updated identifiers for the scope of the Save extension
- Updated tag-event-related identifiers when used within the Save extension
- Removed the use of a persisted Content entity, instead appending the Content entity as necessary

refactor(analytics): correctly append Content entity, update SaveTo tag event identifiers

---

PocketKit/Sources/Sync/PocketModel.xcdatamodeld/PocketModel.xcdatamodel/contents
PocketKit/Sources/Sync/RemoteMapping/SavedItem+RemoteMapping.swift
PocketKit/Sources/Sync/RemoteMapping/SlateLineup+remoteMapping.swift
PocketKit/Sources/Sync/Space/Space.swift
PocketKit/Tests/SyncTests/APISlateServiceTests.swift
PocketKit/Tests/SyncTests/Fixtures/save-item.json
PocketKit/Tests/SyncTests/PocketSourceTests.swift

* Remove uniqueness from `remoteID` in `Item`
* No crashes allowed! Also, pls delete the older version

Core Data: remove uniqueness requirement from `Item.remoteID`

---

PocketKit/Sources/Analytics/Events/System.swift
PocketKit/Sources/PocketKit/Main/RootViewModel.swift
PocketKit/Sources/PocketKit/PocketAppDelegate.swift
PocketKit/Sources/SaveToPocketKit/MainViewController.swift
PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewModel.swift

This ensure that we always attach the APIUser entity and if there is a session, the UserEntity to analytics at app launch. This was primarly done in RootViewModel, but RootViewModel is not loaded until after the App finish launching method and with the 7 -> 8 migration, we are now emitting analytics before the RootViewModel loads.
* https://pocket.slack.com/archives/C4DL4QSU8/p1682463311167069?thread_ts=1682447329.175119&cid=C4DL4QSU8
* I think we can do a cleaner job of analytics initing but I am not going to include that work in MVP.

fix(analytics): ensure we always init the api user entity

---

PocketKit/Sources/PocketKit/MyList/ItemsList/PocketItemViewModel.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Sources/Sync/Requests.swift
PocketKit/Sources/Sync/Source.swift
PocketKit/Sources/Sync/Space/DerivedSpace.swift
PocketKit/Sources/Sync/Space/Space.swift
PocketKit/Tests/PocketKitTests/Support/MockSource.swift
PocketKit/Tests/SyncTests/Fixtures/save-item.json
PocketKit/Tests/SyncTests/Operations/SaveItemOperationTests.swift
PocketKit/Tests/SyncTests/PocketSaveServiceTests.swift
PocketKit/Tests/SyncTests/PocketSourceTests.swift
PocketKit/Tests/SyncTests/Support/FetchSavesTests.swift

Followup to https://github.com/Pocket/pocket-ios/pull/663 to ensure savedItem is always fetched by URL.
* Removed all by remoteID methods so we arent tempted to use it.
* Ask @nzeltzer  if you can use her list that has an item with a non-unique url 🤣

fix(saved-item): ensuring saved item only is pulled by url

---

bitrise.yml

Temporarily disable running UI tests on bitrise. This commit should be reverted once UI tests are in a state where they are consistently passing

ci: temporarily disable running ui tests

---

Pocket.xcodeproj/project.pbxproj
Pocket.xcodeproj/xcshareddata/xcschemes/Pocket (iOS).xcscheme
Tests iOS/Fixtures/recommendation-detail-4.json

Fix issue where Premium Tests were not passing locally, but was passing it Bitrise.
N/A
This is due to the `secrets` file being used that don't have the proper productIDs. To fix this, we created a new config called `Debug_Test` which is a copy of `Debug`, but uses `secrets_tests` and also changed the Scheme to use this config for Tests.
Confirm the Premium Tests are now passing successfully locally. 

chore(tests): fix premium tests that are failing locally

---

PocketKit/Sources/SharedPocketKit/LoggableError.swift

Adds `LocalizedError` support to custom errors (via `LoggableError`, which all Pocket errors conform to) to return a localized description, by default based on the `logDescription` via conformance to `LoggableError`).

refactor(error): add LocalizedError support to custom errors

---

PocketKit/Sources/Analytics/AppEvents/Reader.swift
PocketKit/Sources/Analytics/AppEvents/Saves.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/ReadableViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/RecommendationViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItemsListViewModel.swift
Tests iOS/MyList/SavesTests.swift
Tests iOS/ReaderTests.swift

Updates ContentOpen event identifiers when:
1. Opening an item from the user's list
2. Opening an item in web view from the reader
3. Opening a link by tapping on a link in the reader
IN-1343
Looking at the above summary, when testing step:
1. The identifier should be `saves.card.open`
2. The identifier should be `reader.view-original`
3. The identifier should be `reader.view-external`

refactor(analytics): update content open identifiers

---

PocketKit/Package.swift
PocketKit/Sources/SaveToPocketKit/Keys.swift
PocketKit/Sources/SaveToPocketKit/MainViewController.swift
PocketKit/Sources/SaveToPocketKit/SaveToBraze.swift
PocketKit/Sources/SaveToPocketKit/Services.swift
SaveToPocket/Info.plist

Sends a `SIGNED_IN_USER_UPGRADE_DID_START` event to Braze when a migration attempt begins in the save extension.
IN-1299
1. Update `SaveToPocketKit.Keys' to fetch Braze API key and endpoint from the main bundle
2. Create a very basic class that interfaces with Braze whose only capability (currently) is to send the `SIGNED_IN_USER_UPGRADE_DID_START` event
3. When a migration is attempted in the save extension, send the event

feat(braze): send begin migration event in save extension

---

PocketKit/Sources/Analytics/AppEvents/Tags.swift
PocketKit/Sources/PocketKit/PremiumUpgrade/View/PremiumUpsellView.swift
PocketKit/Sources/PocketKit/PremiumUpgrade/ViewModel/PremiumUpsellViewModel.swift
PocketKit/Sources/PocketKit/Tags/PocketAddTagsViewModel.swift

Add missing content entity to Add Tags Premium Upsell Analytics Call
IN-1371
Added the Content Entity to the Premium Upsell Impression Call
Verify that `global-nav.addTags.upsell` is triggered and has an associated url

fix(analytics): add content entity to upsell call

---

PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewController.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/Sync/Operations/FetchArchive.swift
PocketKit/Sources/Sync/Operations/FetchSaves.swift
PocketKit/Sources/Sync/Source.swift
PocketKit/Tests/PocketKitTests/SavedItemsListViewModelTests.swift
PocketKit/Tests/SyncTests/Support/FetchSavesTests.swift

Adds a progress bar while downloading your saves/archives to make clear to the user we are still doing work. 
* I changed our breadcrumbs to be more helpful on download.
* Log in fresh. See progress bar and breadcrumbs
https://user-images.githubusercontent.com/1010384/235556980-493444c6-4e8a-4bc3-8d49-cc54a41031d9.mp4

feat(progress): adding in a progress bar for initial downloading

---

PocketKit/Sources/PocketKit/Listen/ListenViewModel.swift

We have a few listen crashes because remoteID is nil for some SavedItems which can occur before a users changes are pushed to the server, and get remoteIDs.
Fix is to filter out unprocessed items.

fix(listen): filtering out savedItems that have no itemIds

---

PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Item/Item+Extensions.swift
PocketKit/Sources/PocketKit/Listen/ListenViewModel.swift
PocketKit/Sources/PocketKit/Listen/SavedItem+Listen.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItem+ItemsListItem.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/Sync/CoreDataInitializers/SavedItem+CoreDataProperties.swift
PocketKit/Sources/Sync/CoreDataSpotlightDelegate.swift
PocketKit/Sources/Sync/PocketModel.xcdatamodeld/PocketModel.xcdatamodel/contents
PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Tests/PocketKitTests/SavedItemViewModelTests.swift
PocketKit/Tests/PocketKitTests/SlateDetailViewModelTests.swift
PocketKit/Tests/SyncTests/Operations/SaveItemOperationTests.swift
PocketKit/Tests/SyncTests/PocketSourceTests.swift
PocketKit/Tests/SyncTests/Support/FetchSavesTests.swift

Set Item back to non-optional on SavedItem since there are scenarios such as extension and offline where we can't create an Item (which is server backed)
See convo here:
https://pocket.slack.com/archives/C01UH57EJKD/p1683046168112139?thread_ts=1683042594.907889&cid=C01UH57EJKD
* Make `Item` optional on `SavedItem`
* Fix build errors for compiling project and running tests
1. Save an article to Pocket via Share Extension on airplane mode
2. Navigate to Saves List
3. Validate that no crash occurs

fix(coredata): make Item optional on SavedItem

---

PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Sources/Sync/Space/DerivedSpace.swift

* Solving https://pocket.sentry.io/issues/4087949922/?project=5829390&query=is%3Aunresolved+release.build%3A24498&referrer=issue-stream&statsPeriod=14d&stream_index=0 and a few other errors on CoreData
* Save an Item from Home
* Delete the item from your saves
* Close the app
* Open the app.
* Note in the logs errors like the sentry error.
* Retry steps with this fix.

fix(item): deleting in the same context

---

PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItemsListViewModel.swift

Resolves an issue where there would be a glitchy animation where the cell would be resetting its swipe state, while also getting deleted due to an archive / move to saves
See added code comment.

fix(swipe): do not call completion handler on list cell swipe actions

---

PocketKit/Sources/PocketKit/Home/HomeCollectionViewSectionProvider.swift

Adjust padding between sections in Home tab for iPad layout
IN-1386
* Update padding to be consistent with the spacing between recent saves and editor's pick
Run app and verify there is no longer inconsistent space between section

fix(home): adjust padding between sections for iPad layout

---

PocketKit/Sources/PocketKit/MyList/ItemsList/PocketItem.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/PocketItemViewModel.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/ItemsListItem.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItem+ItemsListItem.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SwiftUI/ListItem.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchSavedItem+ItemsListItem.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Tests/PocketKitTests/Search/PocketItemViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockItemsListItem.swift

Add proper url input parameter for `fetchOrCreateSavedItem` so that it takes the right `url` and fetches the right item in core data.
Previously, we were searching on `bestURL` and we were unable to find the item so we created a new one. However, updated this so that we are fetching the item instead of creating a new one. 
IN-1430
Instead of using the `bestURL`, we created another field `savedItemURL` to get the proper url to be fetched from core data. Added test to make sure that the url we pass in is the savedItem URL and should match the remoteParts.
1. Navigate to Search
2. Search for Items in Both Online + Local Search
3. Confirm if Search Actions are now working

fix(search): add proper url to fetch and create savedItem

---

PocketKit/Sources/Localization/Resources/en.lproj/Localizable.strings
PocketKit/Sources/PocketKit/Article/ArticleComponentUnavailableView.swift
PocketKit/Sources/PocketKit/Style/ActionsPrimaryButtonStyle.swift
PocketKit/Sources/Textile/Style/Colors/Colors.xcassets/UI/teal2.colorset/Contents.json
PocketKit/Sources/Textile/Style/PocketButtonStyle.swift

Button color should be the same as light mode and `teal2` color in dark mode should be adjusted.
IN-1393
As part of this work: 
* Updated `teal2` dark mode to use `#9AE2DE`
* Added corner radius of `13` to buttons
* Change dark mode buttons to use light mode colors
* Small fix on capitalizing Pocket in Strings
Verify that dark mode buttons are now same color as light mode buttons
| iPad  | iPhone |
| ------------- | ------------- |
| ![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-05-04 at 11 33 25](https://user-images.githubusercontent.com/6743397/236256661-57d122b2-2a1c-415d-bc8e-c8a7a6a9dd3b.png) | ![Simulator Screenshot - iPhone 13 mini - 2023-05-04 at 11 35 24](https://user-images.githubusercontent.com/6743397/236257158-17b0ad6c-4314 …

fix(ui): dark mode buttons + color

---

PocketKit/Sources/Localization/Strings.swift
PocketKit/Sources/PocketKit/MyList/EmptyStates/EmptyStateView.swift
PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SkeletonView.swift
PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewController.swift

Fix Search Section in Dark Mode
* Titles of empty states on search should be semibold (currently, it seems it is in bold)
* In dark mode the background is not matching the rest of the app
IN-1257
Added some UI adjustments in terms of color in dark mode and font weight.
Verify the following:
* Search dark mode background should match the rest of the app
* Change empty states title from bold to semibold
* Fix Button color in dark Mode for Add Tags (snuck it in :) )
| iPhone  | iPhone |
| ------------- | ------------- |
| ![Simulator Screenshot - iPhone 13 mini - 2023-05-05 at 12 53 00](https://user-images.githubusercontent.com/6743397/236519325-582954c7-4196-4975-8cbb-47c8e61a27e4.png) | ![Simulator Screenshot - iPhone 13 mini - 2023-05-05 at 12 53 …

fix(search): adjust ui refinements for search dark mode

---

PocketKit/Sources/Sync/PocketSaveService.swift

Fixes an issue where, when offline, adding tags to an item saved from the save extension would not update the UI in the app.
IN-1351
Since the save extension and app are run as different processes, the core data store itself is shared, but not references to certain contexts (e.g background context). However, the parent remains the same (the persistent container). Since we are not directly saving to the context used by the app (since it's in another process), we notify the app that a saved item has been updated. However, a necessary Core Data type was not being saved, causing a guard to fail (`PocketSource.handleSavedItemsUpdatedNotification()`). This pull request saves the correct Core Data type to the store such that once the app is notified that a saved item has been created, …

fix(SaveTo): notify app for refresh after adding tags from Save extension

---

PocketKit/Sources/PocketKit/MyList/ItemsList/PocketItem.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/LocalSavesSearch.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/Sync/Requests.swift
PocketKit/Tests/PocketKitTests/Search/SavesLocalSearchTests.swift

*This PR
- Fixes a crash on delete an item from local search results on `saves`
- Fixes an issue that was causing archived items to show in the local `saves` search

Search: fix a crash when deleting an item

---

PocketKit/Sources/PocketKit/PremiumUpgrade/Model/PocketSubscriptionStore.swift

* Remove a Subscription expired info log from Sentry
* Update `PocketSubscriptionStore`, remove the aforementioned log.

Premium: remove expired subscription log from Sentry

---

PocketKit/Sources/PocketGraph/Operations/Queries/GetUserDataQuery.graphql.swift
PocketKit/Sources/PocketGraph/user-defined-operations/user.graphql
PocketKit/Sources/PocketGraphTestMocks/User+Mock.graphql.swift
PocketKit/Sources/PocketKit/Settings/AccountViewModel.swift
PocketKit/Sources/PocketKit/Settings/SettingsView.swift
PocketKit/Sources/SharedPocketKit/User.swift
PocketKit/Sources/SharedPocketKit/UserDefaultsKey.swift
PocketKit/Sources/Sync/User/UserService.swift
PocketKit/Tests/PocketKitTests/Support/MockUser.swift
PocketKit/Tests/SaveToPocketKitTests/Support/MockUser.swift
PocketKit/Tests/SyncTests/Fixtures/user.json
PocketKit/Tests/SyncTests/Support/FetchUserDataTests.swift
PocketKit/Tests/SyncTests/Support/MockUser.swift

* This PR adds the user email to the top section header in the Settings screen, right below the section title ("Your Account")
* see branch name
* Update graphql query for `User`, request `email`
* Update `User`, `PocketUser`, add `email` property
* Update `AccountViewModel`, add `userEmail` property
* Update `SettingsView`, add user email to the top section header, styled as the footer
* Checkout this branch and build/run
* go to Settings
* Make sure the email of the account you used is displayed below the "Your Account" title (see screenshot)
<p align=center>
</p>

Settings - Add user email to the top section header

---

Tests iOS/Support/Response+factories.swift

* With https://github.com/Pocket/pocket-ios/pull/717 the mock data stopped loading.
This was a hidden error in Apollo Client complaining about missing fields from a graphql request response.
I propose we should do 1 of 2 things to mitigate in the future:
* Detect if we are in a testing environment and make this type of missing data error crash the app for tests
* Show this error to the user, and make our tests ensure that the error is not shown.

fix(data): fixing tests missing a piece of data

---

PocketKit/Sources/Sync/Operations/FetchArchive.swift
PocketKit/Sources/Sync/Operations/FetchSaves.swift
PocketKit/Sources/Sync/Operations/FetchTags.swift
PocketKit/Sources/Sync/Operations/SaveItemOperation.swift
PocketKit/Sources/Sync/Operations/SavedItemMutationOperation.swift
PocketKit/Tests/SyncTests/Operations/ItemMutationOperationTests.swift
PocketKit/Tests/SyncTests/Operations/SaveItemOperationTests.swift
PocketKit/Tests/SyncTests/Support/FetchSavesTests.swift

* A 500 indicates an internal server error, without any backoff logic the code will try the same operation again within seconds of it failing. It is highly unlikely that an internal server error will be solved in that time. 
Until we have a backoff strategy removing the retries on 500 errors
* https://pocket.slack.com/archives/C01UH57EJKD/p1683583090774729
* Making 500 errors be a general failure.
* Pairs with https://github.com/Pocket/pocket-ios/pull/718

fix(retry): disabling retry on a 500

---

PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListOfflineCell.swift

Make title for Home offline state semibold to match other empty screens
IN-1392
Add semibold weight onto title 
Run app in offline mode and navigate to Home 
Verify that title is now in semibold
- N / A  Added Unit / UI tests
| Dark Mode | Light Mode | 
| --- | --- |
|![Simulator Screenshot - iPhone 13 mini - 2023-05-09 at 14 11 05](https://github.com/Pocket/pocket-ios/assets/6743397/e3e65983-f419-4ec1-bc0d-4812223ae7b5) | ![Simulator Screenshot - iPhone 13 mini - 2023-05-09 at 14 11 17](https://github.com/Pocket/pocket-ios/assets/6743397/862515d3-6bdc-4597-a6c6-a2407c1c29fd) |

fix(ui): add semibold weight to offline view title

---

PocketKit/Sources/Sync/Article/ArticleComponent.swift
PocketKit/Sources/Sync/Article/VideoComponent.swift

* This PR fixes a crash occurring when trying to create a `VideoComponent` instance with an invalid url
* 
* See branch name
* Update `VideoComponent`, make the convenience initializer throw an error if the url from `VideoParts` is invalid
* Update `ArticleComponent`, handle the errors described in the previous bullet

Article - Fix a crash when attempting to load a video with an invalid URL

---

PocketKit/Sources/PocketKit/Constants.swift
PocketKit/Sources/PocketKit/Extensions/UIViewControllerExtension.swift
PocketKit/Sources/PocketKit/Home/HomeCollectionViewSectionProvider.swift
PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewController.swift

Modify margins on iPad so that sections below the tile Home (“Recent Saves“, “Editors' picks“ and all others below) align with the “Home“ title margin. 
IN-1387
Add new margin for iPad and move implementation for `shouldUseWideLayout` as an extension to `UITraitCollection` to be reused in multiple places. Utilize new iPad margin of `20` for Home leading and trailing side margins. Also, modified margins for Slate Detail. 
1. Navigate to Home
2. Confirm that margins are now aligned and left / right margins are consistent
| iPad - Home | iPad - Slates | 
| --- | --- |
| ![image](https://github.com/Pocket/pocket-ios/assets/6743397/dc2eec9d-1f14-498c-bdd1-a0781348b465) | ![image](https://github.com/Pocket/pocket-ios/assets/6743397/8556d8f0-a36a-4c68-b023-2050a42ef473 …

fix(ui): make adjustments to margins for iPad

---

PocketKit/Sources/Sync/ApolloClientProtocol+Extensions.swift

* This PR updates Sentry logging from Apollo operations, making sure to always send the error code to Sentry
* Update `ApolloClientProtocol+Extensions`, refactor `handleServerError()` method to always log the code to Sentry.

Apollo - Always log error code to Sentry

---

PocketKit/Sources/PocketKit/Article/ReadableViewModel/RecommendationViewModel.swift
PocketKit/Tests/PocketKitTests/AuthorizationClientTests.swift

Address errors associated with throwing tasks that were being triggered in Bitrise.
```
/Users/[REDACTED]/git/PocketKit/Tests/PocketKitTests/AuthorizationClientTests.swift:129:9: Unhandled Throwing Task Violation: Errors thrown inside this task are not handled, which may be unexpected. Handle errors inside the task, or use `try await` to access the Tasks value and handle errors. See this forum thread for more details: https://forums.swift.org/t/task-initializer-with-throwing-closure-swallows-error/56066 (unhandled_throwing_task)
/Users/[REDACTED]/git/PocketKit/Sources/PocketKit/Article/ReadableViewModel/RecommendationViewModel.swift:113:9: Unhandled Throwing Task Violation: Errors thrown inside this task are not handled, which may be unexpected. Handle errors inside the task, or use `try …
```

fix(tasks): address errors associated with throwing tasks

---

PocketKit/Sources/PocketKit/Article/ReadableViewModel/RecommendationViewModel.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift
PocketKit/Sources/PocketKit/Item/Item+Extensions.swift
PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Sources/Sync/Source.swift
PocketKit/Tests/PocketKitTests/ItemExtensionsTests.swift
PocketKit/Tests/PocketKitTests/RecommendationViewModelTests.swift
PocketKit/Tests/PocketKitTests/SavedItemViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockSource.swift
Tests iOS/Fixtures/archive-item-detail.json
Tests iOS/Fixtures/recommendation-detail-4.json
Tests iOS/Support/Response+factories.swift

Update our logic to consider only showing articles that have article components in reader view. If an article does not have marticle data associated with it, then we show the web view.
IN-1497
Created new boolean property `hasArticleComponents` to determine if an article is not nil or its components are not empty. Added a check for `checkForArticleData` to show item in web view if the article's components are missing. Also, had to modify the `PocketSource` methods `fetchDetails` to return a Bool. This allows us to also check if the remote has article data when it has not been updated locally. 
Note: Although I don't love this, it seems to work. Happy to hear alternatives.
Currently, no known article to test with, but verified with unit / UI tests. If you have an article in which isArticle …

feat(article): open article in web view if it has no article components

---

PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListItemPresenter.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewController.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/ItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/PocketItem.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Tests/PocketKitTests/ItemsListItemPresenterTests.swift

Disallows the selection of archived items that contain no offline data, or are pending. Additionally, automatically reloads the current Saves list when the network status changes to show the latest state of the items.
IN-1308
Adds a helper function, `isItemDisabled`, that returns true if:
- the user is offline, and an archived item has no article data
- the user is offline, and an item is pending
- the user is online, and an item is pending
This is then used to initialize item presenters appropriately for the required state by adding a `isDisabled` argument. This is because determining whether or not an item is disabled required use of network monitoring, which is outside the scope of a `SavedItem`.
Additionally, a network monitor is used to determine when to reload the Saves list as to …

feat(list): disallow selection of archived or pending items

---

Pocket.xcodeproj/project.pbxproj
PocketKit/Sources/PocketKit/MyList/ItemsList/SavedItemsList/SavedItem+ItemsListItem.swift
PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewModel.swift
PocketKit/Sources/SaveToPocketKit/URLExtractor.swift
PocketKit/Tests/SaveToPocketKitTests/URLExtractorTests.swift

Improves link extraction when sharing from certain apps that may share a deep-link into their app (like Ivory).
IN-1469
- If the shared item is a URL
- If the URL is http(s), use the URL
- If the URL is not, attempt to find the first included link that _is_ http(s)
- If the shared item is a String
- If the string _is_ a URL, use the string as a URL
- If the string contains a URL, find the first included link that is http(s)
- If the string does not contain a URL, do nothing (error) 
Any time a URL is used, percent encoding is first removed. This simplifies what's stored in the local db, as well as what's sent to the backend. We want to ensure as much consistency between platforms as we can, here.

refactor(saveto): improve link extraction when sharing to pocket

---

PocketKit/Sources/PocketKit/MyList/EmptyStates/EmptyStateView.swift

Fix title and subtitle in empty state
IN-1385
Discussed with Tais on creating a maxWidth on `380` for the empty state text. This will apply to iPhone and iPad. 
Navigate to all the empty states and verify that they look like the screenshots below.
| iPhone | iPad | 
| ---- | ---- | 
| ![Simulator Screenshot - iPhone 13 mini - 2023-05-30 at 16 09 58](https://github.com/Pocket/pocket-ios/assets/6743397/22092577-58b8-4c7e-9f6b-739b1355e8b8) | ![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-05-30 at 16 10 59](https://github.com/Pocket/pocket-ios/assets/6743397/38d0bc20-61d5-4498-a119-660553fabb7c) |

fix(emptystate): fix empty state title and subtitle

---

PocketKit/Sources/Analytics/AppEvents/SaveTo.swift
PocketKit/Sources/Analytics/Events/System.swift
PocketKit/Sources/SaveToPocketKit/SavedItem/SavedItemViewModel.swift
PocketKit/Sources/SaveToPocketKit/URLExtractor.swift

Updates `Log` usage in `URLExtractor` to switch from `message` to `breadcrumb`. One `message` is newly captured if and only if no URL could be saved at the _end_ of parsing all item providers.
Most things that may happen in `URLExtractor` are not "actionable", but the final state of "couldn't save anything" _might_ be. So, if we breadcrumb up until the "couldn't save anything" scenario, we'll only have one general message that may prove fruitful, and all the things that might have led us there.

refactor(saveto): update URLExtractor logging

---

PocketKit/Sources/Localization/Resources/en.lproj/Localizable.strings
PocketKit/Sources/Localization/Strings.swift
PocketKit/Sources/PocketKit/FeatureFlagService.swift
PocketKit/Sources/PocketKit/LoggedOut/LoggedOutViewController.swift
PocketKit/Sources/PocketKit/Main/MainViewModel.swift
PocketKit/Sources/PocketKit/MyList/EmptyStates/Search/ErrorEmptyState.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/Textile/Style/Style+SwiftUI.swift
PocketKit/Sources/Textile/Views/Banner/BottomNotification.swift
PocketKit/Sources/Textile/Views/Report/ReportField.swift
PocketKit/Sources/Textile/Views/Report/ReportHeader.swift
PocketKit/Sources/Textile/Views/Report/ReportIssueView.swift
PocketKit/Tests/PocketKitTests/Search/SearchViewModelTests.swift
Tests iOS/MyList/SearchTests.swift

Add refinements to our Report an Issue UI and added a feature flag to show / hide the report an issue button for the empty state view and banner view
IN-1524
* Created new `ReportHeader` view and modify `ReportIssueView` to prevent users from editing their email
* Created feature flag `perm.ios.report_issue` that determines whether to show or hide the report button for the error empty state and error banner view
| iPhone | 
| ------  |
| ![image](https://github.com/Pocket/pocket-ios/assets/6743397/1a638721-2aed-4f1a-8e04-89efc28b6d63) |

feat(reportIssue): add UI refinements

---

PocketKit/Sources/PocketKit/MyList/ItemsList/UIKit/SavedItemsList/SavedItemsListViewModel.swift
Tests iOS/MyList/ArchiveFiltersTests.swift
Tests iOS/MyList/SavesFiltersTests.swift

Address bug where tags menu appears when tapping on Sort filter after a user filters their list with a specific tag
IN-1256
* Move presenting tag view to `handleFilterSelection` from `fetch`
* Allow tags list to be filtered through sorting by passing the proper filter values to our local store. Created `getPredicate` to return the proper filter cases
* Added two UI tests to cover the scenario if a user filters their list by a specific tag and then taps on the sort option
1. Nav to Saves
2. Tap Tagged filter
3. Select a tag
4. Click Sort / Filter in the filter menu
5. Confirm that tag menu does not appear and the list is sorted
| Video Capture |
| --- | 
| https://github.com/Pocket/pocket-ios/assets/6743397/b7a2f33c-c9eb-4a1b-9d5a-238e2ad54900 |

fix(filters): fix bug where tag menu appears when trying to sort

---

PocketKit/Sources/PocketKit/FeatureFlagService.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewModel.swift
PocketKit/Sources/PocketKit/Item/Item+Extensions.swift
PocketKit/Sources/PocketKit/Main/MainViewModel.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/UIKit/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Tests/PocketKitTests/HomeViewModelTests.swift
PocketKit/Tests/PocketKitTests/ItemExtensionsTests.swift
PocketKit/Tests/PocketKitTests/SlateDetailViewModelTests.swift

See Title
https://featureflags.readitlater.com/projects/default/features/perm.ios.disable_reader
Add new feature flag
Change the shouldOpenInWebview computed var to a func
Add an override to the function to accept a boolean, if true always use the web.
App should function as normal with the featureflag disabled
If enabled it should make all content; saves, archives and home screen render in the web view.

feat(killswitch) Add and enable featureflags for a Reader killswitch

---

PocketKit/Sources/ItemWidgetsKit/Views/ItemWidgetsRow.swift

* This PR sets a the vertical thumbnail size according to the set aspect ratio, to avoid layout issues
* Update `ItemWidgetsRow`, add a `height` value for the thumbnail frame
* Build this branch, install one or more widgets, and make sure the UI looks good

Item Widgets: fix vertical thumbnail size

---

PocketKit/Sources/PocketKit/Home/HomeViewModel.swift

When a Recommendation doesn't have a slate/slateLineup we were logging a message, the only thing we didn't do after this was to log analytics.
Therefore I moved the message log to a breadcrumb.
https://getpocket.atlassian.net/browse/IN-1284

fix(Sentry) Change a log to a breadcrumb

---

Pocket.xcodeproj/project.pbxproj
bitrise.yml
fastlane/Appfile
fastlane/Fastfile

Updates bitrise signing to use manual provisioning profiles, and apple ID-based auth for TestFlight uploads. This removes waiting for builds to process, as well as submitting the release build to a specific group, since those features are not currently available when using account-based auth.
After app transfer, we were required to change our API-key based authentication to account-based authentication, and the featureset when using account-based auth is smaller; i.e, we can only submit to TestFlight, and no longer wait for a build to stop processing, or submit to a group.

ci: update bitrise signing

---

PocketKit/Sources/SharedPocketKit/Migrations/LegacyUserMigration.swift
PocketKit/Sources/SharedPocketKit/UserDefaultsKey.swift
PocketKit/Tests/SharedPocketKitTests/LegacyUserMigrationTests.swift

Upon performing an app transfer, users will have to be migrated once again to ensure their session information is moved into the keychain, as the previous keychain is unavailable after app transfer. 
This pull request should _only_ be merged when preparing the first app update after app transfer.
IN-1540
This is an extension of the legacy user migration, which is live and seems to be working properly. This pull request forces the migration to be run (again) if the app has not been transferred into the new org. However, this "force" is secondary to the original logic for necessitating a migration (e.g 7 -> 8). 
This migration is _really_ in place for users who were logged into Pocket 8 pre-transfer, and "migrating" the keychain over post-transfer. The ways this works is that a current user …

feat(migration): force user migration after app transfer

---

PocketKit/Sources/Textile/Animations/EndOfFeedAnimationView.swift

Offload end-of-feed animation loading to prevent loading the animation on the main thread.
https://github.com/airbnb/lottie-ios/issues/872#issuecomment-1176773074

refactor: offload end-of-feed animation loading to background thread

---

PocketKit/Sources/PocketGraph/Operations/Queries/GetCollectionBySlugQuery.graphql.swift
PocketKit/Sources/PocketGraph/Schema/SchemaMetadata.graphql.swift
PocketKit/Sources/PocketGraph/user-defined-operations/collections.graphql
PocketKit/Sources/PocketGraphTestMocks/Collection+Mock.graphql.swift
PocketKit/Sources/PocketGraphTestMocks/CollectionAuthor+Mock.graphql.swift
PocketKit/Sources/PocketGraphTestMocks/CollectionStory+Mock.graphql.swift
PocketKit/Sources/PocketGraphTestMocks/MockObject+Unions.graphql.swift
PocketKit/Sources/Sync/CoreDataInitializers/Collection+CoreDataClass.swift
PocketKit/Sources/Sync/CoreDataInitializers/Collection+CoreDataProperties.swift
PocketKit/Sources/Sync/CoreDataInitializers/CollectionAuthor+CoreDataClass.swift
PocketKit/Sources/Sync/CoreDataInitializers/CollectionAuthor+CoreDataProperties.swift
PocketKit/Sources/Sync/CoreDataInitializers/CollectionStory+CoreDataClass.swift
PocketKit/Sources/Sync/CoreDataInitializers/CollectionStory+CoreDataProperties.swift
PocketKit/Sources/Sync/CoreDataInitializers/Item+CoreDataProperties.swift
PocketKit/Sources/Sync/PocketModel.xcdatamodeld/.xccurrentversion
PocketKit/Sources/Sync/PocketModel.xcdatamodeld/PocketModel 3.xcdatamodel/contents

Update Core Data model to include Collection entities and remove unused graphQL fields
IN-1546
* Add two entities `Collection` and `CollectionStory` to `Pocket Model 2`
* Created the respective `+CoreDataClass` and `+CoreDataProperties`
* Add `collection` property to `Item` model
Verify that the models are created properly and relationships are accurate

feat(collections): add core data models

---

PocketKit/Sources/Localization/Resources/en.lproj/Localizable.strings
PocketKit/Sources/Localization/Strings.swift
PocketKit/Sources/PocketKit/Article/ReadableViewModel/SavedItemViewModel.swift
PocketKit/Sources/PocketKit/Collections/CollectionMetadataCell.swift
PocketKit/Sources/PocketKit/Collections/CollectionMetadataPresenter.swift
PocketKit/Sources/PocketKit/Collections/CollectionStoryViewModel.swift
PocketKit/Sources/PocketKit/Collections/CollectionViewController.swift
PocketKit/Sources/PocketKit/Collections/CollectionViewModel.swift
PocketKit/Sources/PocketKit/FeatureFlagService.swift
PocketKit/Sources/PocketKit/Home/HomeRecommendationCellViewModel.swift
PocketKit/Sources/PocketKit/Home/RecommendationCell.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/UIKit/ItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/UIKit/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift
PocketKit/Sources/PocketKit/MyList/SavesContainerViewModel.swift
PocketKit/Sources/Sync/Collection/CollectionModel.swift
PocketKit/Sources/Sync/Collection/CollectionService.swift
PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Sources/Sync/Source.swift
PocketKit/Sources/Textile/NSAttributedString+Extensions.swift
PocketKit/Sources/Textile/Style/Style+Recommendation.swift
PocketKit/Sources/Textile/Views/Collection/CollectionStyler.swift
PocketKit/Sources/Textile/Views/Collection/Style+Collection.swift
PocketKit/Tests/PocketKitTests/Support/MockSource.swift
PocketKit/Tests/SyncTests/PocketSourceTests.swift
PocketKit/Tests/SyncTests/Support/MockCollectionService.swift

Create native collection view (focused on UI portion)
IN-1549
* Created native collection view in UIKit using `CollectionViewController`, `CollectionViewModel` (based on `SlateDetailViewController`, `SlateDetailViewModel`)
* For the metadata of collection, created `CollectionMetadataCell` and `CollectionMetadataPresenter` (based on ArticleMetadataPresenter)
* For the stories, created `CollectionStoryViewModel` (based on `HomeRecommendationCellViewModel`) and uses `RecommendationCell`
* Added feature flag for native collections `perm.ios.native_collections`
* Added logic to open a collection on Saves in `SavedItemsListViewModel` as well as API service `CollectionService` to retrieve graphQL data which will be refactored in the future
1. Navigate to a collection in Saves list
2. Tap on the …

feat(collections): create native collection view

---

PocketKit/Sources/PocketGraph/Fragments/CollectionSummary.graphql.swift
PocketKit/Sources/PocketGraph/Fragments/CorpusItemParts.graphql.swift
PocketKit/Sources/PocketGraph/Fragments/CorpusRecommendationParts.graphql.swift
PocketKit/Sources/PocketGraph/Fragments/CorpusSlateParts.graphql.swift
PocketKit/Sources/PocketGraph/Operations/Queries/HomeSlateLineupQuery.graphql.swift
PocketKit/Sources/PocketGraph/user-defined-operations/unifiedHome.graphql

*This PR adds the `Collection.slug` to a `CorpusItem` fetched from Unified Home
* Issue number in branch name
* Update `unifiedHome.graphql`, add `CollectionSummary` (at this moment, it only contains `slug`)
* No UI changes at the moment. If you want to test that we are actually pulling the slug, you can set a conditional breakpoint (or a printout) in `Item+remoteMapping.swift`, inside the method `func update(from corpusItem: CorpusSlateParts.Recommendation.CorpusItem, in space: Space)` and check (for collections only) that `corpusItem.target?.asCollection?.slug` is not nil and actually contains the slug that you are expecting.

Native Collections: add Collection Slug to CorpusItem in Unified Home

---

PocketKit/Sources/PocketKit/Collections/CollectionViewController.swift
PocketKit/Sources/PocketKit/Collections/CollectionViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift

* Add Save and Archive to Nav Bar for Collection
* Add buttons for overflow menu (no actions associated for now, only foundation added)
Note: this only applies to Saves currently, will create a PR for Home once the work to present from Home is merged in
IN-1552, IN-1553
* Add nav bar buttons for Collections (Sav / Archive, Open in Web, Overflow Menu)
* Follow logic from `ReadableHostViewController` and `SavedItemViewModel`
**Archive**
and the Collection is saved,
when I look at the navigation bar,
then I should see an Archive button
and the Collection has been archived,
then the Collection view should be dismissed (i.e popped from the navigation stack)
when the Collection view is dismissed,
and look at the origin card for the Collection,
then the Save button should be in the "Save" state …

feat(collections): add saving and archiving a collection

---

PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/Sync/CoreDataInitializers/Recommendation+CoreDataProperties.swift
PocketKit/Sources/Sync/PocketModel.xcdatamodeld/PocketModel 3.xcdatamodel/contents
PocketKit/Sources/Sync/RemoteMapping/Item+remoteMapping.swift
PocketKit/Sources/Sync/RemoteMapping/SlateLineup+remoteMapping.swift
PocketKit/Sources/Sync/Requests.swift
PocketKit/Sources/Sync/Space/Space.swift
PocketKit/Tests/PocketKitTests/HomeViewModelTests.swift

* This PR allows opening collections in the native view from Home
* Issue number in branch name
* Add `collection` readable type
* Add `collectionSlug` field to `Recommendation
* go to Home
* tap on a collection
* make sure it opens in the native view

Native Collections: open collections in native view from Unified Home

---

PocketKit/Sources/PocketKit/Activity/PocketItemActivity.swift
PocketKit/Sources/PocketKit/Collections/CollectionViewModel.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/UIKit/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift
PocketKit/Tests/PocketKitTests/Collections/CollectionViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/Space+factories.swift

Update actions for overflow menu for a saved collection. Currently, addressed for saved item on Saves / Archive. Future PR for Home and not saved collection item.
IN-1554, IN-1555, IN-1557, IN-1556
* Add functionality for the respective actions related to a saved collection (similar functionality to `SavedItemViewModel`)
* Create Unit test for `CollectioViewModel` to tests the actions
and the Collection has been saved,
when I look at the navigation bar,
then I should see an Overflow button with "Favorite", "Add tags", "Delete", and "Share" as visible options
**Favorite**
and the Collection is saved, and the Collection is unfavorited,
when I tap the overflow button and tap "Favorite",
and tap the overflow button again,
then I should see "Unfavorite" instead of "Favorite"
and the Collection …

feat(collections): update collection actions in overflow menu

---

PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewModel.swift

* This PR adds the native collections feature to slate detail and recent saves (Home)
* Issue number in branch name
* Update `HomeViewController`, `HomeViewModel`, `SlateDetailViewModel`: add logic to push the native collections view when a collection is selected from either recent saves or slate detail.
<p align=center>
</p>

Native Collections: show native collection view from slate detail and recent saves

---

PocketKit/Sources/PocketKit/Collections/CollectionViewController.swift
PocketKit/Sources/PocketKit/Collections/CollectionViewModel.swift
PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift
PocketKit/Sources/PocketKit/Report/ReportRecommendationHostingController.swift
PocketKit/Sources/PocketKit/Report/ReportRecommendationView.swift
PocketKit/Tests/PocketKitTests/Collections/CollectionViewModelTests.swift
PocketKit/Tests/PocketKitTests/SlateDetailViewModelTests.swift

Add report and share actions for collections that have not been saved yet.
Additional Small Fixes
* Addressed build errors from main feature branch
* Add actions presentation logic to Home
* Fix Home spacing for collection view
* Add feature flags throughout
* IN-1603, IN-1602
* Refactor report view to be more flexible in taking a `url` as opposed to a `recommendation`
* Add report and share actions for Collection that is not a saved item
* Hide tab bar for native collection 
Given I have opened a Collection in the native Collection view,
and the Collection is saved,
when I tap the overflow button and tap "Report",
then the Pocket report view should open, reporting the currently opened Collection.
Given I have opened a Collection in the native Collection view,
and the Collection is saved, …

feat(collections): add report + share for not saved collection

---

PocketKit/Sources/PocketKit/Collections/CollectionStoryViewModel.swift
PocketKit/Sources/PocketKit/Collections/CollectionViewController.swift
PocketKit/Sources/PocketKit/Collections/CollectionViewModel.swift
PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Home/HomeViewModel.swift
PocketKit/Sources/PocketKit/Home/SlateDetailViewModel.swift
PocketKit/Sources/PocketKit/MyList/ItemsList/UIKit/SavedItemsList/SavedItemsListViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift
PocketKit/Sources/Sync/Collection/CollectionStoryModel.swift
PocketKit/Tests/PocketKitTests/Collections/CollectionViewModelTests.swift
PocketKit/Tests/PocketKitTests/SlateDetailViewModelTests.swift

Open stories from collections
Note: Unable to find a collection with ads, so did not validate the premium vs free user cane mentioned in test steps
IN-1551
* Created `createStoryViewModel` to clean up how we initialize the view model
* Added 2 published property to handle reader view and web view (`selectedReadableViewModel`, `presentedStoryWebReaderURL`)
* Main logic is in `selectItem` in which we check if an item is a saved item, recommendation (important in the case of a syndicated article) as well as utilizing current `shouldOpenInWebView` logic.
Since saving / archiving is being worked on, we can save items in a collection via web and then validate that opening it up gives us the proper view.
when I tap on a story that is not a syndicated article and is not saved,
then the story …

feat(collections): open story from collections

---

PocketKit/Sources/PocketKit/Collections/CollectionStoryViewModel.swift
PocketKit/Sources/PocketKit/Collections/CollectionViewController.swift
PocketKit/Sources/PocketKit/Collections/CollectionViewModel.swift
PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/Main/MainViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift
PocketKit/Sources/PocketKit/MyList/SavesContainerViewModel.swift
PocketKit/Tests/PocketKitTests/Collections/CollectionViewModelTests.swift

Add overflow actions for stories (reporting / sharing)
IN-1561, IN-1562
* Add `overflowActions` for stories and created published properties on `CollectionViewModel` so that presentation logic can be triggered from `HomeViewController` similar to how we do with slate details
Please verify through both Home, Saves
and have scrolled to any Story,
when I tap the overflow menu,
and tap "Share",
then a share sheet with a link to the Story should open
and have scrolled to any Story,
when I tap the overflow menu,
and tap "Report",
then a Report view for the Story should open
https://github.com/Pocket/pocket-ios/assets/6743397/1e5fa97b-ed68-4c31-9721-e30c9e8805ab

feat(collections): add overflow actions for stories - report and share

---

PocketKit/Sources/PocketKit/FeatureFlagService.swift
PocketKit/Sources/Sync/PocketSource.swift
PocketKit/Sources/Sync/Source.swift
PocketKit/Sources/Sync/Space/Space.swift
PocketKit/Tests/PocketKitTests/Support/MockSource.swift

Fixes an app hang (commonly seen on initial login) by utilizing in-memory caching of feature flags when checking assignments.
An app hang was commonly visible when initially signing in (with a large account) and immediately attempting to switch tabs. After pausing execution, it appeared as if Sentry, when requesting sampling rates, was forcing its closure(s) on the main thread, including downstream tasks, such as fetching an object from Core Data. I _think_ what was happening is that Sentry would call a closure on the main thread, with the side effect of fetching an object from a (background) context _from_ the main thread, where the context was being used heavily, and already on another thread.
This pull request fixes the fetching of feature flag (assignments / payloads) by utilizing an …

refactor(feature-flags): check assignment from in-memory cache

---

PocketKit/Sources/Analytics/AppEvents/Collection.swift
PocketKit/Sources/PocketKit/Collections/CollectionStoryViewModel.swift
PocketKit/Sources/PocketKit/Collections/CollectionViewController.swift
PocketKit/Sources/PocketKit/Collections/CollectionViewModel.swift
PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift

Implement analytics for native collections and verified that only good events are returned.
* IN-1600
Added the following analytic events
```
// Existing Analytics
collection.screen - user views native collection screen
collection.save - tapping on save icon in nav bar (has never been saved)
collection.unsave - tapping on archive icon in nav bar
collection.story.open - when a user taps on a story in a collection
collection.story.save - Fired when a user Saves a story in a collection
collection.story.unsave - Fired when a user unSaves a story in a collection
// New Analytics
collection.un-archive - tapping on save icon in nav bar (moves from archive to save)
collection.overflow - tapping on overflow menu
collection.overflow.favorite - tapping on overflow menu and favoriting the collection …
```

feat(collections): implement analytics

---

PocketKit/Sources/PocketKit/Collections/CollectionViewModel.swift
PocketKit/Sources/PocketKit/Home/HomeViewController.swift
PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift
PocketKit/Sources/Sync/RemoteMapping/Item+remoteMapping.swift
PocketKit/Tests/PocketKitTests/Collections/CollectionViewModelTests.swift

Open sub-collections from a collection
IN-1606
* Change `selectedReadableViewModel` from `ReadableViewModel` to `ReadableType` and renamed to `selectedItem` to be more general to allow stories to have the native collection experience
* Refactor both home and saves to account for this change and perform presentation logic depending on the readable type
* Add `collection` property to `Item` for a story to determine if a story is a collection type or not
and I view a story that is also a collection,
when I tap on that story, 
then I should see the native collection experience.
https://github.com/Pocket/pocket-ios/assets/6743397/b87bbef2-1725-465e-ab4f-ac197704d2df

feat(collection): add sub collections

---

PocketKit/Sources/PocketKit/MyList/SavesContainerViewController.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift

Open native collection experience from search
IN-1607
Add existing logic that we are using the present native collection from Home and Saves and add it over to Search
and I have at least one Collection that appears in the search results,
when I tap on the Collection item,
then the native Collection view should appear for the Collection.
https://github.com/Pocket/pocket-ios/assets/6743397/57a40374-8afc-412e-ab7c-78dd9ecd93fd

feat(collections): add native collections experience to search

---

PocketKit/Sources/PocketKit/Collections/CollectionViewController.swift
PocketKit/Sources/PocketKit/Collections/CollectionViewModel.swift
PocketKit/Sources/PocketKit/MyList/EmptyStates/EmptyStateView.swift
PocketKit/Sources/PocketKit/MyList/EmptyStates/EmptyStateViewModel.swift
PocketKit/Sources/PocketKit/MyList/EmptyStates/Search/ErrorEmptyState.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchView.swift
PocketKit/Sources/PocketKit/MyList/SearchItemsList/SearchViewModel.swift
PocketKit/Sources/PocketKit/Report/ReportIssueButton.swift
PocketKit/Tests/PocketKitTests/Collections/CollectionViewModelTests.swift
PocketKit/Tests/PocketKitTests/Support/MockSource.swift
PocketKit/Tests/PocketKitTests/Support/Space+factories.swift

Add offline / error screen for native collections
IN-1596
* Added `error` section to collections 
* Use network monitor to observe changes to network via `observeNetworkChanges` and `handleNetworkChange`
* Refactor `ReportIssueButton` to be more flexible and not tied to search
* Created error view by using `ErrorEmptyState(featureFlags: featureFlags, user: user)` for the empty state view
and the collection is being loaded remotely,
when the remote download errors,
then I should see an error view replacing the spinner.
and then collection is being loaded remotely,
and there is no network connection available (i.e offline),
when the screen is presented,
then I should see an error view replacing the spinner.
and there was no network connection available (i.e offline),
and the error view is …

feat(collections): add error / offline view

---

PocketKit/Sources/PocketKit/UserManagementService.swift
PocketKit/Sources/SharedPocketKit/NotificationCenter+EventNames.swift
PocketKit/Sources/Sync/ApolloClient+Extensions.swift
PocketKit/Tests/PocketKitTests/Notifications/PushNotificationServiceTests.swift
PocketKit/Tests/PocketKitTests/UserManagementServiceTests.swift

Log a user out of the app when a GraphQL responds with a 401 for any given request.
IN-1347
See code comments.
TL;DR: Add async interceptor that published a notification when there is a GraphQL response with a 401 status code, handle that notification in `UserManagementService` by logging out.

feat(sync): log out user on 401 GraphQL response

---

Assets.xcassets/textfieldURL.colorset/Contents.json
PocketKit/Sources/PocketKit/Article/Cells/ArticleComponentTextCell.swift
PocketKit/Sources/Textile/Style/Colors/Colors.xcassets/UI/textfieldURL.colorset/Contents.json
PocketKit/Sources/Textile/Style/Colors/Palettes.swift

The standard blue highlight was difficult to read against the dark background of darkmode. Added a more legible color for URLs
https://getpocket.atlassian.net/browse/IN-1608
Added the new color to the standard Asset catalog. Adding to the Textile catalog added the need to import Textile for just one color on one line and seemed excessive. 
Open and item that is  displayed in Reader.
Check for URLs, all should be the new teal color in darkmode and the standard blue in light mode.

Add new color for Darkmode URLs in Reader

---

PocketKit/Sources/Localization/Resources/en.lproj/Localizable.strings
PocketKit/Sources/Localization/Strings.swift
PocketKit/Sources/PocketKit/Collections/CollectionViewController.swift
PocketKit/Sources/PocketKit/Collections/CollectionViewModel.swift
PocketKit/Sources/PocketKit/Home/LoadingCell.swift
PocketKit/Sources/PocketKit/Settings/DeleteAccountView.swift
PocketKit/Sources/SharedPocketKit/PocketLoadingView.swift
PocketKit/Sources/SharedPocketKit/UIView+Utilities.swift
PocketKit/Sources/Textile/Style/Style+DeleteAccountView.swift
PocketKit/Sources/Textile/Style/Style+PocketLoadingView.swift
PocketKit/Tests/PocketKitTests/Collections/CollectionViewModelTests.swift
Tests iOS/Support/Elements/PocketAppElement.swift

This PR replaces the standard spinner animation with the shapes animation already used in account deletion
* Generalized `DeleteLoadingView` by changing it into a configurable `PocketLoadingView`
* NA
* Tap on a collection that has not been loaded locally
* Verify that you see the animation (see video below)
* You should also see the same animation when loading home or a slate
https://github.com/Pocket/pocket-ios/assets/34376330/997f0303-9dfc-4549-83e0-cbbf2c1797fc

Loading View - Replace spinner with shapes animation
